### ISSUE TITLE
Adjust hasGeometry structure

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#101]
A current example http://lobid.org/gnd/4210884-6.json:

```json
{
  "id": "http://d-nb.info/gnd/4210884-6",
  "hasGeometry":[
    {
      "type":"Point",
      "asWKT":[
        {
          "type":"WKTLiteral",
          "@value":"Point ( +011.481700 +063.793320 )"
        }
      ]
    }
  ]
}
```

We just have to adjust the context a bit adding the type to asWKT there, see http://tinyurl.com/y7872mxl

**Comment by acka47** [comment]
For now, we will only remove the extra object with the `@value`. Before we move this to production, we will have to think about aligning with EntityFacts, where the next release will contain geo coordinates and they use another approach, see https://wiki.dnb.de/pages/viewpage.action?pageId=134055670.

I just talked to @jentschk and there might be some future adjustments to the EntityFacts go information. She will open a discussion about this on a mailing list.

**Comment by fsteeg** [comment]
Deployed to test:

http://test.lobid.org/gnd/4210884-6.json
http://test.lobid.org/gnd/4210884-6

**Comment by acka47** [comment]
+1 for the adjustments. @jentschk started a mailing list thread at http://lists.dnb.de/pipermail/lds/2018-May/000118.html regarding the JSON-LD representation of geodata (including polygons). We should provide some feedback soon.
