### ISSUE TITLE
Issues with realIdentity field

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#103]
See http://lobid.org/gnd/118624822.json `gnd:realIdentity`

- not properly set up in context ("gnd:" prefix)
- inconsistent structure (not an array)

**Comment by fsteeg** [comment]
Deployed to test:

http://test.lobid.org/gnd/118624822.json
http://test.lobid.org/gnd/118624822

**Comment by ChristophEwertowski** [comment]
+1
