### ISSUE TITLE
Most GND entries are currently missing

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#109]
This is a serious bug. We currently only have around 3 Million entities indexed although it should be around 14 Million. What happened?

**Comment by acka47** [comment]
> All data is up'n running again.

Nope, lobid-gnd and lobid-organisations are still missing approximately half of the resources.

**Comment by dr0i** [comment]
Well, 2 shards aren't assigned for gnd. This wouldn't be a problem if there were at least one replica configured, which it isn't.
As for organisations: these are not indexed in our cluster.
Assigning @fsteeg.

**Comment by dr0i** [comment]
I switched the `gnd`-alias to the index build  3 days before one used, that is from 2018-05-17 to 2018-05-14. I don't know exactly effects but hope it's better to have all resources instead of all the features. Let's work this out tomorrow.

**Comment by fsteeg** [comment]
> As for organisations: these are not indexed in our cluster. Why there is missing data I cannot see.

If this is an issue, it's probably unrelated and might have been this way for a while. But I also seem to remember that we talked about the number of "over 20.000" on the main page being no longer correct (after some changes in the data, like removing ebook packages or something like that?)

**Comment by acka47** [comment]
The number of [entries with an ISIL](http://lobid.org/organisations/search?q=_exists_%3Aisil) (13,980) seems correct. But the number of [entries with a DBS ID](http://lobid.org/organisations/search?q=_exists_%3AdbsID) (4892) seems off. Looking at a dbs.csv from 2017 it has 9000 lines...

However, I have to speak to Ira anyhow. This can wait until I have talked to her.

**Comment by fsteeg** [comment]
Reindexed base dump and updates, closing. See: http://lobid.org/gnd/search
