### ISSUE TITLE
Enable initiating a search for properties with multiple nodes in relation view

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#113]
Like we just discussed. Instead of offering an OR search for all the relation-entities only offer searches for a specific relation. E.g. at http://lobid.org/gnd/11850391X#rels when clicking on the edge to Günther Anders only search for other entitities with familialRelationship to him.

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/gnd/11850391X#rels

**Comment by acka47** [comment]
I like. +1
