### ISSUE TITLE
Some problems with auto suggest

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#114]
1. When typing in a complex query on different fields that are deeper in the JSON hierarchy it takes quite long to load auto-suggest and can easily happen that one accidentally clicks a suggestion which means losing the query one has typed in irretrievably.
2. When submitting a search and viewing the result list it can easily happen that the auto-suggest box is opened causing some confusion.

**Comment by acka47** [comment]
Re 2.), auto-suggest should simple be deactivated when I am already viewing a result list.

**Comment by fsteeg** [comment]
I don't think we can do anything about 1) and I can no longer reproduce 2) (I think I often got it after browsing the full list, which used to have `*` in the search bar. This is no longer the case. If I enter a search term and browse the list, the suggestions don't pop up for me).

From my point of view we can close this.

**Comment by fsteeg** [comment]
Deployed to test:

https://test.lobid.org/gnd/search?q=type%3APerson (no autofocus, hold shift -> no suggestions)
https://test.lobid.org/gnd/search?q= (empty `q`, autofocus, hold shift -> no suggestions)

**Comment by acka47** [comment]
Re 1.), I couldn't reproduce it on production (on Chromium) even if I am pressing a key. So +1 for that.
Re 2.), wouldn't it be possible (and also make sense) to disable auto-suggest when a character sequence covered by `[a-z]\:[a-zA-Z]` is typed in? I assume that you don't expect any auto suggest when typing a Lucene query string query.

**Comment by acka47** [comment]
Ok. Let's deploy as is and reopen if it still gets on our nerves in the future. +1
