### ISSUE TITLE
Provide GND in (J)SKOS

### ISSUE THREAD

**Issue by nichtich** [hbz/lobid-gnd#119]
The current JSON-LD representation of GND records is based on GND ontology like the RDF representation provided by DNB. Simple use cases would more benefit from SKOS. In project coli-conc we use a mapping of GND ontology to JSKOS (see [this file](https://github.com/gbv/coli-conc.gbv.de/blob/master/services/GNDService.yaml)) which is a subset of SKOS. We should finish a common mapping of GND ontology to SKOS and provide GND in SKOS or JSKOS.

**Comment by acka47** [comment]
Sounds interesting. We could offer JSKOS via a separate content header. Before that we would have to finish the mapping and maybe check it against http://lobid.org/gnd/context.jsonld so that all properties used in the GND data are covered. (There are more properties than those from the GND ontology and from time to time new ones are added.)

**Comment by acka47** [comment]
Talking to @nichtich, it would suffice for his use cases if we only served single entries as JSKOS. No need to offer it for result sets of API queries.

**Comment by nichtich** [comment]
A different path to get SKOS would be from MARCXML. I tried mc2skos and stumbled upon some errors in MARC data of GND provided by DNB: https://github.com/scriptotek/mc2skos/issues/56. This would not cover all properties but may be enough to start with.

**Comment by acka47** [comment]
As Cocoda already uses lobid-gnd based on the reconciliation API, I assume this is not needed anymore and can be closed. Right, @nichtich ?

**Comment by nichtich** [comment]
We still transform GND from DNB in RDF to JSKOS and use lobid for search only. RDF lacks narrower relations so another source is needed. If lobid does not provide JSKOS, we will find another way.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
