### ISSUE TITLE
Use new EntityFacts dump

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#130]
DNB announced a new EntityFacts dump, see https://lists.dnb.de/pipermail/lds/2018-June/000121.html. We should update our EntityFacts index using this dump (@dr0i) and then update lobid-gnd (@fsteeg).

**Comment by fsteeg** [comment]
Started conversion of `GND.rdf` using `entityfacts-20180629-12324` on `weywot2`.

**Comment by fsteeg** [comment]
Deployed new index based on new EntityFacts dump to test: http://test.lobid.org/gnd/search

**Comment by acka47** [comment]
+1 It works, ORCID icons are now shown as requested in https://github.com/hbz/lobid-gnd/issues/125#issuecomment-398350438, see e.g. http://test.lobid.org/gnd/1049808495.

**Comment by fsteeg** [comment]
Updated index aliases `gnd` and  `entityfacts` to the new indices, closing.

See http://lobid.org/gnd/1049808495
