### ISSUE TITLE
Add thumbnail URL to json:suggest parameter & support preview parameter

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#132]
We learned from the OpenRefine reconciliation preview API that it makes sense to send along an image of a suggested entity to better support selection/identification of an entity. Discussing this one the phone with @fsteeg, we decided to:

1. Add an image link to the thumbnail in the standard `format=json:suggest` response, e.g. for http://lobid.org/gnd/search?q=Twain&format=json%3Asuggest
```json
[
  {
    "label":"Twain, Shania | 1965- | Sängerin, Komponistin",
    "image":"https://commons.wikimedia.org/wiki/Special:FilePath/ShaniaTwainJune2011.jpg?width=270",
    "id":"http://d-nb.info/gnd/121570924",
    "category":"Individualisierte Person"
  },
  {
    "label":"Twain, Mark | 1835-1910 | Lotse, Schriftsteller, Drucker, Journalist, Soldat",
    "image":"https://commons.wikimedia.org/wiki/Special:FilePath/MarkTwain.LOC.jpg?width=270",
    "id":"http://d-nb.info/gnd/118624822",
    "category":"Individualisierte Person"
  }
]
```
2. Support a `format=preview` parameter that gives back a HTML snippet with the information from the suggest parameter (including label, type and image).

We should think about using another `width` for the images as the current one (270) is too much for the purpose of showing a small preview.

**Comment by fsteeg** [comment]
3. Use the `format=preview` option to implement the [preview API](https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API#preview-api) for OpenRefine reconciliation

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/gnd/search?q=Twain&format=json:suggest
http://stage.lobid.org/gnd/118624822?format=preview
http://stage.lobid.org/gnd/search (see suggestions)
http://stage.lobid.org/gnd/reconcile (use in OpenRefine, see http://stage.lobid.org/gnd/api#openrefine)

**Comment by ChristophEwertowski** [comment]
+1
