### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#133]
@fsteeg and me discussed this offline. We need at least three parts of documentation in addition to the [API page](https://lobid.org/gnd/api):

1. a description of the UI: search, auto suggest, filtering/facetting, detail view (links vs. looking glass), relations (clicking nodes and edges)
2. a tutorial for building complex queries based on an inspection of example entries
3. a tutorial on how to do OpenRefine reconciliation with the lobid-gnd API

1.) might be best published alongside the API documentation under a new tab "Documentation". 2.) and 3.) are best published as blog post and linked to from the UI documentation. But we haven't made a final decision on how to publish it yet.

**Comment by fsteeg** [comment]
Added links to the bulk download blog section from the `gzip` part in the API doc on test:

https://test.lobid.org/gnd/api#content_types

And to the OpenRefine blog post section from the OpenRefine part in the API doc:

https://test.lobid.org/gnd/api#openrefine

With the links under 'Dokumentation' in the `i` menu (already on production) I think we're done here.

**Comment by fsteeg** [comment]
Removed beta badge on test, as discussed offline: https://test.lobid.org/gnd

**Comment by acka47** [comment]
> Added links to the bulk download blog section from the gzip part in the API doc on test:

> https://test.lobid.org/gnd/api#content_types

I think that a separate section called "Bulk downloads" would be more user friendly.

> And to the OpenRefine blog post section from the OpenRefine part in the API doc:

> https://test.lobid.org/gnd/api#openrefine

There also is a link to the lobid-organisations reconciliation API. I think we don't need it here as it is rather confusing. It should instead be added at https://lobid.org/organisations/api/de#openrefine.

**Comment by fsteeg** [comment]
Deplyed to stage:

https://stage.lobid.org/gnd/api#bulk_downloads
https://stage.lobid.org/gnd/api#openrefine

**Comment by acka47** [comment]
+1
