### ISSUE TITLE
Fix JSON default for "Accept: */*" header

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#137]
Curl's default `Accept: */*` header yields JSON lines, not JSON:

`curl -v http://lobid.org/gnd/search?q=Dom`

It should serve JSON, like it does without an `Accept` value:

`curl -v -H 'Accept:' http://lobid.org/gnd/search?q=Dom`

**Comment by fsteeg** [comment]
Deployed to test:

`curl http://test.lobid.org/gnd/search?q=Dom`

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Just noticed that `format=jsonl` doesn't work, see e.g. `curl http://test.lobid.org/gnd/search?q=Adrian+Pohl&format=jsonl`. Getting JSON Lines via the Accept header works, though: `curl --header "Accept: application/x-jsonlines"  http://test.lobid.org/gnd/search?q=Adrian+Pohl`

**Comment by fsteeg** [comment]
> Just noticed that format=jsonl doesn't work, see e.g. curl http://test.lobid.org/gnd/search?q=Adrian+Pohl&format=jsonl

That's due to the missing `"` around the URL, which causes the `&format=jsonl` part to be ignored:

`curl "http://test.lobid.org/gnd/search?q=Adrian+Pohl&format=jsonl"`

**Comment by acka47** [comment]
Ah, ok. then +1
