### ISSUE TITLE
Switch to new GND full dump format

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#146]
The full GND dumps are no longer published as a single RDF/XML file, see:
https://lists.dnb.de/pipermail/gnd-ontology/2018-July/000115.html
https://data.dnb.de/opendata/

We have two options:

- Switch to the HDT dump (Jena integration for HDT exists, but I'm not sure about the state of the project, the version published to central is from 2014, see https://search.maven.org/#search%7Cga%7C1%7Crdfhdt and https://github.com/rdfhdt/hdt-java/issues/32)
- Use the seven individual RDF/XML files

Any thoughts @acka47 @dr0i?

**Comment by dr0i** [comment]
> I'm not sure about the state of the project, 

I suppose the dnb is using the very same library to compress, so it should be save to use this library to decompress, and future incompatibilities seems unlikely.

**Comment by acka47** [comment]
As discussed last week, we should just use the seven individual files.

**Comment by fsteeg** [comment]
The full GND dump is now also available as N-Triples, s. https://data.dnb.de/opendata/ (`https://data.dnb.de/opendata/GND.nt.gz`)

**Comment by fsteeg** [comment]
I looked into using the N-Triples dump, but splitting that up into records will be tricky, and converting the full thing to RDF-XML is inefficient. I think we should stick to the plan from https://github.com/hbz/lobid-gnd/issues/146#issuecomment-423910315 and use the individual files (`https://data.dnb.de/opendata/T*gesamt*gnd.rdf.gz`).

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd/search

**Comment by acka47** [comment]
Regarding the compacted keys, I found one property that is still not compacted: `http://d-nb.info/standards/elementset/gnd#relatedSubjectHeading`. That is beacause we did not take into account that a typo was fixed some time ago. In the context it still read `relatedSubjecHeading` (without the "t"). Will fix that.

**Comment by acka47** [comment]
So, here is an overview over the things I have checked with the new dump:

- entries without `prefLabel` (related issue is #159): There are [253 entries without prefLabel](http://test.lobid.org/gnd/search?q=NOT+_exists_:preferredName) in lobid-gnd while we have only 15 of them in the original GND. So, at least 238 records that have been deleted in the GND are still in lobid-gnd.
- not-compacted properties: see the [comment above](https://github.com/hbz/lobid-gnd/issues/146#issuecomment-448154559). 
- `describedBy` object (#89): looks good, as said in https://github.com/hbz/lobid-gnd/issues/89#issuecomment-448161128 I will open an issue in the GND Jira for the 63 problematic cases.

**Comment by acka47** [comment]
Please deploy to production as this is already considerably better than the existing index.
