### ISSUE TITLE
Problems with sameAs relations

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#151]
Looking at the Kibana visualization at http://kibana.lobid.org/goto/28f53860e1b69a4fe70cacb6cd34be09 I wondered why only  ~ 6.4 M entries have a `sameAs` link to the DNB/GND itself. This should definitely be found in 100% of the entries. (Although, as not all entity types are covered by EntityFacts it musttn't be 100% but however, there still is something strange.)

So I took a look at all the entries where a `sameAs` link to DNB/GND is supposedly missing with the query http://lobid.org/gnd/search?q=NOT+sameAs.collection.id%3A%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ36578%22

In the results, there are some examples that are not in EntityFacts and thus don't have the sameAs link to DNB/GND, e.g. http://lobid.org/gnd/16255670-6

However, the result list also includes lots of entries that have the exact information in them I gave with boolean `NOT` and, thus they shouldn't be included in the results of this query, e.g. http://lobid.org/gnd/1013254899.

**Comment by acka47** [comment]
For the entries not covered by EntityFacts, i created #152. In this issue we should find out what is wrong with the search index.

**Comment by fsteeg** [comment]
> the result list also includes lots of entries that have the exact information in them I gave with boolean NOT and, thus they shouldn't be included in the results of this query

This was due to non-deleted `deprecatedUri` entries in the index. Fix deployed to test:

http://test.lobid.org/gnd/search?q=NOT+sameAs.collection.id%3A%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ36578%22

**Comment by acka47** [comment]
+1
