### ISSUE TITLE
Handle error on invalid queries

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#156]
See http://lobid.org/gnd/search?q=%2B%2Btest (enter `++test` in the search field)

- [x] Don't show error screen to user
- [x] Don't pollute log with stack traces

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/gnd/search?q=%2B%2Btest

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
+1
