### ISSUE TITLE
Some deprecatedUri statements missing

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#162]
Reported today by API user M.R.:

> Ich bin gerade beim Nutzen der Schnittstelle, um deprecated 
> GND IDs durch neue IDs zu ersetzen. Dabei habe ich das Gefühl, dass eine 
> Reihe von Einträgen bei precedingCorporateBody zu fehlen scheint. Ohne 
> es konkret verifizieren zu können (bei einigen ist nämlich tatsächlich 
> auch in der GND keine Verknüpfung vorhanden), düfte es sich um max. ca 
> 5% bei rund 3000 Records handeln. So sollten z.B. diese beiden verlinkt 
> sein: http://lobid.org/gnd/1027474-1.json 
> http://lobid.org/gnd/4430472-9.json (Alois Zettler, Elektrotechnische 
> Fabrik). Bei den folgenden kennt zumindest auch der http-Redirect der 
> GND (z.B. http://d-nb.info/gnd/4430472-9) den Verweis von deprecated auf 
> aktuell.

**Comment by acka47** [comment]
This is a bug. In the GND, 4430472-9 is redirected to 1027474-1:

```
$ curl -LiI http://d-nb.info/gnd/4430472-9
HTTP/1.1 301 Moved Permanently
Date: Fri, 14 Dec 2018 10:14:46 GMT
Server: Apache
Location: https://d-nb.info/gnd/4430472-9
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 301 Moved Permanently
Date: Fri, 14 Dec 2018 10:14:46 GMT
Server: Apache
Strict-Transport-Security: max-age=15552000
Location: /gnd/1027474-1
Link: </gnd/1027474-1>; rel="canonical"

HTTP/1.1 303 See Other
Date: Fri, 14 Dec 2018 10:14:47 GMT
Server: Apache
Strict-Transport-Security: max-age=15552000
Location: /gnd/1027474-1/about/html
Vary: Accept

HTTP/1.1 302 Found
Date: Fri, 14 Dec 2018 10:14:47 GMT
Server: Apache
Strict-Transport-Security: max-age=15552000
Location: https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid%3D1027474-1

HTTP/1.1 200 OK
Date: Fri, 14 Dec 2018 10:14:47 GMT
Server: Apache
Strict-Transport-Security: max-age=15552000
Set-Cookie: JSESSIONID=9-sMvmL7zbmF0bMl3PSYPv8nZIGS3YsTTn-WfJe-.prod-fly1; path=/; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:00 GMT
Content-Length: 30345
Content-Language: de-DE
Content-Type: text/html;charset=UTF-8
```

Furthermore, in the GND RDF a deprecated URI statement exists, see https://d-nb.info/gnd/1027474-1/about/lds:

```
<http://d-nb.info/gnd/1027474-1> a gndo:Company ;
	gndo:gndIdentifier "1027474-1" ;
	dnbt:deprecatedUri "http://d-nb.info/gnd/4430472-9" .
```

Why is this not reflected in lobid-gnd?

**Comment by acka47** [comment]
M.S. did provide more examples:

```
(DE-588)2137683-9 (DE-588)1085262928
(DE-588)16049174-5 (DE-588)1085304752
(DE-588)2164169-9 (DE-588)1085970604
(DE-588)133932-1 (DE-588)1085901270
(DE-588)5250127-9 (DE-588)1085312119
(DE-588)5078896-6 (DE-588)1085224465
(DE-588)16061923-3 (DE-588)1085302474
(DE-588)271664-1 (DE-588)1086972694
(DE-588)2081619-4 (DE-588)400554-5
(DE-588)18334-9 (DE-588)1089029284
(DE-588)1050567943 (DE-588)1088075754
(DE-588)16035271-X (DE-588)108521642X
(DE-588)2025333-3 (DE-588)1085304345
(DE-588)5092465-5 (DE-588)1086590457
(DE-588)10066059-9 (DE-588)108525285X
(DE-588)1081964936 (DE-588)1086556259
(DE-588)10065541-5 (DE-588)1085303365
(DE-588)5188635-2 (DE-588)1091105251
(DE-588)220802-7 (DE-588)1088198880
(DE-588)5343350-6 (DE-588)1086553926
(DE-588)5014921-0 (DE-588)1085306054
(DE-588)16022196-1 (DE-588)1086095626
(DE-588)5198189-0 (DE-588)1088220428
(DE-588)16052803-3 (DE-588)1088142028
(DE-588)2115238-X (DE-588)1086002393
(DE-588)2020138-2 (DE-588)1086756533
(DE-588)10060976-4 (DE-588)1088198058
(DE-588)1086341732 (DE-588)1086618149
(DE-588)5281591-2 (DE-588)1085263851
(DE-588)5029158-0 (DE-588)1086569695
(DE-588)111271-5 (DE-588)109110526X
(DE-588)2161036-8 (DE-588)108530597X
(DE-588)5007393-X (DE-588)1091105316
(DE-588)10200995-8 (DE-588)1085193632
(DE-588)1090624387 (DE-588)1086056434
(DE-588)7520120-3 (DE-588)1088221270
(DE-588)68031-X (DE-588)1085304930
(DE-588)2162858-0 (DE-588)1085263223
(DE-588)16113711-8 (DE-588)1085208168
(DE-588)7536012-3 (DE-588)1091105235
(DE-588)16010440-3 (DE-588)1085303470
(DE-588)1066748411 (DE-588)1088208495
(DE-588)5071547-1 (DE-588)1088846505
(DE-588)1008163-X (DE-588)1088221246
(DE-588)275741-2 (DE-588)1086891325
(DE-588)273282-8 (DE-588)108519499X
(DE-588)2025728-4 (DE-588)1086042603
(DE-588)1090665172 (DE-588)1085883612
(DE-588)5534402-1 (DE-588)1085307751
(DE-588)5003987-8 (DE-588)1085264866
(DE-588)1064691684 (DE-588)1086090721
(DE-588)2096569-2 (DE-588)1085216470
(DE-588)16084242-6 (DE-588)1086779320
(DE-588)2122243-5 (DE-588)1088838839
(DE-588)66139-9 (DE-588)108657950X
(DE-588)1087384699 (DE-588)1085984001
(DE-588)2132451-7 (DE-588)1085306917
(DE-588)6520829-8 (DE-588)1086676521
(DE-588)500821-9 (DE-588)1085263673
(DE-588)108684582X (DE-588)1085980251
(DE-588)31563-1 (DE-588)108520975X
(DE-588)10183793-8 (DE-588)1085278395
(DE-588)6023686-3 (DE-588)1085306984 
```

**Comment by acka47** [comment]
With #146, a lot of redirects are there now. However, there is also one out of three or four resources I tested that does not redirect:

- https://lobid.org/gnd/108520975X --should redirect to--> https://lobid.org/gnd/31563-1

**Comment by fsteeg** [comment]
>     * https://lobid.org/gnd/108520975X --should redirect to--> https://lobid.org/gnd/31563-1

But there is no connection from 31563-1 to 108520975X (`deprecatedUri`, or anything like `predecessor`).

**Comment by acka47** [comment]
You are right (although these are duplicate records and, thus, a redirect would make sense). Then, obviously the list we got by email is not correct.

However, it is likely that the problem will occur again when we only handle updates. Somehow the `deprecatedUri` statements have not been added to the JSON-LD so that no redirect is triggered.

**Comment by fsteeg** [comment]
> Somehow the `deprecatedUri` statements have not been added to the JSON-LD so that no redirect is triggered. Or do you have an explanation for this? Until we have one I will leave this issue open.

It seems the connection from 31563-1 to 108520975X is missing in the DNB data:

http://d-nb.info/gnd/31563-1/about/lds
http://d-nb.info/gnd/31563-1/about/marcxml

But still the DNB redirects 108520975X to 31563-1:

http://d-nb.info/gnd/108520975X/about

**Comment by fsteeg** [comment]
This seems to be resolved by now:

> https://lobid.org/gnd/108520975X --should redirect to--> https://lobid.org/gnd/31563-1

**Comment by acka47** [comment]
Yes, looks good now. Closing.
