### ISSUE TITLE
Allow sorting of result list

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-gnd#164]
Customers Björn and Axel asked about a way of getting a sorted result list.
Easiest way would probably be to use the [search URI request with the `sort` parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html).
Then we could do something like this:
http://lobid.org/gnd/search?q=scholl&sort=preferredName:asc

**Comment by fsteeg** [comment]
Deployed to test: [https://test.lobid.org/gnd/search?q=Ehrenfeld&sort=preferredName.keyword:asc](https://test.lobid.org/gnd/search?q=Ehrenfeld&sort=preferredName.keyword:asc)

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
Note: don't forget to inform  Björn and Axel when deployed.
