### ISSUE TITLE
Update labels for Agrelon

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#165]
Our colleage D.B. just told me that it would be strange to use the label "Elter" in the relation graph, e.g. http://lobid.org/gnd/120745305#rels. I started telling ehr that we are using the labels from [Agrelon](https://d-nb.info/standards/elementset/agrelon#) (Agent Relationshio Ontology) only to find out that we are using an old version of the ontology for the labels. In the new version the label is "hat Elternteil". We should update the lobid-gnd labeling mechanism accordingly.

**Comment by acka47** [comment]
Also, the GNDO was updated, see https://d-nb.info/standards/elementset/gnd. So please also update it.

Both improvements were initiated with a Jira issue opened by @ChristophEwertowski ([GND-51](http://jira.dnb.de/browse/GND-51?jql=text%20~%20%22elter%22)). ;-) I was not notified because I did not open it...

Here is the text from the original Jira issue:

> Die deutsche Benennung von gnd:professionalRelationship (https://d-nb.info/standards/elementset/gnd#professionalRelationship) müsste "Berufliche Beziehung" lauten.
Bei gnd:opusNumericDesignationOfMusicalWork (http://d-nb.info/standards/elementset/gnd#opusNumericDesignationOfMusicalWork) müsste "Opus-Zählung des Musikwerks" stehen.

> Die deutsche Benennung von gnd:Manuscript lautet "Schriftdenkmal", was für "normale Menschen" nicht besonders eingängig ist. Warum nicht "Manuskript" nehmen? (https://d-nb.info/standards/elementset/gnd#Manuscript)

And in a comment:

> Ein Kollege wies mich noch auf die nicht gebräuchliche deutsche Benennung von "has parent" in AgRelOn hin: "hat Elter". "hat Elternteil" wäre wohl passender (oder wie im Spanischen "hat Vater oder Mutter") (https://d-nb.info/standards/elementset/agrelon#hasParent). Das gleiche trifft auch auf "Schwiegerelter" zu (https://d-nb.info/standards/elementset/agrelon#hasParentInlaw).

"Schriftdenkmal" was not changed, here the reasoning:

> "Schriftdenkmal" ist tatsächlich nicht sehr eingängig, aber „Schriftdenkmal“ ist ein Oberbegriff für Handschriften (in Codex- oder Rollenform, handschriftliche Archivalien…) und Inschriften (auf Runensteinen, an Bauwerken …). Der deutsche Begriff "Manuskript" würde hier also zu kurz greifen. Und im englischen gibt es keine passende Übersetzung für "Schriftdenkmal".

**Comment by fsteeg** [comment]
Deployed to test:

- https://test.lobid.org/gnd/1075383196#rels
- https://test.lobid.org/gnd/1081988592#rels

But discovered two issues while testing:

- 'Großelter': https://test.lobid.org/gnd/101417675#rels (new DNB-GND issue? 'Großelternteil'?)
- No `hasParentInlaw` in results or context: [https://lobid.org/gnd/search?q=hasParentInlaw%3A*](https://lobid.org/gnd/search?q=hasParentInlaw%3A*) https://lobid.org/gnd/context.jsonld (new lobid-gnd issue?)

**Comment by acka47** [comment]
+1

> Großelter': https://test.lobid.org/gnd/101417675#rels (new DNB-GND issue? 'Großelternteil'?)

I will create a new issue.

> No hasParentInlaw in results or context: https://lobid.org/gnd/search?q=hasParentInlaw%3A* https://lobid.org/gnd/context.jsonld (new lobid-gnd issue?)

Also, `hasPatron` is missing and probably others. The properties are actually used in the data yet, so it is not a big issue. I checked Kibana and only found one not-compacted key (http://rdaregistry.info/Elements/u/P60049) which is used in 51 resources (see https://lobid.org/gnd/search?q=_exists_%3A%22http%3A%2F%2Frdaregistry.info%2FElements%2Fu%2FP60049%22). I will create an issue for all of these context-related things.

**Comment by acka47** [comment]
I created http://jira.dnb.de/browse/GND-74 for replacing "hat Großelter" by "hat Großelternteil".
