### ISSUE TITLE
Use https URLs in reconciliation metadata

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#168]
@literarymachine reported issues using the lobid-gnd OpenRefine reconciliation service from an https OpenRefine instance. This seems to be caused by the http URLs in our service metadata at https://lobid.org/gnd/reconcile

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd/reconcile

**Comment by acka47** [comment]
+1
