### ISSUE TITLE
Get GND vocabs for labels

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#17]
For getting labels for URIs like http://d-nb.info/standards/vocab/gnd/geographic-area-code#XA-DE

**Comment by fsteeg** [comment]
Unlike the GND ontology at http://d-nb.info/standards/elementset/gnd, which is available as RDF, I have not found anything similar for the vocab. @acka47 Are you aware of any dump for the `http://d-nb.info/standards/vocab/gnd` namespace?

**Comment by acka47** [comment]
I think there are only two different controlled vocabs from the `http://d-nb.info/standards/vocab/gnd` namespace used in GND. Besides the already mentioned [GND Geographic Area Codes](http://d-nb.info/standards/vocab/gnd/geographic-area-code.html), there also are the [GND Subject Categories](http://d-nb.info/standards/vocab/gnd/gnd-sc.html). You can get both of them as RDF, e.g. `curl -L -H "Accept:application/rdf+xml" http://d-nb.info/standards/vocab/gnd/geographic-area-code`

**Comment by acka47** [comment]
Command for getting the Sachgruppen:

`$ curl -L -H "Accept:application/rdf+xml" http://d-nb.info/standards/vocab/gnd/gnd-sc`

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/gnd/118820591 (Ländercode, Geschlecht)

**Comment by acka47** [comment]
I just noticed that the GND-Sachgruppen aren't shown yet in the HTML. We should show them with the GND-SachgruppenJoseph Weizenbaum for example is in Sachgruppen "Personen zu Mathematik" and "Personen zu Informatik, Datenverarbeitung", from the JSON-LD:

```json
{
  "id":"http://d-nb.info/gnd/118820591",
  "gndSubjectCategory":[
    "http://d-nb.info/standards/vocab/gnd/gnd-sc#28p",
    "http://d-nb.info/standards/vocab/gnd/gnd-sc#30p"
  ]
}
```

Furthermore, as discussed on the phone, we should adjust the behaviour of the links:

- All `http://d-nb.info/gnd/{id}` should go the the respective lobid-gnd page of the resource.
- Clicking on country codes, gender and Sachgruppen should result in a query for all resources with that code.

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/gnd/118820591

(For consistency, all text links go to searches, and all icons to sources, but in lobid-gnd if we have it.)

**Comment by ChristophEwertowski** [comment]
If I click on "Personen zur Mathematik" I first see a page of works. I think it would be better to show persons first, if possible. 
Before clicking "Berlin" at "Geburtsort" I would expect to only get persons who were born there, not all resources with the according GND-URL.

**Comment by acka47** [comment]
> Before clicking "Berlin" at "Geburtsort" I would expect to only get persons who were born there, not all resources with the according GND-URL.

Yes, it would be nice to make the link context-sensitive, i.e. only query for occurences of the respective entry (here "Berlin") in the actual field I am clicking on.

**Comment by fsteeg** [comment]
Deployed field-specific search links: http://stage.lobid.org/gnd/118820591

**Comment by acka47** [comment]
This is much better. But for outgoing links like wikidata and viaf the behaviour is quite unexpected. We should add an exception for those (`wikipedia` and `sameAs`).

**Comment by ChristophEwertowski** [comment]
What Adrian said.

**Comment by fsteeg** [comment]
Deployed fix: http://stage.lobid.org/gnd/118820591

**Comment by acka47** [comment]
+1 (Reviewing this I had to write https://github.com/hbz/lobid-gnd/issues/44#issuecomment-378861077 as showing all these long URLs isn't the best approach.)
