### ISSUE TITLE
Add tests to catch not-compacted properties

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#171]
As said in https://github.com/hbz/lobid-gnd/issues/163#issuecomment-445232779 we need some mechanism to check whether all properties are compacted in the lobid-gnd JSON-LD or whether some keys exist that are a URI.

This might best be implemented using the [GET mapping mechanism](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html).

**Comment by acka47** [comment]
See https://github.com/hbz/lobid-gnd/issues/89#issuecomment-445760214 as current case where we have problems with not automatically detecting not-compacted keys. (Although I knew about this change and should have prepared the context, a test would of course be fine to catch it when we miss something.)

**Comment by acka47** [comment]
The tests should at best run before a new index is deployed to production.

**Comment by acka47** [comment]
As discussed today, this is a good issue for @dr0i to help out with lobid-gnd.

**Comment by dr0i** [comment]
quick note: `curl weywot5.hbz-nrw.de:9200/gnd/_mapping | jq -r 'paths | map(.|tostring)|join(".")' a.json |grep http.*properties. |grep -vE  '.properties(.id|.label)(.*)$' |grep -vE  '.properties$'`
where if have to get the proper index name of course.

**Comment by dr0i** [comment]
As mailing was not working on quaoar1: uninstalled `postfix` and installed `sendmail`.

**Comment by dr0i** [comment]
TODO: get/set index-name which shall be checked.

**Comment by dr0i** [comment]
Done setting index name.
Deployed. Closing
