### ISSUE TITLE
Support GET for reconciliation requests

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#175]
Internally OpenRefine uses POST with the query data in the request body.

The wiki however describes GET with a `queries` parameter:

https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API#multiple-query-mode

We should probably support both.

**Comment by fsteeg** [comment]
Required for testing with https://github.com/reconciliation-api/testbench, which is useful e.g. for https://github.com/hbz/lobid-gnd/issues/206.

**Comment by fsteeg** [comment]
Deployed to test, see: [https://test.lobid.org/gnd/reconcile?queries={"q0":{"query":"Twain"}}](https://test.lobid.org/gnd/reconcile?queries=%7B%22q0%22%3A%7B%22query%22%3A%22Twain%22%7D%7D)

To test in the reconciliation service test bench:

- Go to https://reconciliation-api.github.io/testbench
- Click 'Test bench' tab
- Endpoint: `https://test.lobid.org/gnd/reconcile`
- Name: e.g. `Twain`
- Click 'Reconcile'

**Comment by acka47** [comment]
I tested it in the reconciliation service test bench and it worked. +1
