### ISSUE TITLE
Use new Entityfacts dump 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#177]
There is a new EntityFacts dump available, see https://lists.dnb.de/pipermail/lds/2018-December/000130.html.

Am 19.12.18 um 11:38 schrieb Datendienste:> Sehr geehrte Damen und Herren,
> 
> wir haben einen aktualisierten Gesamtabzug der Daten des Services „Entity Facts“ bereitgestellt unter https://data.dnb.de/opendata/.
> Die Bereitstellung erfolgt dreimal im Jahr, jeweils im Anschluss an die Produktivnahme der Export-Releases[1].
> 
> Mehr Informationen zum Service Entity Facts unter http://www.dnb.de/entityfacts.
> 
> .........................
> 
> Dear Sir or Madam,
> 
> We made available a new dump file of the data from our service Entity Facts at https://data.dnb.de/opendata/.
> The dump file is updated three times a year, after each case of a new Export release[1] being deployed.
> 
> More information about the service Entity Facts at http://www.dnb.de/EN/entityfacts.
> 
> 
> Mit freundlichen Grüßen / Kind regards,
> Jana Hentschke
> 
> 
> [1] https://wiki.dnb.de/x/wgcbBQ

**Comment by dr0i** [comment]
New index is set up, took 24 min.
Aliases need to be set.

**Comment by fsteeg** [comment]
Note to self: conversion is running on weywot2 and should finish later today. Then: index into new index (in `data/index`, but first: move updates and set up deletions of deprecated items with `GND-deprecated_baseline_plus_2018-10-13_2018-12-20.txt`), add subsequent updates after 2018-12-20.

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd/search

**Comment by acka47** [comment]
Looks good. For example, #161 will be resolved when deploying this to production.

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production: http://lobid.org/gnd/search
