### ISSUE TITLE
Normalize diacritics

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#181]
Via Email by M.A.M. via T.S. on 2019-01-16:

> Derzeit muss man Sonderzeichen korrekt eingeben, um einen Namen zu finden. Also beispielsweise suchte ich gerade: 
Halevy, Ludovic
und fand nichts, erst nachdem ich
Halévy eingab, fand ich den gewünschten.

**Comment by acka47** [comment]
Resolved with #263.  Closing
