### ISSUE TITLE
Incorrect wikidata/wikipedia links for 4380740-9

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#182]
Reported on 2019-02-28 via email by T.U.:

> die Verknüpfung von gnd 4380740-9 zu wikidata müsste meiner meiner 
> Meinung nach Q179830 (Stadt in Lettland), statt zu Q5244309 Bahnhof 
> Jelgava.

I responded:

> Die Wikidata-Links kommen aus EntityFacts, wo 
> mittlerweile der korrekte Link ist, siehe 
> http://hub.culturegraph.org/entityfacts/4380740-9. Wir bekommen leider 
> nur alle zwei bis drei Monate einen aktuellen EntityFacts-Abzug, weshalb 
> das bei lobid-gnd erst später korrigiert wird.
> 
> Der Wikipedia-Link ist leider noch in EntityFacts und lobid-gnd 
> inkorrekt. Wir werden uns darum kümmern.

**Comment by acka47** [comment]
Fixed by now, see http://lobid.org/gnd/4380740-9. Closing.

**Comment by acka47** [comment]
Oups, the wikipedia link is still incorrect. Reopening.

**Comment by rettinghaus** [comment]
@acka47 Looks like this one could closed now.

**Comment by acka47** [comment]
> Looks like this one could closed now.

Thanks for the hint. Closing.
