### ISSUE TITLE
Declare inbox and hub in link header

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#184]
We should do this on the staging system for now to be able to test https://github.com/hbz/skohub-pubsub/issues/7. For now, we must use local URLs, `http://localhost:3000/inbox?target={target-URL}` for the inbox and `http://localhost:3000/hub` for the hub. [Example](https://lobid.org/gnd/135539897):

```
Link: <http://localhost:3000/inbox?target=http://d-nb.info/gnd/135539897>; rel="http://www.w3.org/ns/ldp#inbox"
Link: <http://localhost:3000/hub/>; rel="hub"
Link: <http://d-nb.info/gnd/135539897>; rel="self"
```

As one can see I am using the DNB URIs that identify the resource in the inbox link and the `self` link. I think this is the way to go but I am not 100% whether this is correct.

**Comment by literarymachine** [comment]
Links for the test setup:
```
Link: <https://test.skohub.io/inbox?target=https://test.lobid.org/gnd/118696432>; rel="http://www.w3.org/ns/ldp#inbox"
Link: <https://test.skohub.io/hub>; rel="hub"
Link: <https://test.lobid.org/gnd/118696432>; rel="self"
```

**Comment by fsteeg** [comment]
Deployed to test:

`curl -I http://test.lobid.org/gnd/100002617`
`curl -I http://test.lobid.org/gnd/100002617.json`
`curl -I http://test.lobid.org/gnd/100002617.html`
`curl -I http://test.lobid.org/gnd/100002617.rdf`

`HTTP/1.1 200 OK`
`Link: <https://test.skohub.io/inbox?target=http://test.lobid.org/gnd/100002617>; rel=http://www.w3.org/ns/ldp#inbox, <https://test.skohub.io/hub>; rel=hub, <http://test.lobid.org/gnd/100002617>; rel=self`

**Comment by acka47** [comment]
I Noticed that the quote are missing around the values of `rel=`. I think they are expected, see [RFC 5988](https://tools.ietf.org/html/rfc5988)

**Comment by fsteeg** [comment]
> I noticed that the quote are missing around the values of `rel=`. I think they are expected, see [RFC 5988](https://tools.ietf.org/html/rfc5988)

Hm, I explicitly test for quotation marks, see https://github.com/hbz/lobid-gnd/commit/1965988d4df81ac06f2f71ce3f8a569449105edc#diff-7b6d18ce6977e12af82ab242d90349f0R55

It seems there is [a newer RFC](https://tools.ietf.org/html/rfc8288), see "Link Serialisation in HTTP Headers":

> In other words, the following parameters are equivalent:
>     x=y
>     x="y"

So this might just be the way cURL (and others) display the value.

Assigning @literarymachine to verify in his client.

**Comment by fsteeg** [comment]
@acka47 I can't assign @literarymachine – should we add the skohub team to lobid-gnd? https://github.com/hbz/lobid-gnd/settings/collaboration

**Comment by acka47** [comment]
Done that & assigned @literarymachine.

**Comment by acka47** [comment]
Closing this as we are through with testing this, see https://github.com/hbz/lobid-resources/issues/986.
