### ISSUE TITLE
Merge EntityFacts sameAs data with GND sameAs data

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#187]
Currently, `sameAs` data from EntityFacts replaces the original GND data.

This might cause the missing ORCID data (not yet in our EntityFacts dump).

**Comment by fsteeg** [comment]
@acka47 Last week you showed me a sample with an ORCID ID, but wrong structure and missing fields (abbr etc.). I thought that was where no EntityFacts enrichment happened, but I can't find something like that now. Here is a non-EntityFacts sample which looks fine: http://lobid.org/gnd/1153970082

**Comment by acka47** [comment]
I used the example from https://twitter.com/junicatalo/status/1107928653357301761 wich ist http://lobid.org/gnd/1176129791. See http://lobid.org/gnd/search?q=sameAs.collection.id%3A%22http%3A%2F%2Forcid.org%22+AND+NOT+_exists_%3AsameAs.collection.name for more.

- Those entries are not part of our EntityFacts index (I just checked) although they by now have an EntityFacts entry (see e.g. http://hub.culturegraph.org/entityfacts/1176129791)
- they have an orcid link provided via the GND RDF.
