### ISSUE TITLE
Error on colons in reconciliation queries

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#188]
e.g. `Deutscher Bibliothekartag (28. Bibliothekartag 1932 : 1932 : Jena)`

Reported by @LibrErli via email.

**Comment by fsteeg** [comment]
Deployed to test, reconcile using `https://test.lobid.org/gnd/reconcile`

**Comment by LibrErli** [comment]
Thank you, Fabian. I've tested it with the set of all "Deutsche Bibliothekartage", and it worked fine!

**Comment by fsteeg** [comment]
@LibrErli Oh great, that was fast, so please ignore the mail I've just sent :-)

We will deploy to production after code review (probably tomorrow).
