### ISSUE TITLE
HTML is broken when geo coordinates are a polygon

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#192]
See e.g. http://lobid.org/gnd/4099668-2.html or any entry from this list of 79 places: http://lobid.org/gnd/search?q=hasGeometry.asWKT%3APolygon

From the JSON:

```json
{
   "hasGeometry":[
      {
         "type":"http://www.opengis.net/ont/sf#Polygon",
         "asWKT":[
            "Polygon (( +009.711666 +052.364444, +009.711666 +052.364444, +009.711388 +052.364444, +009.711388 +052.364444, +009.711666 +052.364444 ))"
         ]
      }
   ]
}
```

I suggest to not show the map whenever `hasGeometry.type` is  `http://www.opengis.net/ont/sf#Polygon` (which we also should add to the context to only just read `Polygon`.

**Comment by fsteeg** [comment]
Deployed to test (taking on of the polygon points, not ideal for larger units, but better than the current error):

http://test.lobid.org/gnd/search?q=hasGeometry.asWKT:Polygon

**Comment by acka47** [comment]
+1 (I also added `http://www.opengis.net/ont/sf#Polygon` to the context as said above.)
