### ISSUE TITLE
Support reconciliation against type "DifferentiatedPerson"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#193]
At KIM workshop 2019, P.M., a colleague from ETH Zürich library, asked to add this very useful feature to our OpenRefine reconciliation endpoint.When reconciling values in a column, it should be possible to chose the subset of type `DifferentiatedPerson` to reconcile against. This will improve matchings for person names a lot. (Their use case ist, they have a list from an archive with person names and unstructured further data (occipation, birth and death date).)

**Comment by fsteeg** [comment]
While it's not in the suggested types, it should work to specify it under `Reconcile against type` (below the suggested types).

**Comment by acka47** [comment]
Thanks, I will let her know. This probably is very relevant for other users, so we should think about adding this to the blog post at http://blog.lobid.org/2018/08/27/openrefine.html

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd/reconcile

See also https://github.com/lobid/lobid.github.com/pull/45

**Comment by acka47** [comment]
+1
