### ISSUE TITLE
Load icons via HTTPS

### ISSUE THREAD

**Issue by rettinghaus** [hbz/lobid-gnd#195]
For proper HTTPS load graphics/icons from other sites over HTTPS or cache them locally. 

(BTW the `favicon.ico` from www.deutsche-digitale-bibliothek.de is gone.)

**Comment by acka47** [comment]
As the icon URLs are coming from the EntityFacts data we use for lobid-gnd, I opened an issue in the (password-protected) GND Jira: https://jira.dnb.de/browse/GND-97. I will leave this issue open until the problem is fixed upstream.

**Comment by acka47** [comment]
And thanks for the report, @rettinghaus!

**Comment by dr0i** [comment]
This is fixed with hbz/lobid#421.
Closing.
