### ISSUE TITLE
combine equal information

### ISSUE THREAD

**Issue by rettinghaus** [hbz/lobid-gnd#199]
Momentarily `Beruf oder Beschäftigung` is shown at the top of the output, while `Beruf oder Beschäftigung (Literal)` is way down. As they represent equal information, they should be grouped together, maybe even shown all as `Beruf oder Beschäftigung` in one line.

**Comment by rettinghaus** [comment]
E.g. http://lobid.org/gnd/104278870

**Comment by acka47** [comment]
Thanks for the request. I also think it would be best to put the string in the same line as the GND occupations. With the underlying link missing it will be clear that one is dealing with a literal.

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/gnd/104278870

**Comment by acka47** [comment]
Looks good. I noticed one thing, though.

The field name is suffixed with "(Literal)" if a correspondent URI value does not exist, see e.g.  https://test.lobid.org/gnd/100124356 & https://test.lobid.org/gnd/100168337, https://test.lobid.org/gnd/10008110X, https://test.lobid.org/gnd/10009807X.

I think we should always use the same name (without "(Literal")) as the suffix is not there if both value types exist and as you can see by the non-existent link that you are dealing with a literal only.

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd/100168337

**Comment by rettinghaus** [comment]
Great! Thanks!

**Comment by acka47** [comment]
+1
