### ISSUE TITLE
Remove outdated sameAs entries

### ISSUE THREAD

**Issue by rettinghaus** [hbz/lobid-gnd#203]
Some GND RDF datasets (e.g. [105519682X](https://d-nb.info/gnd/105519682X/about/lds.rdf)) carry a depricated GND-IDN in the sameAs field, which result in multiple links to the same set in `Deutsche Nationalbibliothek (DNB)` (see https://lobid.org/gnd/105519682X).
These `sameAs ` entries should be filtered out. 

```xml
<gndo:oldAuthorityNumber rdf:datatype="http://www.w3.org/2001/XMLSchema#string">(DE-588)1073348296</gndo:oldAuthorityNumber>
<owl:sameAs rdf:resource="http://d-nb.info/gnd/1073348296"/>
<dnbt:deprecatedUri rdf:datatype="http://www.w3.org/2001/XMLSchema#string">http://d-nb.info/gnd/1073348296</dnbt:deprecatedUri>
```

Refers to #198

**Comment by acka47** [comment]
This looks like something to be fixed in the GND RDF provided by DNB. Opened an issue over there ([GND-98](https://jira.dnb.de/browse/GND-98)).

**Comment by acka47** [comment]
Nearly three yeas later, we received the response from DNB via the Jira issue [GND-98](https://jira.dnb.de/browse/GND-98):

> Wir würden das owl:sameAs der alten Nummer gerne drin behalten. Die Aussage ist richtig und für manche Anwendungsfälle gut zu gebrauchen. Wenn eine Anwendung diese URIs nicht anzeigen lassen will, dann sollte das meiner Meinung nach über die Anwendung gesteuert werden.

So, we will have to filter those out in the UI or during the data transformation. Removing the "upstream" label.

**Comment by fsteeg** [comment]
Deployed to test, e.g. https://test.lobid.org/gnd/105519682X

(Also fixes a related issue: for entries with `deprecatedUri`, but no explicit DNB `sameAs` in the data, we displayed *only* the deprecated URI. Fixed in e.g. https://test.lobid.org/gnd/1250844843.)

**Comment by rettinghaus** [comment]
Looks great, thanks!
