### ISSUE TITLE
Support OpenRefine Suggest API

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#206]
See https://github.com/OpenRefine/OpenRefine/wiki/Suggest-API

I noticed that we do not provide this while looking at the overview of OpenRefine API endpoints at the "Reconciliation service test bench" provided by @wetneb: https://reconciliation-api.github.io/testbench/

**Comment by fsteeg** [comment]
Deployed to test, see:

Suggestions:

https://test.lobid.org/gnd/reconcile/suggest/entity?prefix=hbz
https://test.lobid.org/gnd/reconcile/suggest/type?prefix=werk
https://test.lobid.org/gnd/reconcile/suggest/property?prefix=beruf

Flyouts:

https://test.lobid.org/gnd/reconcile/flyout/entity?id=2047974-8
https://test.lobid.org/gnd/reconcile/flyout/type?id=Work
https://test.lobid.org/gnd/reconcile/flyout/property?id=professionOrOccupation

Post about the improvements and updated general documentation:

https://github.com/lobid/lobid.github.com/pull/49

**Comment by acka47** [comment]
Everything looks good. I reviewed the JSON and tested it in OpenRefine. I am not quite sure whether it responds quick enough (the [API documentation](https://github.com/OpenRefine/OpenRefine/wiki/Suggest-API) mentions 200ms). When I do a lookup for the first time, it seems to take too long. it is very quick when repeated, though.
