### ISSUE TITLE
JSON: DNB ID in describedBy wrongly links to GND

### ISSUE THREAD

**Issue by zuphilip** [hbz/lobid-gnd#209]
Currently the DNB ID is saved in the describedBy/id field as an URI pointing to the GND instead of the DNB, e.g. https://lobid.org/gnd/4193754-5.json

```
"describedBy": {
  "id": "http://d-nb.info/gnd/041937546/about",
  "license": {
    "id": "http://creativecommons.org/publicdomain/zero/1.0/",
    "label": "http://creativecommons.org/publicdomain/zero/1.0/"
  },
  "dateModified": "2013-12-15T13:48:48.000"
},
"gndIdentifier": "4193754-5",
"id": "http://d-nb.info/gnd/4193754-5",
"preferredName": "Maschinelles Lernen"
...
```
which IMO instead should be `describedBy/id = http://d-nb.info/041937546/about` (or save only the identifier).

**Comment by acka47** [comment]
Hi @zuphilip, thanks for the report and sorry for the late response. I just now got aware of this issue. You are right that there is a problem. 

> which IMO instead should be describedBy/id = http://d-nb.info/041937546/about

I think the best solution would be describedBy.id: "http://d-nb.info/gnd/4193754-5/about" like it is done for persons, see e.g. http://lobid.org/gnd/1024861112.json. 

As we just take the RDF data from DNB, this has to be fixed upstream. Luckily, DNB is already aware of the bug and has fixed it for the next relesae, see the thread startin at https://lists.dnb.de/pipermail/lds/2019-June/000142.html.

**Comment by dr0i** [comment]
DNB has fixed this. Closing.
