### ISSUE TITLE
Obtain new EntityFacts dump

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#210]
This request by D.G. from Bonn came in via email today (snippet):

> Heute aber bin ich 
> etwas überrascht, weil ich auf der Suche nach Friedman, Batya 
> (GND-Nummer 1187201553 oder 152687629) keine Verknüpfungen zu VIAF, LOC 
> oder anderen Datenbanken vorhanden sind, obwohl Frau Friedman dort zu 
> finden ist:
> 
> https://viaf.org/viaf/77828351/
> 
> Ich hoffe, Sie können das wahrscheinlich technische Problem lösen und 
> die fehlende Verknüpfung ohne großen Aufwand einarbeiten.

It looks like the person did not have an EntityFacts entry by the time the last dump was created (2019-03-05) (see #183). However, by now such an entry exists, see https://hub.culturegraph.org/entityfacts/1187201553

**Comment by acka47** [comment]
I wrote a request to the lds list, see https://lists.dnb.de/pipermail/lds/2019-July/000147.html.

**Comment by acka47** [comment]
DNB [responded](https://lists.dnb.de/pipermail/lds/2019-July/000148.html) that there will be a nw EntityFacts dump next week. However, I figured the best solution would be if DNB send us the monthly updated enrichment file created from all the BEACON files, VIAF and Wikidata as described in https://wiki.dnb.de/display/LINKEDDATASERVICE/Anreicherungen. I sent an enquiry to datendienste whether this is feasible.

**Comment by acka47** [comment]
A new dump is now available:

[Am 29.07.19 um 10:30 schrieb Datendienste](https://lists.dnb.de/pipermail/lds/2019-July/000150.html):
> Sehr geehrte Damen und Herren,
> Liebe Kolleginnen, liebe Kollegen,
> nach einigen Schwierigkeiten steht Ihnen jetzt auch der aktualisierte 
> Gesamtabzug der Daten des Services „Entity Facts“[1] zur Verfügung[2].
> Ich bedanke mich bei Ihnen für Ihre Geduld und bei meinen Kollegen für 
> Ihre Hartnaeckigkeit.
> Mit freundlichen Grüßen
> i.A.
> Uta Ackermann
> [1]_https://www.dnb.de/entityfacts_
> [2]_https://data.dnb.de/opendata/_

**Comment by acka47** [comment]
@fsteeg, I keep this open until the data is updated in lobid-gnd. I think @dr0i usually set up the EntityFacts index. Can you take over this taks this time?

**Comment by fsteeg** [comment]
Assigning @dr0i for next week. If he doesn't have time, I'll do it later next week.

**Comment by dr0i** [comment]
Build new entityfacts-index, switched alias. I think the gnd-index need a complete rebuild, don't see how to do this in the crontab - there only updates are described.
Assigning @fsteeg, aslo: could you paste into the crontab how to trigger a fulldump index build ?

**Comment by fsteeg** [comment]
> Assigning @fsteeg, also: could you paste into the crontab how to trigger a fulldump index build ?

I think there are two things we should do here to make this fully automatable:

- [ ] Move GND indexing into a separate main ([currently done as part of the app startup process](https://github.com/hbz/lobid-gnd/blob/master/app/modules/IndexComponent.java))
- [ ] Move EntityFacts  indexing into lobid-gnd ([currently done in lobid-resources](https://github.com/hbz/lobid-resources/blob/master/src/main/java/org/lobid/resources/run/Entityfacts2Es.java))

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/gnd/1187201553 (http://test.lobid.org/gnd/search)

(But it seems the VIAF link already got there in some other way: http://lobid.org/gnd/1187201553)

**Comment by acka47** [comment]
> (But it seems the VIAF link already got there in some other way: http://lobid.org/gnd/1187201553)

The VIAF and ISNI links are meanwhile also in the GND RDF, see https://d-nb.info/gnd/1187201553/about/lds.ttl.

In https://hypothes.is/a/bmBf8sKBEemssUsuLRMriQ a missing depiction link for [Berlin](https://lobid.org/gnd/4005728-8) was reported. It will be there after deployment to production (see http://test.lobid.org/gnd/4005728-8.).

+1 for deploying

**Comment by fsteeg** [comment]
Deployed current data to production, closing. See http://lobid.org/gnd/search
