### ISSUE TITLE
One-step executable workflows for EntityFacts, GND baseline and updates

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-gnd#218]
Result from
https://github.com/hbz/lobid-gnd/pull/215#pullrequestreview-281909400:

Update cron.sh (and rename it to e.g  startEtl.sh) to allow parameters to start ETL of not only gnd-updates, but also baseline and entitifacts.

**Comment by fsteeg** [comment]
Implemented in [baseline.sh](https://github.com/hbz/lobid-gnd/blob/c4e0c817adfa230e6402e6334677d82a0a1eb078/baseline.sh) ([history](https://github.com/hbz/lobid-gnd/commits/master/baseline.sh)), see #255 & #299, closing.
