### ISSUE TITLE
Show link to DNB in "Siehe auch" for every entry

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#219]
Feedback from GND user T.C. via email on 2019-09-02:

> Beim Datensatz
> http://lobid.org/gnd/1193756588
> steht nicht von wann er stammt und es gibt leider nicht einmal ein
> Link zur DNB-HTML-Webseite, damit man die aktuelle und datenreichere
> Version sehen kann.

For approximately half of the entries, a sameAs link to GND already exists, shown under "Siehe auch": https://lobid.org/gnd/search?q=sameAs.collection.id%3A%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ36578%22. We should also show a link in the HTML for all entries that do not have it in the JSON-LD.

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd/1193757835

**Comment by acka47** [comment]
+1 (It would be even better to have it in the data but this will suffice for now.)
