### ISSUE TITLE
Put lobid-authorities into public beta

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#22]
At some point, we should switch lobid-authorities to public beta:

- Use the ~~beta~~.lobid.org ~~sub~~domain for http://test.lobid.org/authorities
- Add "authorities `beta`" to the main navigation at http://lobid.org

Perhaps we could add a `beta` label for the issues that need to be solved before we do so.

@acka47 What do you think?

**Comment by acka47** [comment]
I think we should run the "beta" version at https://lobid.org/authorities and the staging version at https://staging.lobid.org/authorities.

**Comment by acka47** [comment]
I created a "beta" label but actually only found one issue that really is necessary to be implemented before going beta.

**Comment by fsteeg** [comment]
Deployed: http://lobid.org/

**Comment by acka47** [comment]
+1 Closing
