### ISSUE TITLE
Fix reconciliation query properties search

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#224]
When sending additional properties during reconciliation ("Also use relevant details from other columns"), the plain property is used in the internal field query. This only makes sense for `*AsLiteral` fields. For others, we need to append `.id` or `.label`, e.g. `affiliation.id:"http://d-nb.info/gnd/2022139-3"`.

**Comment by acka47** [comment]
I suggest translating this to an `OR` query so that both IDs and literals work, e.g. `affiliation.id:"http://d-nb.info/gnd/2022139-3" OR affiliation.label:"http://d-nb.info/gnd/2022139-3"`

**Comment by fsteeg** [comment]
Deployed to test, see https://test.lobid.org/gnd/reconcile

> I suggest translating this into an OR query so that both IDs and literals work

I check the value and use `.id` if it starts with `http`, otherwise `.label`, see https://github.com/hbz/lobid-gnd/commit/a734854f84bb1eca95d1f17e3802556aef1d60be.
