### ISSUE TITLE
OpenRefine Reconciliation - Search for new match - No respond on special characters in searchstring

### ISSUE THREAD

**Issue by LibrErli** [hbz/lobid-gnd#226]
If you have already reconciled values in OpenRefine and if you click on "Search new match" and enter some string especialliy containing colons - the search result preview seems to be frozen. 
maybe this error is similar to this issue https://github.com/hbz/lobid-gnd/issues/188

Try to search for the following GND-Item: http://lobid.org/gnd/801510-7 with its preferred name.

![openrefine_lobid_search](https://user-images.githubusercontent.com/18214283/64797967-7bbd9e80-d582-11e9-875b-4aec5b922b8e.gif)

**Comment by fsteeg** [comment]
@LibrErli Thanks for the report.

Deployed to test, reconcile using `https://test.lobid.org/gnd/reconcile`

**Comment by acka47** [comment]
+1
