### ISSUE TITLE
Reconcile only against name fields

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#228]
Currently, when starting reconciliaton from a row in OpenRefine, a general `q` query is sent without indicating any specific fields to search. Assuming that reconciliation is per se run on the basis of a text name ("Reconciliation is a semi-automated process of matching text names to database IDs", [source](https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation)), we should limit the request to those fields containing names. These are:
```
preferredName
variantName
abbreviatedNameForTheConferenceOrEvent
abbreviatedNameForThePlaceOrGeographicName
abbreviatedNameForTheWork
abbreviatedNameForTheCorporateBody
temporaryName
```

Note: When #227 is done `temporaryName` will also cover all cases with the more specific properties. I will make an issue in DNB Jira to add a general `abbreviatedName` property to GNDO.

**Comment by acka47** [comment]
>  I will make an issue in DNB Jira to add a general abbreviatedName property to GNDO.

I opened an issue at https://jira.dnb.de/browse/GND-112 and will open an issue for using the property instead of the specific properties as soon as it is added.

**Comment by fsteeg** [comment]
Deployed to test, reconcile with https://test.lobid.org/gnd/reconcile

See https://refine.graphthinking.com/project?project=2291226341193

**Comment by acka47** [comment]
Just, tested it. This improves reconciliation and automatic matching significantly. :rocket: +1
