### ISSUE TITLE
Add page on sources, updates and differences to GND

### ISSUE THREAD

**Issue by annainfo** [hbz/lobid-gnd#231]
https://web.archive.org/web/20190916114811im_/https://lobid.org/gnd/1193757835

does not display what is found in
1) https://web.archive.org/web/20190916120358/https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid%3D1193757835
- a link to Marc21 (http://d-nb.info/gnd/1193757835/about/marcxml)
- Link zu diesem Datensatz | http://d-nb.info/gnd/1193757835
- Quelle | BBLD: https://bbld.de/0000000004345912

2) https://web.archive.org/web/20190916120358/http://d-nb.info/gnd/1193757835/about/marcxml / http://d-nb.info/gnd/1193757835/about/marcxml
!Note: The pasted source code is not displayed in github,

2.1) datafield tag 024 (URI, ISNI)

Source code:
 <datafield tag="024" ind1="7" ind2=" ">
      <subfield code="a">http://d-nb.info/gnd/1193757835</subfield>
      <subfield code="2">uri</subfield>
    </datafield>
    <datafield tag="024" ind1="7" ind2=" ">
      <subfield code="a">0000000004345912</subfield>
      <subfield code="2">isni</subfield>
    </datafield>

2.2) datafield tag 670 (in HTML : Quelle:)
Source code:
    <datafield tag="670" ind1=" " ind2=" ">
      <subfield code="a">BBLD</subfield>
      <subfield code="u">https://bbld.de/0000000004345912</subfield>
    </datafield>

**Comment by acka47** [comment]
We do neither process DNB MARC21 nor DNB HTML (and we do not say so anywhere), so this is no surprise. I described our sources and processing in #230.

We recently had a similar request per email (see https://github.com/hbz/lobid-gnd/issues/220) in reaction to which we updated the description at https://lobid.org/gnd. However, as misunderstandings continue to be, I will rename this issue to add a page with detailed information on the data sources, the update frequency and – most important – the difference to the Pica/MARC21 version of the GND.

**Comment by acka47** [comment]
As an easy first step for more clarity, we should adjust the labels for the "Datenquelle" links below each entry. Instead of just "GND" it should read: "GND RDF". 

As discussed offline, we could add a link to the turtle version as well. Then it would read, e.g. for https://lobid.org/gnd/118049240:

> Datenquelle: DNB RDF ([Turtle](https://d-nb.info/gnd/118049240/about/lds.ttl), [RDF/XML](https://d-nb.info/gnd/118049240/about/lds.rdf)) und [Entityfacts](http://hub.culturegraph.org/entityfacts/118049240)

**Comment by fsteeg** [comment]
Deployed updated info to test: https://test.lobid.org/gnd/118049240, http://localhost:9002/gnd/1193757835

**Comment by acka47** [comment]
Looks good. Could you make it "Datenquelle**n**" when both LDS and EntityFacts are listed?

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd/118049240, https://test.lobid.org/gnd/1193757835

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
> Quelle | BBLD: https://bbld.de/0000000004345912

FTR, I already opened an issue on 2919-09-03 in DNB Jira to add this field to the GND RDF so that we can also display it.
