### ISSUE TITLE
Inconsistent pluralisation "Datenquellen"

### ISSUE THREAD

**Issue by annainfo** [hbz/lobid-gnd#234]
https://test.lobid.org/gnd/118049240
(https://web.archive.org/save/https://test.lobid.org/gnd/118049240)

"Datenquellen: DNB Linked-Data-Service (RDF/XML, Turtle) und EntityFacts (JSON-LD) | CC0"

but

"Titelangabe", "Varianter Name"

**Comment by acka47** [comment]
For all properties and types we are using the labels from [GND Ontology](https://d-nb.info/standards/elementset/gnd). Addign exceptions to this behaviour would require a lot of work. As this is a minor problem which does not impact use of lobid-gnd and adding, we won't fix this. Closing.
