### ISSUE TITLE
Support type param in property suggest service

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#236]
The type param is ignored in property suggest queries:

https://lobid.org/gnd/reconcile/suggest/property?prefix=Ort&type=Person
https://lobid.org/gnd/reconcile/suggest/property?prefix=Ort&type=CorporateBody

**Comment by fsteeg** [comment]
Deployed to test:

https://test.lobid.org/gnd/reconcile/suggest/property?prefix=Ort&type=Person
https://test.lobid.org/gnd/reconcile/suggest/property?prefix=Ort&type=CorporateBody

**Comment by acka47** [comment]
+1
