### ISSUE TITLE
Set up GND reconciliation landing page

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#237]
I think we should set up a landing page for our OpenRefine reconciliation service, comparable to https://tools.wmflabs.org/openrefine-wikidata/, with some basic info and links to:

- GND general information
- OpenRefine general information
- Our existing reconciliation tutorial
- Our upcoming real-world data tutorial
- Our reconciliation API documentation
- The reconciliation community group

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/gnd/reconcile

(default still JSON: `curl http://test.lobid.org/gnd/reconcile`)

**Comment by acka47** [comment]
Looks good. Shouldn't we also add a link to https://reconciliation-api.github.io/specs/latest/?

**Comment by fsteeg** [comment]
> Shouldn't we also add a link to https://reconciliation-api.github.io/specs/latest/

I think it's best to just link to the community group main page, which contains a direct link to the 0.1 version of the spec (which is what OpenRefine and our service actually conform to). The latest version is a moving target, I don't think it's that relevant for our service.

**Comment by acka47** [comment]
+1
