### ISSUE TITLE
[recon-extend] non-GND values should have no type

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#241]
https://github.com/OpenRefine/OpenRefine/wiki/Data-Extension-API#data-extension-protocol:

> The type field should only be provided when the property returns reconciled items.
> [...]
> an object with "id" and "name" represents a reconciled value (from the same reconciliation service)

See http://lobid.org/gnd/reconcile?extend={%22ids%22:[%2210662041X%22,%221064905412%22],%22properties%22:[{%22id%22:%22variantName%22},{%22id%22:%22geographicAreaCode%22},{%22id%22:%22professionOrOccupation%22}]}

`geographicAreaCode` should have no type.

See also https://reconciliation-api.github.io/specs/#data-extension-responses

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/gnd/reconcile?extend={%22ids%22:[%2210662041X%22,%221064905412%22],%22properties%22:[{%22id%22:%22variantName%22},{%22id%22:%22geographicAreaCode%22},{%22id%22:%22professionOrOccupation%22}]}

**Comment by acka47** [comment]
+1
