### ISSUE TITLE
"Reconciliation" of GND identifiers

### ISSUE THREAD

**Issue by wetneb** [hbz/lobid-gnd#247]
Just making sure you had seen this, from OpenRefine's mailing list:
https://groups.google.com/d/msgid/openrefine/0b677083-2be3-437c-8f8c-f61b7234330b%40googlegroups.com

A reconciliation query containing a GND identifier as text (such as `132390299`) does not give any results, whereas a suggest query for the same text returns the expected result.

**Comment by acka47** [comment]
Thanks for the hint. No one from the lobid team was a subscriber until now. I will subscribe to the list today.

Regarding the conrete problem, we should probably add `gndIdentifier` to the list of fields a reconciliation query is matched against:

https://github.com/hbz/lobid-gnd/blob/cace3e55211aba9976fec081414a9738ddeff98b/app/controllers/Reconcile.java#L446-L453

**Comment by acka47** [comment]
We should probably also add `sameAs.collection.id` where the corresponding identifiers from other sources are located. People might even be more interested in using external identifiers for reconciliation than GND IDs.

**Comment by fsteeg** [comment]
Deployed to test:

http://test.lobid.org/gnd/reconcile/?queries={"q1":{"query":"118624822"}}
http://test.lobid.org/gnd/reconcile/?queries={"q1":{"query":"http://viaf.org/viaf/50566653"}}

**Comment by fsteeg** [comment]
There's an issue when the IDs contain a dash:

http://test.lobid.org/gnd/reconcile/?queries={"q1":{"query":"4463847-4"}}

**Comment by fsteeg** [comment]
Redeployed to test:

http://test.lobid.org/gnd/reconcile/?queries={"q1":{"query":"118624822"}}
http://test.lobid.org/gnd/reconcile/?queries={"q1":{"query":"http://viaf.org/viaf/50566653"}}
http://test.lobid.org/gnd/reconcile/?queries={"q1":{"query":"4463847-4"}}
http://test.lobid.org/gnd/reconcile/?queries={"q1":{"query":"https://d-nb.info/gnd/4463847-4"}}

**Comment by acka47** [comment]
Works mostly fine but it doesn't work with ORCIDs, e.g. `http://orcid.org/0000-0003-0232-7085`.

**Comment by acka47** [comment]
My bad, I took non-http ORCID URIs from the production system. On staging, there are https-URIs. So everything works fine. +1
