### ISSUE TITLE
"Gods" and "Spirits" are shown within first-level type facet

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#25]
...while they are actually subclasses of "Differentiated Person".

See http://test.lobid.org/authorities/search?q=*

**Comment by fsteeg** [comment]
The thing that makes this case special is that these are on a third level, and don't contain the second level type (DifferentiatedPerson) already, see https://wiki1.hbz-nrw.de/x/CIeW. So we can't simply add them to the config (unless we make them only Person, or only DifferentiatedPerson). The way to go would probably be to support multiple types in the config. Moving to backlog for now.

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/gnd/search

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1
