### ISSUE TITLE
Problems with Chinese language tag for variant names

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#250]
Reported by @j4lib via email (thanks!):

> ich war mit eurem großartigen Tool mal wieder in den Tiefen der GND
> unterwegs und bin zufällig auf ein kleines Problem bei den Labels
> gestoßen.
> Bei diesem Treffer https://lobid.org/gnd/1013975324 steht bei
> "Varianter Name" neben ein paar Schriftzeichen auch "DE-576" (SWB-
> Verbund???). Ich habe dann aus Spaß folgendes abgefragt:
> https://lobid.org/gnd/search?q=de-576&filter=%2B%28type%3APerson%29
> Wenn man sich die Treffer genauer ansieht, fällt auf, dass bei
> "Varianter Name" oft "DE-576" angezeigt wird, wenn Schriftzeichen
> vorhanden sind.
> 
> Bei der DNB sieht es wie folgt aus und man versteht schnell, woher die
> Anzeige kommt:
> 
> `<https://d-nb.info/gnd/1013975324> gndo:variantNameForThePerson "DE-
> 576"@zh-Hans;
>    gndo:variantNameEntityForThePerson _:node1dtqgudcqx1000606 .`

This is obviously an upstream problem in GND RDF as provided by DNB. I opened an issue at https://jira.dnb.de/browse/GND-125.

**Comment by acka47** [comment]
I think ISILs indicating the name of the source that provided a variant name are used as the name itself. There are 52 additional cases with DE-603 (HeBIS), see https://lobid.org/gnd/search?q=variantName%3A%22DE-603%22.

**Comment by acka47** [comment]
The data transformation will be corrected with release 2021.3 on 2021-09-28. From [Metadatendienste: Änderungen im Format RDF ab 28. September 2021(Export-Release 2021.03)](https://www.dnb.de/SharedDocs/Downloads/DE/Professionell/Metadatendienste/Rundschreiben/rundschreiben20210628AenderungFormatRDF202103.pdf?__blob=publicationFile&v=3):

> Korrektur: In einigen Fällen kam es bei der Bildung der Literale varianter Namensformen („gndo:variantNameForThePerson“) zur Ausgabe der ISIL der Institution, die das Feld in besonderer Art verwendet. Dieser Fehler wurde jetzt behoben.

**Comment by acka47** [comment]
This is now fixed at DNB (see http://d-nb.info/gnd/1013975324/about/lds) but not yet in lobid-gnd, see https://lobid.org/gnd/1013975324.json.

**Comment by fsteeg** [comment]
Fixed and deployed via #255, see https://github.com/hbz/lobid-gnd/issues/255#issuecomment-981501347.
