### ISSUE TITLE
Wrong image links in EntityFacts

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#251]
Am 04.02.20 um 16:42 schrieb L.W.: 
> In reusing your data in https://data.swissbib.ch, we noticed that there 
> are strange thumbnails for some persons :
> 
> https://lobid.org/gnd/1089164025
> 
> https://lobid.org/gnd/132814412
> 
> https://lobid.org/gnd/118558064
> 
> Any clue why it is like that ?

**Comment by acka47** [comment]
I opened https://jira.dnb.de/browse/GND-133 in the DNB Jira for this and described what is going wrong:

<blockquote>
Die entsprechenden EntityFacts-Einträge sind die Fehlerquelle: http://hub.culturegraph.org/entityfacts/1089164025
http://hub.culturegraph.org/entityfacts/132814412
http://hub.culturegraph.org/entityfacts/118558064
 
Das Problem ist offensichtlich folgendes. Die Wikidata Query, mit der die Bild-Links aus Wikidata geholt werden (siehe [hier](http://tinyurl.com/ycnclxdg)), gibt für die drei Einträge sowohl ein Bild (`P18`) also auch ein Wappen (`P94`) mit:

```csv
item,gndid,type,image,logo,crest
http://www.wikidata.org/entity/Q3052772,1089164025,http://www.wikidata.org/entity/Q5,http://commons.wikimedia.org/wiki/Special:FilePath/Emmanuel%20Macron%20in%20Tallinn%20Digital%20Summit.%20Welcome%20dinner%20hosted%20by%20HE%20Donald%20Tusk.%20Handshake%20%2836669381364%29%20%28cropped%202%29.jpg,,http://commons.wikimedia.org/wiki/Special:FilePath/Coat%20of%20arms%20of%20the%20French%20Republic.svg
http://www.wikidata.org/entity/Q3910,132814412,http://www.wikidata.org/entity/Q5,http://commons.wikimedia.org/wiki/Special:FilePath/Prince%20Albert%20II%202016.jpg,,http://commons.wikimedia.org/wiki/Special:FilePath/Royal%20Monogram%20of%20Prince%20Albert%20II%20of%20Monaco.svg
http://www.wikidata.org/entity/Q989,118558064,http://www.wikidata.org/entity/Q5,http://commons.wikimedia.org/wiki/Special:FilePath/Luxembourg-5151%20-%20Pope%20John%20Paul%20II%20%2812727135684%29.jpg,,http://commons.wikimedia.org/wiki/Special:FilePath/John%20paul%202%20coa.svg
```
Bei der Generierung der EntitfyFacts-Daten wird dann fälschlicherweise nur der Wappen-Link ergänzt. Die beste Lösung wäre, bei der Generierung der EF-Daten, Bild-Links (`P18`) – wenn vorhanden – Wappen-Links (`P94`) vorzuziehen.
</blockquote>

**Comment by acka47** [comment]
There was a comment by @thoffma in the DNB Jira on 2022-02-16:

> wir haben begonnen an dem Thema zu arbeiten und sind darauf gekommen, gleich noch das komplette Skript zur Anreicherung der Commonsbilder zu überarbeiten. Kurz: wir sind dran, ich kann aber noch nicht sagen wann wir fertig sind.

And another one today:

> das Skript, welches die Bildlinks holt und verarbeitet wurde aktualisiert. Die Bildlinks sollten jetzt passen. Mit dem nächsten Entity Facts dump (Mitte Juni) hättet ihr dann auch die neuen Links!

We will have to update lobid-gnd with the new EntityFacts dump as soon as it is available. Assigning me and @fsteeg to remember this.

**Comment by acka47** [comment]
Fixed upstream Closing.

**Comment by liowalter** [comment]
Very nice, thanks a lot !
