### ISSUE TITLE
Load new EntityFacts & GND dump 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#255]
[Am 03.04.20 um 10:18 schrieb Metadatendienste](https://lists.dnb.de/pipermail/lds/2020-April/000160.html):
> Sehr geehrte Damen und Herren,
> 
> nun stehen alle aktualisierten RDF-Dumps der Deutschen Nationalbibliothek (DNB), der Zeitschriftendatenbank (ZDB), der Gemeinsamen Normdatei (GND) und der Adressdatei (ISIL- und Sigelverzeichnis) in verschiedenen Serialisierungsformen (RDF/XML, Turtle, JSON-LD, HDT-Datei und als N-Triples) bereit [1]. Details der Formataenderung im Release 2020.01 entnehmen Sie bitte der Ankuendigung [2]. Bitte beachten Sie weiterhin die Details der Formataenderung im Release 2019.03 [3], insbesondere das Kapitel 3, welches auf die Umstellung des Protokolls von HTTP auf HTTPS in allen Komponenten des Linked-Data-Service hinweist.
> Informationen rund um den Linked Data Service der Deutschen Nationalbibliothek finden Sie unter [4].
> 
> Entity Facts:
> Der aktualisierte Gesamtabzug der Daten des Services „Entity Facts“ [5] wurde ebenfalls bereitgestellt [1].
> 
> Alle Daten werden kostenfrei zur Verfuegung gestellt und unter Creative-Commons-Zero-Bedingungen (CC0 1.0) [6] zur freien Nachnutzung angeboten.
> 
> In der Zeit vom Montag, 6. April bis einschliesslich Ostermontag, 13. April ist der Dienstbetrieb in unserem Haus geschlossen. Sie erreichen uns wieder am 14. April 2020 per E-Mail unter metadatendienste@dnb.de und unter der Telefonnummer 069 1525-1630.
> 
> [1] https://data.dnb.de/opendata/
> [2] https://www.dnb.de/SharedDocs/Downloads/DE/Professionell/Metadatendienste/Rundschreiben/rundschreiben20191111AenderungFormatRdf20201.pdf
> [3] https://www.dnb.de/SharedDocs/Downloads/DE/Professionell/Metadatendienste/Rundschreiben/rundschreiben20190703AenderungFormatRdf20193.pdf
> [4] https://www.dnb.de/lds
> [5] https://www.dnb.de/entityfacts
> [6] https://creativecommons.org/publicdomain/zero/1.0/deed.de

**Comment by acka47** [comment]
There is a new EntityFacts dump as well as a GND RDF dump (with the undifferentiated persons removed). From the [mailing list](https://lists.dnb.de/pipermail/lds/2020-July/000161.html):

> nun stehen alle aktualisierten RDF-Dumps der Deutschen Nationalbibliothek (DNB) und der Gemeinsamen Normdatei (GND) [1] in verschiedenen Serialisierungsformen (RDF/XML, Turtle, JSON-LD, HDT-Datei und als N-Triples) bereit [2].
>
> Die Datei fuer die Namensdatensaetze (Tn-Saetze) der GND wird nicht mehr bereitgestellt. Naehere Informationen zur Abschaffung der Tn-Normdaten erhalten Sie im ILTIS WIKI [3]. 
> 
> Um die Herkunft der einzelnen Metadatenangaben in den RDF-Daten transparent zu gestalten, gibt es ergaenzend Metadatenprovenienz-Dumps fuer die DNB-Titeldaten, erkennbar an der Dateibenennung „dnb-all_ldsprov ...“. Darin enthalten sind Entstehungsangaben fuer alle Aussagen mit den Properties dcterms:subject und dcterms:language. Die Dokumentation der Modellierung ist unter [4] verfuegbar.
> 
> Informationen rund um den Linked-Data-Service der Deutschen Nationalbibliothek finden Sie unter [5].
> 
> 
> Entity Facts: 
> Der aktualisierte Gesamtabzug der Daten des Services „Entity Facts“ [6] wurde ebenfalls bereitgestellt [2].
> 
> Alle Daten werden kostenfrei zur Verfuegung gestellt und unter Creative-Commons-Zero-Bedingungen (CC0 1.0) [7] zur freien Nachnutzung angeboten.
> 
> Bitte beachten Sie die Struktur der Dateibenennung. Diese besteht aus dem OAI-Datensetbezeichner mit Bindestrich statt Doppelpunkt bei Untersets [8], Profil (z. B. lds, ldsprov, entityfacts), Datum des Datenabzugs (8-stellig) und zum MIME-Type gehoerende Dateiendung (z. B. ttl).
> Beispiel: authorities-person_lds_20200622.rdf.gz
> Die jeweils aktuellsten Dateien sind unter einem stabilen Link (Dateibenennung ohne Datum) abrufbar.
> 
> Fuer Rueckfragen erreichen Sie uns per E-Mail unter metadatendienste at dnb.de und unter der Telefonnummer 069 1525-1630.
> 
> [1] https://www.dnb.de/gnd 
> [2] https://data.dnb.de/opendata/
> [3] https://wiki.dnb.de/x/aJDOC
> [4] https://wiki.dnb.de/x/46G5C
> [5] https://www.dnb.de/lds
> [6 https://www.dnb.de/entityfacts
> [7] https://creativecommons.org/publicdomain/zero/1.0/deed.de
> [8] https://www.dnb.de/oai, Abschnitt „Über OAI verfuegbare Kataloge (sets) der Deutschen Nationalbibliothek“

**Comment by acka47** [comment]
Will be fixed with https://github.com/hbz/lobid-gnd/pull/259. The numbers loo good.

Old (current production): 15.661.604 resources
New (staging): 8.639.879 resources

Old minus undifferentiated persons in there (7.031.501) = 8630103

Thus, there are nearly 10k more resources on staging which will be the missing updates one of which was reported in #258.

**Comment by dr0i** [comment]
Closing this issue as it is resolved by now.

**Comment by acka47** [comment]
New dumps have been available since the end of November. We now got a mention on Twitter that `sameAs` links are wrong in on eGND entry: https://twitter.com/slackingcrab/status/1349456241752477699

Using the new EntityFacts dump will probably fixx this.

**Comment by fsteeg** [comment]
Set up and switched production alias to new index, see e.g. https://lobid.org/gnd/4011039-4

**Comment by acka47** [comment]
+1 Closing.

For future reference: The new index contains ~2k less resources than the old one. New: 8,803,333 Old: 8,805,326
This is probably due to the deleted entries that are removed when loading a new full dump (see e.g. #117).

**Comment by acka47** [comment]
See https://lists.dnb.de/pipermail/lds/2021-July/000166.html:



> Sehr geehrte Damen und Herren,
>
> wir möchten Sie darauf hinweisen, dass ab der KW 27, 2021 die aktualisierten RDF-Dumps der Gemeinsamen Normdatei (GND), der Titeldaten der Deutschen Nationalbibliothek (DNB), in verschiedenen Serialisierungsformen (RDF/XML, Turtle, JSON-LD, HDT-Datei und als N-Triples) bereit stehen [1].
> Um die Herkunft der einzelnen Metadatenangaben in den RDF-Daten transparent zu gestalten, gibt es ergänzend Metadatenprovenienz-Dumps für die DNB-Titeldaten, erkennbar an der Dateibenennung „dnb-all_ldsprov ...“. Darin enthalten sind Entstehungsangaben für alle Aussagen mit den Properties dcterms:subject und dcterms:language. Die Dokumentation der Modellierung ist unter [2] verfügbar.
>
> Entity Facts:
> Der Gesamtabzug der Daten des Services „Entity Facts“ [3] wird monatlich aktualisiert [1].
>
> Alle Daten werden kostenfrei zur Verfügung gestellt und unter Creative-Commons-Zero-Bedingungen (CC0 1.0) [4] zur freien Nachnutzung angeboten.
>
> Informationen rund um den Linked-Data-Service der Deutschen Nationalbibliothek finden Sie unter [5].
>
> Für weitere Fragen erreichen Sie uns per E-Mail unter metadatendienste at dnb.de<mailto:metadatendienste at dnb.de> und unter der Telefonnummer 069 1525-1630.
>
>
> [1] https://data.dnb.de/opendata/
> [2] https://wiki.dnb.de/x/46G5C
> [3] https://www.dnb.de/entityfacts
> [4] https://creativecommons.org/publicdomain/zero/1.0/deed.de
> [5] https://www.dnb.de/lds

**Comment by acka47** [comment]
Reopening (see comment above).

**Comment by acka47** [comment]
@fsteeg has deployed the changes to https://test.lobid.org/gnd.

+1 looks good and fixes #250.

Similarly to the last update, there are 6832 resources less in the new index compared to the old one:

- old: 9,080,558
- new: 9,073,726

Again, apparently lots of subject headings sensu strictu have been deleted.

Old:

![image](https://user-images.githubusercontent.com/160292/143851023-671f9093-898a-4b8b-b9bb-dcdf4d7f0c29.png)

New:

![image](https://user-images.githubusercontent.com/160292/143851098-017b51fd-d40e-4328-b994-bee04b7af98a.png)

**Comment by fsteeg** [comment]
Deployed to production, see: http://lobid.org/gnd/search

**Comment by acka47** [comment]
We have loaded a new full dump, see https://github.com/hbz/lobid-gnd/issues/326#issuecomment-1308946028 ff. Here are the numbers:

* old: 9,334,203 total entries
* New: 9,337,592

Interestingly, we have – contrary to the previous two updates – 3.4k more resources in the new index.

By type:

Old: 
![image](https://user-images.githubusercontent.com/160292/201087178-88ad54cc-b10a-4b91-92cc-1a2968278ba4.png)

New:
![image](https://user-images.githubusercontent.com/160292/201087237-535dcbb4-0d49-4438-9f23-88f6b9041d94.png)
