### ISSUE TITLE
Implement ascii variant search

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-gnd#263]
B. Ahrens asked for a new feature at around 2020-08-17:

>  Ist es möglich, in diakritikafreien "ASCII"-Varianten von Namen zu 
suchen? Beispielsweise möchten wir bei einer Suche nach "Wroclaw" 
 auch eine Entität namens "Wrocław" finden.

So the task is to be able to search for ASCII-variants, e.g. "Wroclaw" should hit "Wrocław".

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/gnd/search?q=variantName.ascii:Wroclaw

**Comment by acka47** [comment]
Looks good. These queries yield the same results:

[variantName.ascii:Wroclaw](http://test.lobid.org/gnd/search?q=variantName.ascii:Wroclaw) & [variantName:(Wrocław OR Wroclaw)](http://test.lobid.org/gnd/search?q=variantName%3A%28Wroc%C5%82aw+OR+Wroclaw%29)

while those give fewer results:

[variantName:Wroclaw](http://test.lobid.org/gnd/search?q=variantName%3AWroclaw) & [variantName:Wrocław](http://test.lobid.org/gnd/search?q=variantName%3AWroc%C5%82aw)

**Comment by fsteeg** [comment]
I was thinking: we should probably also support this for preferredName, right? To e.g. find http://test.lobid.org/gnd/16330586-9 with a query like `preferredName.ascii:Chor` ('Chór' only in preferredName, not variantName).

**Comment by acka47** [comment]
>  we should probably also support this for preferredName, right?

I guess it's not much effort, so +1. And we will have to document it somewhere, probably right in the first paragraph "Suche" at http://lobid.org/gnd/api

**Comment by fsteeg** [comment]
Deployed to test:

http://test.lobid.org/gnd/search?q=preferredName.ascii:Chor+OR+variantName.ascii:Chor
http://test.lobid.org/gnd/api

**Comment by acka47** [comment]
+1
