### ISSUE TITLE
Undifferentiated persons are back

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#267]
Undifferentiated persons have resurrected from their graves, see https://lobid.org/gnd/search?filter=%2B%28type%3AUndifferentiatedPerson%29. We had removed them in #255, see https://github.com/hbz/lobid-gnd/issues/255#issuecomment-666384497. What happened?

**Comment by fsteeg** [comment]
There was a config error in our production setup. On Sep. 1, it was switched to the older gnd-test index. I've switched it back to the production index and indexed the updates since Sep. 1 into the production index. See http://lobid.org/gnd/search.

**Comment by acka47** [comment]
Good to know you've killed the zombies. Closing.
