### ISSUE TITLE
Pretty print reconciliation responses

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#272]
To improve readability without a browser plugin, pretty print reconciliation API responses like:

[https://lobid.org/gnd/reconcile/?queries={"q1":{"query":"Twain, Mark"}}](https://lobid.org/gnd/reconcile/?queries={%22q1%22:{%22query%22:%22Twain,%20Mark%22}})

(Like we already e.g. for https://lobid.org/gnd/search?q=*&format=json)

**Comment by fsteeg** [comment]
Deployed to test. See samples linked from http://test.lobid.org/gnd/api#openrefine (without formatter/view-source/in `curl`), e.g.

[https://test.lobid.org/gnd/reconcile/?queries={"q1":{"query":"Twain, Mark"}}](https://test.lobid.org/gnd/reconcile/?queries={%22q1%22:{%22query%22:%22Twain,%20Mark%22}})

**Comment by acka47** [comment]
+1
