### ISSUE TITLE
Filtering shouldn't alter ranking

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#28]
For example:

1. [http://test.lobid.org/gnd/search?q=*](http://test.lobid.org/gnd/search?q=*) -> The first 10 hits are all persons starting with "G"
2. Filter by Person -> Not only are the other entities filtered out but the ranking is changed. Now persons with "Person" in their name are shown on top of the list.

Probably the best way to handle this would be to use elasticsearch filters instead of queries for facetting, see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html (as we do in OER World Map).

BTW, we do it like this in all our services...

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/gnd/search, filter `CorporateBody`

**Comment by fsteeg** [comment]
(Difference in initial search in comparison to original sample link due to query changes for https://github.com/hbz/lobid-gnd/issues/32).

**Comment by acka47** [comment]
That was quick. +1

**Comment by ChristophEwertowski** [comment]
+1 There are two organisations which are typed as `Person` and therefore wrongly assigned. I forwarded it to the Verbundgruppe.
