### ISSUE TITLE
Marker on map missing when zooming into html page

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-gnd#282]
See e.g. https://lobid.org/gnd/4064682-8..
Originates from https://github.com/hbz/lobid/issues/436.

**Comment by dr0i** [comment]
It's only missing when zooming the html page. Which I did by coincidence.
Nevertheless.

**Comment by fsteeg** [comment]
Can't reproduce in Firefox or Chromium.

**Comment by dr0i** [comment]
It's probably cached. After clearing cache in "developer concole", look at "network" in developer console and search for "marker" you will find `404`. Also, try the http version of the gnd.

**Comment by fsteeg** [comment]
Alright, I can reproduce if I zoom and then reload.

**Comment by dr0i** [comment]
Thx for discovering that I comitted a html page instead of the png. Fixed it and force-pushed.

**Comment by dr0i** [comment]
Ups - wrong place to note that. Copying my comment to the PR.

**Comment by dr0i** [comment]
Hm, I fail to deploy this. Going to test (weywot2), I kill the process, but monit seems to initialize it forever without success. Restarted monit, all apps come up but not gnd. As I merged the branch, there was a conflict. I stashed it and popped it, but maybe there was something wrong? Logs don't come up with something useful.
Also production - I fortunately didn't try to restart the service there.
Can you help out @fsteeg ?

**Comment by fsteeg** [comment]
Deployed to production, see https://lobid.org/gnd/4064682-8

On production, the usual `sh restart.sh lobid-gnd` worked fine.

On test, no secret in application.conf was set, resulting in an exception during startup. I don't know why that was not logged to `logs/application.log`. I saw it when doing a manual `sbt "start 7100"`. The monit output to `/var/log/monit.log` looks different than I seem to recall, and it kept trying to restart until now. It used to give up after a few attempts, and unmonitor. Could this be related to a system update and newer monit version?

**Comment by dr0i** [comment]
Works - thx for deployment. Closing.
