### ISSUE TITLE
Improve handling of failed updates

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#284]
We need to improve handling of failing updates.

On 2021-02-03 we got a "GND updates fails" email. After a quick check in the the `data/backup` folder all updates seemed to be there. We have a mechanism that should include missed updates on the next day (GND-lastSuccessfulUpdate.txt, see https://github.com/hbz/lobid-gnd/blob/master/cron.sh). But thankfully @dr0i pushed me to investigate if this actually worked, and it didn't: the backup file is empty, so we either missed updates for that day or there were no updates(?).

What we should do:

- [x] Fix the mechanism based on GND-lastSuccessfulUpdate.txt
~~- [ ] Don't copy empty update files to `data/backup`~~
- [x] Handle the case where the OAI-PMH service works fine, but there are no updates
- [x] Re-run updates for the missing day

**Comment by dr0i** [comment]
Also experienced in https://github.com/hbz/lobid-gnd/issues/313.

**Comment by fsteeg** [comment]
Seems I lost track of this issue, and it might be a simple fix.

> - [x] Fix the mechanism based on GND-lastSuccessfulUpdate.txt

Pushed https://github.com/hbz/lobid-gnd/commit/5d41b7b7a81eeca43172f70a7d778f9aed1545f6 to only write the last successful update date after actual success.

> - [ ] Don't copy empty update files to data/backup

I think this one is actually nice the way it is, since we have a full record of what happened. When we look at the backups, we see the update happened, but the file was empty. If it's not there, we don't know if something was there and was later deleted etc. What do you think, @dr0i?

> - [x] Re-run updates for the missing day

I think with the fix above, this is already handled: on the next day, we'll use the same older start day again, as on the day before, since we did not update the date when we got no data.

> - [x] Handle the case where the OAI-PMH service works fine, but there are no updates

I think with the fix above, this should be fine too: if the response is not completely empty, the date will be updated, and on the next day we'll continue, as if there had been some updates.
