### ISSUE TITLE
Fallback server uses gnd-test

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-gnd#290]
The fallback server for lobid-gnd is the same `stage.lobid.org/gnd` uses, i.e. it uses the `gnd-test` index - which is fairly outdated (from Augut 2020, lacking 10% of the data of the productive server).

Working on https://github.com/hbz/lobid/issues/467 I set `stage.lobid.org/gnd` to use the productive index, as a temporary solution. One might not need a third instance (for testing at `stage`) for one could use that instance to test by reconfigure the index to `gnd-test` and switch this back after tests are done. We apparently don't do so much testing and we don't have so much fallback incidents so that this may be ok - but don't forget to reconfigure it back.
_Or_ we might wand to walk the save path and deploy a third instance , as done in lobid-alma.
Decide.

**Comment by fsteeg** [comment]
> I set stage.lobid.org/gnd to use the productive index, as a temporary solution [...] We apparently don't do so much testing and we don't have so much fallback incidents so that this may be ok

+1
