### ISSUE TITLE
Images won't load from Wikimedia Commons proxy

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#291]
The proxy implemented in #262 does not work anymore as expected. Images won't load in the browser.

- There is no error notification in the browser console.
- Resolving a proxy URL – e.g. https://lobid.org/imagesproxy?url=https://commons.wikimedia.org/wiki/Special:FilePath/Quarter%20Siliqua%20of%20Witigis.jpg?width=270 – gives a notification, strangely as an image; "Die Grafik ... kann nicht angezeigt werden, weil sie Fehler enthält."
- Loading the image directly works, though, see https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Quarter_Siliqua_of_Witigis.jpg/270px-Quarter_Siliqua_of_Witigis.jpg.

This was also reported by a lobid-gnd user via email.

**Comment by dr0i** [comment]
From apache logs:

> failed to open stream: HTTP request failed! HTTP/1.0 429 Too many requests. Please comply with the User-Agent policy: https://meta.wikimedia.org/wiki/User-Agent_policy  in /usr/local/lobid/src/lobid.org/gatsby/lobid/public/imagesproxy.php

**Comment by dr0i** [comment]
Followed the instructions at wikimedia's site and included an header like:

> header("User-Agent: imagesproxy/0.1 (https://lobid.org/gnd $emailaddress)";

Seems to work :)

**Comment by acka47** [comment]
Great. I just searched for some information about guidelines forproxies that load Commons images but did not find something. However, I am adding some general information I found.

Generally, Wikimedia Commons doesn't recommend "hotlinking" via `img` tags, see https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia/technical:

> Hotlinking is *allowed* from Wikimedia servers, but *not generally recommended*: this is because anyone could change, vandalise, rename or delete a hotlinked image. On your own server, you will have control over what is served.
>
> If you do hotlink, then it is still necessary to follow the licensing conditions (see [Commons:Reusing content outside Wikimedia](https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia)) as you would for copies on your own server, including (if the license requires it) providing attribution as specified by the content creator. Ignoring the licenses could be a copyright infringement, regardless of whether you hotlink or use a copy of the file from your own server.

As we are following the licensing conditions, our hotlinking practice is fine, though. Hopefully, the added `User-Agent` header will prevent us from similar issues in the future.

**Comment by dr0i** [comment]
Don't know why it seemed to worked re: https://github.com/hbz/lobid-gnd/issues/291#issuecomment-870350085 because there only the _response_ header was set, not the _request_ header.
Did no set the "request header" using curl php.

**Comment by acka47** [comment]
Fixed on production. +1 Closing.
