### ISSUE TITLE
Rename to lobid-gnd

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#30]
We decided to rename the service to lobid-gnd.

- [x] Rename git repo
- [x] Rename Play project
- [ ] ~~Change URIs in transformation~~
- [x] Change HTTP routes
- [x] Change in UI
- [x] Update proxy settings

**Comment by fsteeg** [comment]
@acka47: I forgot about one practical issue when using `gnd`: unlike with the pluralizations for resources and organisations, we'd get the same URLs as the current 1.x service: `http://lobid.org/gnd`. So we can't run them in parallel. How should we deal with that?

(Yet another inconsistency in the naming, it still feels kind of wrong to me.)

**Comment by acka47** [comment]
The current 1.0 service is `/subject` respectively `/person` so no problem here at all.

**Comment by fsteeg** [comment]
> The current 1.0 service is /subject respectively /person so no problem here at all.

Damn! I'm already making stuff up just to avoid this :D

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/gnd

**Comment by acka47** [comment]
+1
