### ISSUE TITLE
URIs instead of labels shown in UI for GND-internal links

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#302]
See e.g. https://lobid.org/gnd/118540238:

![image](https://user-images.githubusercontent.com/160292/152756191-0ecb5a45-4f6a-4e81-90a4-7ed5fd37a26a.png)

I already noticed it on 2022-01-28 but when I looked a gain a few days later everything was fine.

**Comment by fsteeg** [comment]
Deployed to production via new baseline index: https://lobid.org/gnd/118540238

**Comment by acka47** [comment]
+1 Closing.
