### ISSUE TITLE
Using range query parameter via OpenRefine Reconciliation

### ISSUE THREAD

**Issue by b2m** [hbz/lobid-gnd#304]
The general API of lobid-gnd supports several Elasticsearch Query Parameters like wildcards via `*` and ranges like `[1920 TO 1950]`.

See the Blogpost [lobid-gnd: Formulierung komplexer Suchanfragen](https://blog.lobid.org/2018/07/06/lobid-gnd-queries.html) for details.

Some of these features also seem to work when using lobid-gnd via the OpenRefine Reconciliation endpoint, like wildcards or fuzzy search. But trying out date ranges produce unexpected results in OpenRefine.

### Example via web search

Here is an contrived example:

I want to reproduce the following search via OpenRefine:
 - http://lobid.org/gnd/search?q=Papst+Benedikt+dateOfBirth%3A%5B1920+TO+1950%5D
![lobid-gnd-test0](https://user-images.githubusercontent.com/135298/154530551-ab9c2ecf-4c84-410b-ac79-b724d396edc1.png)

The results from the web search are awesome.

### Example via OpenRefine Reconciliation

To reproduce this in OpenRefine I used the following data:
![lobid-gnd-test1](https://user-images.githubusercontent.com/135298/154530836-4296a323-9ef1-4b54-8c84-1ea39e54d3cd.png)

The Range for the birthday was used as additional property in the reconciliation request:
![lobid-gnd-test2](https://user-images.githubusercontent.com/135298/154530938-8cb359dd-a1d1-432a-a71e-7bb49361da1e.png)

But the results quite differ from the ones I tried to reproduce:
![lobid-gnd-test3](https://user-images.githubusercontent.com/135298/154531003-870094f8-14b8-4ffc-b920-966b981c1ff4.png)

Using full date ranges produce even more unexpected results:
![lobid-gnd-test4](https://user-images.githubusercontent.com/135298/154533183-883ca9a7-7b40-4bd0-b530-e0114f46c5e0.png)

## Conclusion

I conclude that I am either using the range query parameter via the reconciliation API wrong or it is not supported (yet).
Either way I would be happy for some clarification about which Elastic Search query parameters are supported and whether it is planned to support range queries via the OpenRefine reconciliation API.

**Comment by fsteeg** [comment]
Thanks for getting in touch! Many special characters are removed [here](https://github.com/hbz/lobid-gnd/blob/e101bceb0fcd8668ee9ee5a1b29cd7004e905bad/app/controllers/Reconcile.java#L536). We are doing that because these caused issues when they are part of the data (see #188 / #190). But maybe we could check for the range pattern specifically and support that.

**Comment by b2m** [comment]
> Many special characters are removed [here](https://github.com/hbz/lobid-gnd/blob/e101bceb0fcd8668ee9ee5a1b29cd7004e905bad/app/controllers/Reconcile.java#L536).

Thanks for providing the reference to the source code.
In essence this means that the following query parameters are also not usable:
 - exclusive ranges: `{2010 TO 2021}`
 - unbounded ranges: `>1, >=2, <3, <=4`
 - boosting: `Müller^2 Michael`
 - boolean operators: `+König -Graf`
 - grouping: `(Müller OR Meier) AND Michael`

**Comment by fsteeg** [comment]
Since ranges with TO and groups with AND/OR are quite specific, I think it makes sense to support these, and that should not result in issues with unexpected data as in #188. If a value contains such a range or group, no special characters are replaced in that value.

Deployed to `http://test.lobid.org/gnd/reconcile`, see e.g.:

[{"query":"Benedikt Papst","properties":[{"pid":"dateOfBirth","v":"[1920-01-01 TO 1950-01-01]"}]}](http://test.lobid.org/gnd/reconcile/?queries={%22q1%22:{%22query%22:%22Benedikt%20Papst%22,%22properties%22:[{%22pid%22:%22dateOfBirth%22,%22v%22:%22[1920-01-01%20TO%201950-01-01]%22}]}})

@b2m Would this work for you?

**Comment by b2m** [comment]
Thx, this looks promissing!

For me today this would be enough, I mean I could just send `(needle+ OR needle)` and have the support of the query string "mini language". But me in 5 years (months? 🤔) will forget about this and again would wonder why `needle+` ist not working.

So it would suggest to expand the trigger for "not removing special characters" to the other supported patterns like `(\+|\-)\w`, `(<|>)=?\d`, `\w^\d`, and ` (OR|AND) `.

This would make a clear distinction between:
1. User is sending "garbage", therefore special characters are removed.
2. User is sending structured content, let's assume he knows what he is doing.

ElasticSearch also has a [validation endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-validate.html) to check queries before executing them. Not sure about the impact on performance but maybe this is an alternative approach to consider.

**Comment by fsteeg** [comment]
> ElasticSearch also has a [validation endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-validate.html) to check queries before executing them. Not sure about the impact on performance but maybe this is an alternative approach to consider.

That's a good point, thanks! I did a quick and dirty test and this might work. I'll need a bit time for proper implementation though, and I'm currently not sure when we'll have time for that. Depending on what you prefer @b2m we can either deploy this as it currently is and open a new issue, or leave this open.

**Comment by b2m** [comment]
So a new issue it is =)

I'll close this one as the main part will be solved by #306 and #309 looks like a promising replacement or addition.
