### ISSUE TITLE
Use ElasticSearch validation endpoint to check queries before executing them

### ISSUE THREAD

**Issue by b2m** [hbz/lobid-gnd#309]
Extracted issue from #304: use ElasticSearch validation endpoint instead of or additional to custom data cleaning methods.

> ElasticSearch also has a [validation endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-validate.html) to check queries before executing them. Not sure about the impact on performance but maybe this is an alternative approach to consider.

_Originally posted by @b2m in https://github.com/hbz/lobid-gnd/issues/304#issuecomment-1055792505_

> That's a good point, thanks! I did a quick and dirty test and this might work. I'll need a bit time for proper implementation though, and I'm currently not sure when we'll have time for that. 

_Originally posted by @fsteeg in https://github.com/hbz/lobid-gnd/issues/304#issuecomment-1081817133_

Also see #188, #190, #304 and #306.

**Comment by b2m** [comment]
From a users perspective this is a very clean solution!

One possible feature would be to log and analyze failed queries to be able to discover and react on misusage, failed expectations or wrong usage on client side implementations. But I do not know whether you have the infrastructure for that.

**Comment by acka47** [comment]
+1

> One possible feature would be to log and analyze failed queries to be able to discover and react on misusage, failed expectations or wrong usage on client side implementations. But I do not know whether you have the infrastructure for that.

I think this should be no problem.Is this something, @dr0i would set up. However, if we can easily set it up, we should write out failed queries in an extra file. Or we could schedule a regular appointment to go through the whole logs and look at the failed queries...

**Comment by fsteeg** [comment]
Thanks for the feedback @b2m, I've added logging in [b3b04c0](https://github.com/hbz/lobid-gnd/commit/b3b04c0e59ec3029c0462985237567c65e7bd8af) to allow us to track invalid queries in the future. Will assign @dr0i for code review in #315.
