### ISSUE TITLE
Create & publish JSON-LD context that includes keys for classes

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#31]
Moving from old lobid-gnd repo, issue by @acka47.

We will use short keys instead of the URIs for classes/types in GND API 2.0. Thus, we will need these keys be defined in the `@context`. At best, we will generate this (half-)automatically from the GND ontology.

We already did some half-automatic generation of the GND context, see https://github.com/lobid/lodmill/issues/251 & https://gist.github.com/niklasl/2770154#gistcomment-946311.

I once again used Niklas' python tool and created the JSON-LD context. Afterwards a bit of manual post-processing was necessary as well as addition of `owl:sameAs` and `foaf:page` and the deletion of deprecated properties and classes. The result can be found at .https://gist.github.com/acka47/98035a3f215c783bdc00.

Leaving this open (and renaming the ticket) until the context is published.

**Comment by acka47** [comment]
The context exists and is up to date, see https://github.com/hbz/lobid-gnd/blob/master/conf/context.jsonld. We still need to serve it from a lobid.org-URL (http://lobid.org/gnd/context.jsonld) instead of using the raw github URL.

**Comment by fsteeg** [comment]
The context URL is inserted at transformation time, future updates will contain the the lobid URL.
