### ISSUE TITLE
Missing updates from 2022-05-17

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#313]
Reported by @peterstadler yesterday via email:

> sehr kurzem bemerke ich in unserem WeGA-Datenbestand GND IDs, die über
> die DNB abrufbar sind, nicht aber über lobid. Beispiele:
> * https://d-nb.info/gnd/1257644416
> * https://d-nb.info/gnd/1257667327
> * https://d-nb.info/gnd/1257642308

All three resources were created on 2022-05-16, so there must have been a problem with the updates for this day. We even got an email by the monitoring process on 2022-05-17 at 05:01:

> Tried to get the update several times, but the data remains to be empty.This may or may not be a problem on the side of the data provider.

For some reason, we did not investigate this.

**Comment by peterstadler** [comment]
Thanks for taking care!

**Comment by fsteeg** [comment]
> All three resources were created on 2022-05-16, so there must have been a problem with the updates for this day.

Indexed the missing updates, now available:

https://lobid.org/gnd/1257644416
https://lobid.org/gnd/1257667327
https://lobid.org/gnd/1257642308

> We even got an email by the monitoring process [...] For some reason, we did not investigate this.

I think we were under the impression that the intended mechanism to get the missing updates as part of the next day's update was working, and so could basically ignore a single empty update, as long as it does not fail repeatedly. I basically forgot about https://github.com/hbz/lobid-gnd/issues/284, which might actually be a simple fix.

**Comment by acka47** [comment]
Thanks for the quick fix. Closing
