### ISSUE TITLE
Use newest version of GNDO for labels in UI

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#324]
As reported on 2022-09-27 via email by @philipprumpf we still show the incorrect label for `gndo:SubjectHeadingSensoStricto` in the lobid-gnd UI although it was corrected to "Subject heading sensu stricto" on GNDO some time ago, see https://d-nb.info/standards/elementset/gnd#SubjectHeadingSensoStricto.

Looking at https://github.com/hbz/lobid-gnd/blob/master/conf/gnd.rdf we still use the GNDO version from 2019, a new version was published in June 2022. We probably just have to use the new RDF/XML file. 

(I am not sure whether we interpret the file as XML instead of RDF – like we do with the country code vocabulary, see #256 . If yes, swapping the files might bring some problems with it.)

**Comment by fsteeg** [comment]
Deployed to test, see e.g. http://test.lobid.org/gnd/7657492-1

**Comment by acka47** [comment]
+1 please deploy to production
