### ISSUE TITLE
Add new properties to context

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#326]
We got a monitoring alert: Alert GND: found not compacted fields:

```
gnd_20220630.mappings.authority.properties.describedBy.properties.https://d-nb.properties.info/standards/elementset/gnd#descriptionLevel.properties.id.type
gnd_20220630.mappings.authority.properties.describedBy.properties.https://d-nb.properties.info/standards/elementset/gnd#descriptionLevel.properties.label.type
gnd_20220630.mappings.authority.properties.describedBy.properties.https://d-nb.properties.info/standards/elementset/gnd#descriptionLevel.properties.label.fields.keyword.type
gnd_20220630.mappings.authority.properties.https://d-nb.properties.info/standards/elementset/gnd#alternativeMediumOfPerformance.type
gnd_20220630.mappings.authority.properties.https://d-nb.properties.info/standards/elementset/gnd#alternativeMediumOfPerformance.fields.keyword.type
gnd_20220630.mappings.authority.properties.https://d-nb.properties.info/standards/elementset/gnd#titleWithOtherTitleInformation.type
gnd_20220630.mappings.authority.properties.https://d-nb.properties.info/standards/elementset/gnd#titleWithOtherTitleInformation.fields.keyword.type
gnd_20220630.mappings.authority.properties.https://d-nb.properties.info/standards/elementset/gnd#totalNumberOfEnsembles.type
gnd_20220630.mappings.authority.properties.https://d-nb.properties.info/standards/elementset/gnd#totalNumberOfEnsembles.fields.keyword.type
gnd_20220630.mappings.authority.properties.https://d-nb.properties.info/standards/elementset/gnd#totalNumberOfPerformers.type
gnd_20220630.mappings.authority.properties.https://d-nb.properties.info/standards/elementset/gnd#totalNumberOfPerformers.fields.keyword.type
gnd_20220630.mappings.authority.properties.mediumOfPerformance.properties.http://www.properties.w3.properties.org/1999/02/22-rdf-syntax-ns#value.properties.id.type
gnd_20220630.mappings.authority.properties.mediumOfPerformance.properties.http://www.properties.w3.properties.org/1999/02/22-rdf-syntax-ns#value.properties.label.type
gnd_20220630.mappings.authority.properties.mediumOfPerformance.properties.http://www.properties.w3.properties.org/1999/02/22-rdf-syntax-ns#value.properties.label.fields.keyword.type
gnd_20220630.mappings.authority.properties.mediumOfPerformance.properties.https://d-nb.properties.info/standards/elementset/gnd#numberOfPerformersOfTheSameMedium.type
gnd_20220630.mappings.authority.properties.mediumOfPerformance.properties.https://d-nb.properties.info/standards/elementset/gnd#numberOfPerformersOfTheSameMedium.fields.keyword.type
```

This seems to break updating of records (at least) with these new properties, e.g. http://lobid.org/gnd/300126603 has no `totalNumberOfPerformers` or uncompacted `https://d-nb.properties.info/standards/elementset/gnd#totalNumberOfPerformers`, while https://d-nb.info/gnd/300126603/about/lds.rdf does (though it's weird they still have the same `modified` time, maybe the date is not updated if the original record was not changed, but only the property added to the transformation).

To avoid uncompacted fields, we should add the new properties to our context file.

**Comment by fsteeg** [comment]
Deployed added properties to test (quaoar2): https://test.lobid.org/gnd/context.jsonld

Automated updates should actually run on quaoar2, so if this works we should get no alert tomorrow.

**Comment by acka47** [comment]
The alerts came in again so this did not resolve the problem. Maybe #327 does not add all needed properties to the context. There are more properties that have been added to GND in June. From https://d-nb.info/standards/elementset/gnd_20220627:

```
Changes from 2022-02-08 to 2022-06-27

Add new object properties

    #equivalence
    #exactEquivalence
    #inexactEquivalence
    #compoundEquivalence
    #cumulativeCompoundEquivalence
    #broaderMapping
    #narrowerMapping
    #relatedMapping

Add new datatype properties

    #mediumOfPerformanceAsLiteral
    #numberOfEnsemblesOfTheSameType
    #numberOfPerformersOfTheSameMedium
    #alternativeMediumOfPerformance
    #totalNumberOfPerformers
    #totalNumberOfEnsembles
```

**Comment by dr0i** [comment]
Added these properties and deployed to test, see https://test.lobid.org/gnd/context.jsonld.
@fsteeg how are the tests to be run? `@quaoar2:~/git/lobid-gnd$ "sbt test"` results in 
> error] Test controllers.HomeControllerTest failed: java.io.FileNotFoundException: /GND.jsonl (Permission denied),

**Comment by acka47** [comment]
I wrote an email to the lds list asking for the publication date of the GND linked data export: https://lists.dnb.de/pipermail/lds/2022-October/000181.html

**Comment by acka47** [comment]
> I wrote an email to the lds list asking for the publication date of the GND linked data export: https://lists.dnb.de/pipermail/lds/2022-October/000181.html

And I got an explanation from @nils-stefan-weiher (Thanks!):
> die Antwort findet sich in der Ankündigung vom Juni:
> 
> https://www.dnb.de/SharedDocs/Downloads/DE/Professionell/Metadatendienste/Rundschreiben/rundschreiben20220627AenderungenRDF.pdf?__blob=publicationFile&v=3
> 
> Hier steht unter 2.1 Gesamtabzüge:
> 
> In Anlehnung an die Exportreleases werden in den Monaten März, Juni/Juli 
> und Oktober/November aktualisierte Gesamtabzüge der Gemeinsamen 
> Normdatei (GND2) und der Titeldaten der DNB in den Serialisierungsformen 
> RDF/XML, Turtle, JSON-LD und als HDT-Datei sowie als N-Triples zum 
> Download bereitgestellt.
> 
> Sowie ich das verstehe ist das Release 3.2022 schon produktiv für die 
> Konversion nach RDF auf den DNB Servern aber die Gesamtabzüge kommen im 
> laufe von Oktober Novemeber.

**Comment by acka47** [comment]
Die DNB "konkretisiert":

> Bedauerlicherweise können wir keinen genauen Termin für die Bereitstellung der Datendumps nennen, November ist aber sehr wahrscheinlich.

**Comment by acka47** [comment]
New dumps are now there, see https://data.dnb.de/opendata/. @j4lib made me aware that the file names have changed once again, though. (Was this in the Twitter chat, Julia? I can not find it again and have since deleted my Twitter account...)

**Comment by j4lib** [comment]
No, it was in SWIB's mattermost :)

**Comment by fsteeg** [comment]
Started the conversion (thanks @j4lib for the heads up on the file names), but it aborted due to XML issues in `authorities-gnd-geografikum_lds.rdf.gz` and `authorities-gnd-sachbegriff_lds.rdf.gz`:

```bash
$ zcat authorities-gnd-geografikum_lds.rdf.gz | xmllint --noout -
-:5: parser error : Attribute xmlns:void redefined
xmlns:void="http://rdfs.org/ns/void#" 
                                     ^
-:6: parser error : Attribute xmlns:cc redefined
xmlns:cc="http://creativecommons.org/ns#"	xmlns:schema="http://schema.org/"
                                         ^
$ zcat authorities-gnd-sachbegriff_lds.rdf.gz | xmllint --noout -
-:5: parser error : Attribute xmlns:void redefined
xmlns:void="http://rdfs.org/ns/void#" 
                                     ^
-:6: parser error : Attribute xmlns:cc redefined
xmlns:cc="http://creativecommons.org/ns#"	xmlns:schema="http://schema.org/"
                                         ^
```
- [ ] I will attempt to fix the issues locally and re-run the conversion for these files.
- [ ] We should consider adding a validation step using xmllint as above to our baseline.sh script to catch this kind of issue early.
- [ ] And we should provide feedback to the DNB so that it can be fixed in the LDS.

**Comment by fsteeg** [comment]
Deployed new baseline plus updates since 2022-10-13: https://lobid.org/gnd/search

Manual `bash checkCompactedProperties.sh` says `no uncompacted fields found`.

**Comment by fsteeg** [comment]
Production deployment seems to work fine, we're no longer getting the alert:

https://lobid.org/gnd/search

I've switched the test deployment to the old index for comparison in functional review:

https://test.lobid.org/gnd/search

**Comment by acka47** [comment]
+1
