### ISSUE TITLE
Problems with special characters in search term

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#33]
E.g. http://lobid.org/gnd/search?q=k%C3%B6ln

**Comment by fsteeg** [comment]
What's the problem?

**Comment by acka47** [comment]
There is only one result that actually has "Köln" in the name in the list and thaat is beacause it also has the string "Koeln". Generally, entries with Umlauts can't be found, another example: http://lobid.org/gnd/search?q=heinrich+b%C3%B6ll

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/gnd/search?q=köln

**Comment by acka47** [comment]
+1
