### ISSUE TITLE
Depiction is not taken from EntityFacts

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#332]
Reported by E.S. via email on 2022-12-05 See https://lobid.org/gnd/120965100 where no image is shown and also the [JSON](https://lobid.org/gnd/120965100.json) contains no `depiction` information. In [EntityFacts](http://hub.culturegraph.org/entityfacts/120965100) it is available, though:

```json
{
   "depiction":{
      "@id":"https://commons.wikimedia.org/wiki/Special:FilePath/Eva%20strautmann.JPG",
      "publisher":"Wikimedia Commons",
      "copyrighted":"true",
      "creator":[
         "Uwe Buchhop"
      ],
      "creditText":[
         "Uwe Buchhop via Eva Strautmann"
      ],
      "license":[
         {
            "@id":"https://creativecommons.org/licenses/by/3.0/de/deed.en",
            "abbr":"CC BY 3.0 de",
            "name":"Creative Commons Attribution 3.0 de",
            "attributionRequired":"true",
            "restrictions":""
         }
      ],
      "url":"https://commons.wikimedia.org/wiki/File:Eva%20strautmann.JPG?uselang=en",
      "thumbnail":{
         "@id":"https://commons.wikimedia.org/wiki/Special:FilePath/Eva%20strautmann.JPG?width=270"
      }
   }
}
```

I am not sure what the underlying problem is. Did the [addition of attribution information for images iN EntityFacts](https://github.com/hbz/lobid-gnd/issues/285#issuecomment-1150741989) maybe break something?

**Comment by fsteeg** [comment]
Enrichment from EntityFacts was broken due to faulty index config, I just noticed that while looking into the uncompacted fields issue. I thought that would be only for updates, but this here seems to indicate it's a general issue. Will look into that, might require full baseline conversion and reindex.

**Comment by fsteeg** [comment]
Deployed to production: https://lobid.org/gnd/120965100

(It wasn't just a config issue, the new entityfacts index seems to be broken: https://github.com/hbz/lobid-gnd/issues/334)
