### ISSUE TITLE
Missing MARC field 680 in RDF

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#333]
Reported via email by @stefandesu for Cocoda. I opened a corresponding Jira issue at DNB: https://jira.dnb.de/browse/GND-226

Am 07.12.22 um 11:56 schrieb Peters, Stefan:

> ... Dabei ist mir aufgefallen, dass die Daten, die auf der Seite der DNB unter "Erläuterungen" stehen (also insb. Verwendungshinweise) nicht in lobid eingespielt sind.
> 
> Beispiel: 4053474-1 Schule
> lobid: https://lobid.org/gnd/4053474-1
> DNB: https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid%3D4053474-1
> 
> Diese Daten wären jedoch für die Anzeige in Cocoda recht wichtig. Ich vermute, das Problem liegt daran, dass diese Daten nicht im RDF-Datensatz der DNB vorhanden sind, kann das sein? In MARC-XML sind sie vorhanden in Feld 680. Meinst du, es wäre möglich, diese Daten auch über lobid zu bekommen?

**Comment by stefandesu** [comment]
Is there any update on this? I don't have access to the DNB Jira, so I can't check myself.

**Comment by acka47** [comment]
DNB responded quickly and positively:

> die Anforderungen für die Ausgabe in RDF sind erstellt (Ticket: ILT-8227 ist mit diesem Ticket verknüpft, hast Du Zugriff drauf?).
Wenn alles gut geht, werden die Anforderungen im Import/Export-Release 2023.03 umgesetzt (Priorisierungstermin findet Anfang Mai statt).
Go-live für die Export-Formate ist der 26.09.2023.

**Comment by acka47** [comment]
Update from DNB:

> Die Änderung wurde produktiv genommen. Siehe https://d-nb.info/gnd/4427720-9/about/lds
Beim nächsten Dump (Ende Oktober/Anfang November) ist die Änderung dann auch mit drin.

**Comment by acka47** [comment]
For implementing this, a new property was added to GND ontology: `gndo:usingInstructions` (see also the version notes of the [current GNDO version](https://d-nb.info/standards/elementset/gnd_20230626)). I added it with https://github.com/hbz/lobid-gnd/commit/b8ee7976ac7838e987b31f5687878a7b22936726 and will open a PR.

**Comment by acka47** [comment]
With updates coming in that include the property https://d-nb.properties.info/standards/elementset/gnd#usingInstructions, we already get alert mails " Alert GND: found not compacted field(s)!":

On 13.10.23 01:04, sol wrote:
> gnd_20221212.mappings.authority.properties.https://d-nb.properties.info/standards/elementset/gnd#usingInstructions.properties.@language.type
> gnd_20221212.mappings.authority.properties.https://d-nb.properties.info/standards/elementset/gnd#usingInstructions.properties.@language.fields.keyword.type
> gnd_20221212.mappings.authority.properties.https://d-nb.properties.info/standards/elementset/gnd#usingInstructions.properties.@value.type
> gnd_20221212.mappings.authority.properties.https://d-nb.properties.info/standards/elementset/gnd#usingInstructions.properties.@value.fields.keyword.type

 I am hopeful, this will be solved by just updating the context as in #356.

**Comment by stefandesu** [comment]
I see that `gndo:usingInstructions` is now part of the Lobid context. However, it doesn't seem like the values have been updated yet. Are there any entries with new updates that I can use to test this? When will old entries (see my [original example](https://lobid.org/gnd/4053474-1.json)) get the updated values?

Thanks!

**Comment by acka47** [comment]
Hi @stefandesu ,

thanks for asking. Unfortunately, my assumption above was wrong:

> I am hopeful, this will be solved by just updating the context as in https://github.com/hbz/lobid-gnd/pull/356.

1. I forgot to set the language in the context which should be fixed with #360 
2. The changes have not been deployed to production anyway but are only on https://test.lobid.org/gnd

We will let you know tomorrow when some entries are on test that actually look like what you can expect in the future.

**Comment by acka47** [comment]
> We will let you know tomorrow when some entries are on test that actually look like what you can expect in the future.

Unfortunately, no resource with 680 was added/modified, so there is no example yet, see https://test.lobid.org/gnd/search?q=_exists_%3AusingInstructions++AND+describedBy.dateModified%3A2023-11-02.

However, it will just be an array of strings, e.g. in https://test.lobid.org/gnd/1269971174.json it will look like this:

```json
{
   "usingInstructions":[
      "Weitere Titel ggf. auch unter dem Pseudonym bzw. dem wirklichen Namen"
   ]
}
```

**Comment by acka47** [comment]
@stefandesu `usingInstructions` can now be found on production with the correct structure, see https://lobid.org/gnd/search?q=_exists_%3AusingInstructions&format=json

**Comment by stefandesu** [comment]
@acka47 Thanks a lot!

**Comment by acka47** [comment]
Done, see above and https://github.com/hbz/lobid-gnd/issues/366#issuecomment-1827875482 . Closing.
