### ISSUE TITLE
XML character reference issues in updates

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#336]
We're getting errors for OAI-PMH updates for two days, `2022-10-16` and `2022-11-29`.

The problem seems to be caused by Unicode characters in [1267961120](https://d-nb.info/gnd/1267961120) and [124632086X](https://d-nb.info/gnd/124632086X), which seem to be converted into invalid XML character references by the OAI-PMH [library](https://github.com/DSpace/oclc-harvester2) we're using, e.g. `xmllint` says `invalid xmlChar value 55349` for `catalytic water treatment and fuel synthesis: improving the activity of &#55349;`. (For the first example, it's occuring after `<gndo:variantNameForThePerson xml:lang="zh-Hans">邓淑`.)

Both the [LDS-RDF](https://d-nb.info/gnd/124632086X/about/lds.rdf) and content served by the OAI-PMH interface ([GetRecord](https://services.dnb.de/oai/repository?verb=GetRecord&identifier=oai:dnb.de/authorities/124632086X&metadataPrefix=RDFxml), [ListRecords](https://services.dnb.de/oai/repository?verb=ListRecords&from=2022-10-16T03:37:08Z&until=2022-10-16T03:37:08Z&set=authorities&metadataPrefix=RDFxml)) don't use these invalid character references, and validate, so I'm suspecting it happens when the harvester writes the server response [to XML](https://github.com/DSpace/oclc-harvester2/blob/oclc-harvester2-1.0.0/src/main/java/org/oclc/oai/harvester2/verb/HarvesterVerb.java#L225). The string we get for that example is `improving the activity of &#55349;&#56339;&#55349;&#56354;&#55349;&#56334;&#55349;&#57296; by cobalt`, which should be `improving the activity of 𝐓𝐢𝐎𝟐 by cobalt` when rendered correctly. Since we have 8 character references, but only 4 visible characters, it seems this is some combining character sequence. The [marcxml](http://d-nb.info/gnd/124632086X/about/marcxml) contains only 4 character references.

We currently skipped updates of the two dates above in our data. To fix this, we could:

- [ ] ~~Import fine-grained updates for that day, avoiding the single faulty record, to limit the immediate issue~~
- [ ] ~~Manually workaround / change the XML for these two days (comparing with the marcxml?)~~
- [ ] ~~Fix this Unicode character issue in the OAI-PMH library (combined character references?)~~
- [ ] ~~Report this to DNB/LDS, since while not faulty per se, there's something different about these 2 records~~

**Comment by fsteeg** [comment]
> I'm suspecting it happens when the harvester writes the server response [to XML](https://github.com/DSpace/oclc-harvester2/blob/oclc-harvester2-1.0.0/src/main/java/org/oclc/oai/harvester2/verb/HarvesterVerb.java#L225).

Turns out this is not correct, [the harvester works fine](https://blog.codinghorror.com/the-first-rule-of-programming-its-always-your-fault/), the actual problem was the Xerces XML parser pulled in as a transitive dependency, causing effectively the same issue as in https://github.com/metafacture/metafacture-core/issues/334. Fixed with https://github.com/hbz/lobid-gnd/commit/aaa86a6b6e9ca4c930839700b9f3d45b163bf165 by updating the harvester library and removing our own Xalan dependency.

Re-ran updates for the two missing days on test and production, seemed to work, got no errors, we have data for [2022-10-16](https://lobid.org/gnd/search?q=describedBy.dateModified%3A2022-10-16) and [2022-11-29](https://lobid.org/gnd/search?q=describedBy.dateModified%3A2022-11-29), but the two problematic records are [not found](https://lobid.org/gnd/124632086X) (for [124632086X](https://d-nb.info/gnd/124632086X)) / found with a [different ID](https://lobid.org/gnd/1132284465) (for [1267961120](https://d-nb.info/gnd/1267961120)).

**Comment by fsteeg** [comment]
> the two problematic records are [not found](https://lobid.org/gnd/124632086X) (for [124632086X](https://d-nb.info/gnd/124632086X)) / found with a [different ID](https://lobid.org/gnd/1132284465) (for [1267961120](https://d-nb.info/gnd/1267961120))

It seems the same problem comes up again during conversion, found this hidden between the other output: `[warn] application - XPath evaluation failed for Element: org.xml.sax.SAXParseException; lineNumber: 52; columnNumber: 170; Character reference "&#`. (Testing with `sbt "runMain apps.ConvertUpdates 2022-10-16 2022-10-16"`, `124632086X` is in GND-updates.rdf, but not in GND-updates.jsonl.)

This seems to be related to #321, so adding the one from there, the missing entries are:

- [ ] https://d-nb.info/gnd/1262530970/about/lds.rdf &rarr; https://lobid.org/gnd/1262530970
- [ ] https://d-nb.info/gnd/1267961120/about/lds.rdf &rarr; https://lobid.org/gnd/1267961120
- [ ] https://d-nb.info/gnd/124632086X/about/lds.rdf &rarr; https://lobid.org/gnd/124632086X

Sub-issues and related:

- [ ] Handle SAXParseException above properly, with stack trace
- [ ] Revisit `String not in Unicode Normal Form C` logger warnings for all strings (update Jena? Force logger to file to avoid excessive output? Fix underlying Unicode issue? Besides obfuscating the log output, could this be related to the actual problem here?)
- [ ] Fix the parsing issue, is this another transitive dependency bringing in a wrong parser?
- [ ] Show proper 404 page (like https://lobid.org/resources/123 &rarr; https://lobid.org/gnd/123)

**Comment by fsteeg** [comment]
The XPathExpressionException is now rethrown and logged with stack trace (https://github.com/hbz/lobid-gnd/commit/e7edbb4dc28b8a08272b329d1aa6c9b791dd45e8), and with an update to metafacture-core 5.4.0 (https://github.com/hbz/lobid-gnd/commit/310df9b30b94eb92aae68432ff11049f20ec2f48), the XML parsing now works (5.4.0 uses the same oclc-harvester2 version that we switched to in https://github.com/hbz/lobid-gnd/commit/aaa86a6b6e9ca4c930839700b9f3d45b163bf165, so that makes sense).

In the next step however, when indexing, we get a completely new issue after the metafacture update: `stream has already been operated upon or closed` [...] `at controllers.Reconcile.<clinit>(Reconcile.java:64)` (where it loads the config file). The fact that Reconcile is initialized at all seems to be due to the fact we inject an `Index`, which we also use for the indexing. Tests are failing with the same issue.

If we switch back to the state before the metafacture-core update for indexing only (after converting with the new version), we do get the missing records, tested for 2022-10-16: https://test.lobid.org/gnd/124632086X (note the bold Unicode characters in all their glory), so we're getting there.

**Comment by fsteeg** [comment]
After excluding jackson-databind from the metafacture-elasticsearch dependency (https://github.com/hbz/lobid-gnd/commit/591665e131d0532e0c00f6b8e93b1e981811945e), the tests pass and both conversion and indexing works:

- https://test.lobid.org/gnd/1262530970
- https://test.lobid.org/gnd/124632086X
- https://test.lobid.org/gnd/1267961120 (& deleted https://test.lobid.org/gnd/1132284465)

**Comment by fsteeg** [comment]
And added 404 pages like in the other lobid services: https://test.lobid.org/gnd/123.

Assigning @acka47 for functional review (see links above and in the previous comment).

**Comment by acka47** [comment]
+1
