### ISSUE TITLE
Slash breaks reconciliation API

### ISSUE THREAD

**Issue by b2m** [hbz/lobid-gnd#343]
Having a slash `/` in the query data will result in a server side error.

Example query: [{"q1":{"query":"Berlin/Germany"}}](https://lobid.org/gnd/reconcile/?queries={%22q1%22:{%22query%22:%22Berlin/Germany%22}})

**Comment by fsteeg** [comment]
Deployed to test, see:

http://test.lobid.org/gnd/reconcile/?queries={"q1":{"query":"Berlin/Germany"}}

**Comment by acka47** [comment]
+1
