### ISSUE TITLE
HTML-Sicht funktioniert nicht bei einigen musikalischen Werken

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#345]
Am 06.06.23 um 15:11 schrieb G.W.:
> nach diese Suche:
> 
> https://lobid.org/gnd/search?q=300188285
> 
> kommen 5 Treffer auf den Schirm.
> 
> Der Klick auf den 1. Treffer
> 
> 	Radamisto <https://lobid.org/gnd/300188285> 	Werk der Musik
> 	Händel, Georg Friedrich
> 1720
> 	 300188285
> 
> 
> führt zur Seite mit der Meldung "Fehler".
> 
> in den anderen Treffern ist jeweils eingetragen:
> 
> Oberbegriff partitiv Radamisto <https://lobid.org/gnd/300188285>
> _______________________________________________
> 
> genauso hier:
> 
> Suche:
> 
> https://lobid.org/gnd/search?q=30024570X
> 
> 2 Treffer
> 
> davon 1. Treffer
>  
> 	Il trionfo del tempo e del disinganno <https://lobid.org/gnd/30024570X> 
> 	Werk der Musik
> 	Händel, Georg Friedrich
> 1707
> 	 30024570X
> 
> Ergebnis: Seite mit der Meldung "Fehler"
> 
> Im 2. Treffer
> 
> https://lobid.org/gnd/1152424785 ist eingetragen:
> 
> Oberbegriff partitiv Il trionfo del tempo e del disinganno 
> <https://lobid.org/gnd/30024570X>

**Comment by acka47** [comment]
Zur Information: Eingeführt wurden die Änderungen am 27. September 2022 (Export-Release 2022.03). Aus der [Ankündigung](https://www.dnb.de/SharedDocs/Downloads/DE/Professionell/Metadatendienste/Rundschreiben/rundschreiben20220627AenderungenRDF.pdf?__blob=publicationFile&v=3):

> ### 3.2.3. Ergänzung zur Modellierung von Besetzungsangaben bei Werken der Musik
> * Neuerung:
Sechs neue datatype properties zur Beschreibung von Besetzungsangaben bei Werken
der Musik werden eingeführt:
>   * `gndo:mediumOfPerformanceAsLiteral`
>   * `gndo:numberOfEnsemblesOfTheSameType`
>   * `gndo:numberOfPerformersOfTheSameMedium`
>   * `gndo:alternativeMediumOfPerformance`
>   * `gndo:totalNumberOfPerformers`
>   * `gndo:totalNumberOfEnsembles`

**Comment by acka47** [comment]
+1 für die Umsetzung, das HTML wird wieder gerendet. Allerdings werden nicht alle im RDF/JSON-LD verfügbaren Informationen im HTML angezeigt. Ich habe mit  #346 ein allgemeines Ticket angelegt, um die Unterschiede zwischen GND RDF und HTML-Sicht zu analysieren und festzulegen, welche Informationen im weiteren Vorgehen im HTML ergänzt werden müssen/sollten.

**Comment by fsteeg** [comment]
> Eingeführt wurden die Änderungen am 27. September 2022 (Export-Release 2022.03)

Grundsätzlich hatten wir das da auch eingebaut, s. https://github.com/hbz/lobid-gnd/issues/326.

Das Problem hier scheint ein spezifischer Fall zu sein (Struktur ohne `id`, `label`).

**Comment by rettinghaus** [comment]
Noch ein Problem: _Werke der Musik_ die `numberOfPerformersOfTheSameMedium` verwenden (z.B. https://lobid.org/gnd/30024570X, https://lobid.org/gnd/300006888), zeigen in der HTML-Ansicht jetzt einen (invaliden) Link zu [EntityFacts](https://www.dnb.de/entityfacts). Bei Werken ohne diese Property (z.B. https://lobid.org/gnd/300306075) wird er korrekt unterdrückt.
