### ISSUE TITLE
Use shorter interval for updates

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-gnd#350]
By W.G. from UB Müster came the request to use a shorter interval for the updates. Daily updates would not be suffixient for them and DNB provides updates all 10 min.

Perhaps we adjust our updates updates even if we do not meet 10 min.

**Comment by TobiasNx** [comment]
@acka47 says we have to check if dnb offers 10 min updates as rdf

**Comment by dr0i** [comment]
As it turns out the problem is: DNB doesn't update their RDF data this frequently but only the MARC-XML - so we would have to write some ETL (where is the DNB's morph - we could reuse it?).

**Comment by TobiasNx** [comment]
> Der Abfragezeitraum sollte nicht zu weit reichen, um eine Treffermenge über 100.000 Datensätzen zu vermeiden. Empfehlung bei nicht zeitkritischen Verfahren für Abfragezeitraum/Frequenz: 30 Minuten. Bei kleinen Sets (z. B. Online-Dissertationen) reicht ein einmal tägliches oder einmal wöchentliches Harvesting aus, da dadurch ein Datensatz, der in diesem Zeitraum mehrfach geändert wurde, nur einmal bezogen und die Treffermenge trotzdem nicht zu groß wird.
Wir empfehlen zudem als Wiederaufsetzzeitpunkt ("from") die Zeitangabe im Element "responseDate", z. B. <responseDate>2017-08-30T08:12:54Z</responseDate> zu nutzen, da diese Zeitangabe der aktuellen Verfügbarkeit der Daten in unserem Repository am besten entspricht. Zusätzlich empfehlen wir das Harvesten mit einer geringen zeitlichen Überlappung ("responseDate" minus eine Minute = "from").


From: https://www.dnb.de/DE/Professionell/Metadatendienste/Datenbezug/OAI/oai_node.html

**Comment by acka47** [comment]
Also in [Der Linked-Data-Service der Deutschen Nationalbibliothek: Auslieferung der Metadaten](https://www.dnb.de/SharedDocs/Downloads/DE/Professionell/Metadatendienste/linkedDataZugriff.pdf?__blob=publicationFile&v=3) it reads:

> Die RDF-Daten sind über die DNB-Schnittstellen OAI 24 , SRU 25 und den Datenshop 26 zu beziehen.
Die auf diesen Wegen ausgelieferten Metadaten befinden sich auf dem aktuellen zeitlichen Stand.

So we should just try out shorter update intervals, I guess.

**Comment by TobiasNx** [comment]
https://services.dnb.de/oai/repository?verb=ListIdentifiers&from=2023-10-10T07:08:23Z&until=2023-10-10T08:08:23Z&set=authorities&metadataPrefix=RDFxml

https://services.dnb.de/oai/repository?verb=ListIdentifiers&from=2023-10-10T08:08:23Z&until=2023-10-10T09:08:23Z&set=authorities&metadataPrefix=RDFxml

https://services.dnb.de/oai/repository?verb=ListIdentifiers&from=2023-10-10T10:08:23Z&until=2023-10-10T11:08:23Z&set=authorities&metadataPrefix=RDFxml

https://services.dnb.de/oai/repository?verb=ListIdentifiers&from=2023-10-10T11:08:23Z&until=2023-10-10T12:08:23Z&set=authorities&metadataPrefix=RDFxml

https://services.dnb.de/oai/repository?verb=ListIdentifiers&from=2023-10-10T12:08:23Z&until=2023-10-10T13:08:23Z&set=authorities&metadataPrefix=RDFxml

**Comment by dr0i** [comment]
If #355 is merged the cron scheduler can be adjusted to get the data e.g. every 10 minutes.

**Comment by dr0i** [comment]
As getting data every 10 minutes often results in an empty data set we disable sending emails that warns about empty data sets for now. We may want to furtherdiscuss this, e.g. implement a daily report or getting the OAI-PMH's server header resp. answer and work on these (i.e. ignore if the server reports  `<error code="noRecordsMatch"/>`).

**Comment by dr0i** [comment]
We checked this and it seems to work. Got 7 new resources in the last 20 minutes !
We should blog and inform users.

**Comment by dr0i** [comment]
We should also update http://lobid.org/gnd/dataset:
>Datenbasis sind die [RDF-Version der GND](https://www.dnb.de/lds#doc58246bodyText1) (täglich aktualisiert)

(hm, also:  maybe that's why the data seems to be updated only _every hour_ (not every 10 minutes, even if we try to get data all 10 minutes) . If that's the case we should decrease getting data interval @acka47 .)

**Comment by acka47** [comment]
As we have just discussed in the review, we will schedule hourly updates.

**Comment by dr0i** [comment]
Done scheduling hourly. Every_hour:40m.
Note: blog when new full indexing is done.

**Comment by dr0i** [comment]
None is willing to write the blog. As this is not mandatory, I am closing this issue here.

**Comment by TobiasNx** [comment]
I think we still should do this.

We could keep it short:

> Title: Hourly updates intervals for lobid-gnd
> 
> For lobid-gnd we fetch the GND as RDF-XML via OAI-PMH from the DNB and transform it to JSON-LD.
> At SWIB 2023 a colleague from UB Münster suggested to shorten our interval for ingesting OAI-PMH updates
> which we provided at a daily basis.
> 
> Now we are glad to announce that lobid-gnd provides hourly updates so you do not have to wait for the next day to get current GND data.
> 
> Have fun with it.

**Comment by dr0i** [comment]
I've deployed it, see https://blog.lobid.org/.
