### ISSUE TITLE
Support filtering of GND-Hinweissätze

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#351]
Reported today by @kkrebs via email.

> einer Nutzerin unseres Repositories ist aufgefallen, dass sie bei der 
> Schlagwortsuche, die wir über lobid anbieten, auch sogenannte 
> "Hinweissätze" [1] findet. Beispiel ist GND 7503924-2 für den Eintrag
> 
>      Erziehungsforschung [Hinweissatz]
> 
> Die Spezifikation besagt: "Hinweissätze dürfen zur sachlichen 
> Erschließung von Titeldaten nicht verwendet werden." Diese gibt es nur 
> als Übergangsregel und sie "transportieren einen Sucheinstieg für einen 
> Nicht-Deskriptor."
> 
> Da wir die lobid-GND-Suche aber in den Erfassungsmasken anbieten, 
> müssten wir an dieser Stelle alle Hinweissätze herausfiltern können. 
> Dazu habe ich jetzt aber auf Anhieb nichts gefunden. Könnt ihr mir 
> vielleicht weiter helfen?
> 
> [1] https://wiki.dnb.de/download/attachments/90411369/AWB-R01-R03.pdf

**Comment by kkrebs** [comment]
Ich muss zugeben im Detail habe ich das auch noch nicht ganz durchdrungen. Aber man kann es zumindest auf der Webseite der DNB erkennen: https://d-nb.info/gnd/7503924-2
Dort steht "Hinweis für" in der GND-Anzeige. Aber woraus sich das ableitet und wie ich an weitere Beispiele komme ist mir auch nicht ganz klar. Evtl. kann man bei der DNB nachfragen?

**Comment by thoffma** [comment]
Hallo! (Ich bin zurück aus der Elternzeit ;) )
Es gibt einen Hinweis auf Hinweisdatensätze in RDF. Und zwar wird die Property https://d-nb.info/standards/elementset/gnd#complexSeeReferenceSubject verwendet.

```
<https://d-nb.info/gnd/7504106-6> gndo:complexSeeReferenceSubject 
                        <https://d-nb.info/gnd/4011882-4>, <https://d-nb.info/gnd/4053532-0>;
```

Bsp.
https://d-nb.info/gnd/7504987-9 ist ein Hinweisdatensatz und dort wird dann darauf hingewiesen, dass man bitte eine Kombination aus verschiedenen Schlagwörtern benutzen soll anstatt diesen.

Weitere Beispiele:
https://d-nb.info/gnd/7510058-7
https://d-nb.info/gnd/7504106-6

Die Position 4 in der Dokumentation bezieht sich nicht auf MARC 008 sondern auf PICA 002@

**Comment by acka47** [comment]
Danke, @thoffma ! Das habe ich wohl übersehen, aber das ist ja großartig. Dann können die also bereit srausgefiltert werden mit `NOT _exists_:complexSeeReferenceSubject` z.B. http://lobid.org/gnd/search?q=Erziehungsforschung+AND+NOT+_exists_%3AcomplexSeeReferenceSubject

@kkrebs Das sollte doch reichen, oder? Gib bitte kurz bescheid, ob wir das Ticket schließen können.

**Comment by acka47** [comment]
@kkrebs Bezugnehmend auf meinen Kommentar https://github.com/hbz/lobid-gnd/issues/351#issuecomment-1722931421 hake ich nochmal nach, ob das Ticket geschlossen werden kann. Oder fehlt noch irgendetwas für deinen Anwendungsfall?

**Comment by kkrebs** [comment]
Danke für die Rückmeldung. Wir werden den Filter so einbauen und können das Ticket hier gern schließen. Sollte es doch noch Probleme geben, melde ich mich nochmal.
