### ISSUE TITLE
Updating data sometimes crashes

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-gnd#363]
At  `Nov 12 21:00` there is this crash log `hs_err_pid2595418.log`
```
V  [libjvm.so+0xacb58a]  VMError::report_and_die()+0x2ba
V  [libjvm.so+0x4ff069]  report_fatal(char const*, int, char const*)+0x59
V  [libjvm.so+0x9c6b2a]  SharedRuntime::continuation_for_implicit_exception(JavaThread*, unsigned char*, SharedRuntime::ImplicitExceptionKind)+0x33a
...
Event: 7.030 Thread 0x00007fee6dbc6000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x00007fee4d726ffc method=sbinary.JavaOutput.writeByte(B)V @ 5
...
Internal exceptions (10 events):
Event: 2.675 Thread 0x00007fee6c00a800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x000000076d33dee0) thrown at [/HUDSON/workspace/8-2-build-linux-amd64/jdk8u151/9699/hotspot/src/share/vm/runtime/sharedRuntime.cpp,
 ...
Event: 6.867 Thread 0x00007fee6dbbf000 Exception <a 'java/io/FileNotFoundException'> (0x000000077b2d8698) thrown at [/HUDSON/workspace/8-2-build-linux-amd64/jdk8u151/9699/hotspot/src/share/vm/prims/jni.cpp, line 709]
...
Event: 7.063 loading class sbt/SessionVar$Key done
Event: 7.065 Executing VM operation: RevokeBias
```
May well be a result of https://github.com/hbz/lobid-gnd/pull/355.  If so, we shall react to https://github.com/hbz/lobid-gnd/issues/350#issuecomment-1805930760 :
> Would be nice to have a running webhook listener who would just start the process from an already running instance like in https://github.com/hbz/lobid-resources/issues/1159 ).

**Comment by acka47** [comment]
We keep getting in reports of missing GND entries, see https://github.com/hbz/lobid-gnd/issues/372#issuecomment-1898739646 & #376. @dr0i could you take this over and investigate whether this is the cause?

**Comment by dr0i** [comment]
Keeping track. This issue cannot be the cause, though, as there is no further crash log since the mentioned one from November 2023.

**Comment by dr0i** [comment]
Commented in [372](https://github.com/hbz/lobid-gnd/issues/372#issuecomment-1952055639) . Closing this issue here as no more crash logs have appeared.
