### ISSUE TITLE
Update with new RDF dumps 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#366]
RDF dumps from 2013-11-13 have been provided by DNB last week, see https://data.dnb.de/opendata/.

That means we can now update lobid-gnd and incorporate all the latest changes to the GND RDF. This is connected to the following issues will wil have to revisit and – hopefully – close these two issues:

- #357
- #333 

We might also have a look at #359 while we are at it.

**Comment by fsteeg** [comment]
Deployed new baseline to test, see e.g.

https://test.lobid.org/gnd/search?q=_exists_:usingInstructions

In addition to the issues above, this should also resolve https://github.com/hbz/lobid/issues/419, e.g.:

https://test.lobid.org/gnd/1043940596

**Comment by acka47** [comment]
+1 for deploying this to production soon as test contains ~6k more entries than production. 

Note, though, that #357 is **NOT** resolved by this, See the example 4119779-3 at https://test.lobid.org/gnd/4119779-3.json where `variantName` strings don't have any language indication. We will have to take a look at this at another point.

**Comment by fsteeg** [comment]
> +1 for deploying this to production [...]

Switched production index:

https://lobid.org/gnd/search?q=_exists_:usingInstructions
https://lobid.org/gnd/1043940596

> Note, though, that https://github.com/hbz/lobid-gnd/issues/357 is NOT resolved by this [&rarr; in #357:] not sure we can incorporate this information in lobid-gnd without an API break

Yes, we're skipping the tags for API compatibility, see https://github.com/hbz/lobid-gnd/issues/243#issuecomment-548371516, https://github.com/hbz/lobid-gnd/commit/eaa7ff0d3bb7d0dba690e674833f6f5d8ef915bd

**Comment by acka47** [comment]
Done. Closing.
