### ISSUE TITLE
Missing update for https://lobid.org/gnd/1061501078 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#377]
We had an email request to correct the `preferredName` for https://lobid.org/gnd/1061501078 ("Deghenghi" instead of "Deghengi"). Forwarding this to hbz GND editors I got the answer that this was already corrected on 2024-01-31, see https://d-nb.info/gnd/1061501078 and the [MARC](http://d-nb.info/gnd/1061501078/about/marcxml) which contains this information on last update: `controlfield tag="005">20240131010506.0</controlfield>`.

The [RDF](http://d-nb.info/gnd/1061501078/about/lds) also contains the change:

```ttl
<https://d-nb.info/gnd/1061501078>  gndo:preferredNameForThePerson "Deghenghi, Mario".
<https://d-nb.info/gnd/1061501078/about> dcterms:license <http://creativecommons.org/publicdomain/zero/1.0/>;
  dcterms:modified "2024-01-31T01:05:06.000"^^xsd:dateTime. 
```

Apparently, this is also an update problem, maybe related to #363 .

**Comment by fsteeg** [comment]
Fixed by reindexing: https://lobid.org/gnd/1061501078

**Comment by acka47** [comment]
Thanks, closing.
