### ISSUE TITLE
Error on implementation of SVG-Images from Wikimedia Commons

### ISSUE THREAD

**Issue by LibrErli** [hbz/lobid-gnd#385]
E.g. [ZHB Luzern](https://lobid.org/gnd/4647881-4) retrieves as example image the logo image stored as *svg on Wikimedia Commons. It seems that the lobid-imageproxy has troubles with implementing svg correctly. 

* Image-Proxy-URL: https://lobid.org/imagesproxy?url=https://commons.wikimedia.org/wiki/Special:FilePath/ZHB%20Luzern%20Logo%20farbig.svg?width=270
* FilePath: https://commons.wikimedia.org/wiki/Special:FilePath/ZHB%20Luzern%20Logo%20farbig.svg

**Comment by dr0i** [comment]
The image seems to be of type `PNG`:
```
$ curl -L 'https://commons.wikimedia.org/wiki/Special:FilePath/ZHB%20Luzern%20Logo%20farbig.svg?width=270' -o image
$ file image
image: PNG image data, 270 x 60, 8-bit colormap, non-interlaced
```
But lobid's imagesproxy tries to parse it, based on the file's name, as `SVG` - which consequently fails.

What we can do: change the  `imagesproxy` to:
a)  determine type of image by taking the `content-type` header into account (and not just by parsing the URL to determine get the file's suffix)
b) get rid of all HTML parameter (?.*) - that would leave us with ` curl -L 'https://commons.wikimedia.org/wiki/Special:FilePath/ZHB%20Luzern%20Logo%20farbig.svg` which _is_ a `SVG`

As a hip-shot I would say b) is easier to do, but then we might not fix all scenarios. On the other hand, a) may also be problematic, _if_ not all images have a `content-type` header. (b) could also be just a fallback if a URLs path is not ending with a dot + three characters (aka file extension).

**Comment by acka47** [comment]
What is the status of this, @phu2 @dr0i ?

**Comment by Phu2** [comment]
+1 for b)

@dr0i  Where does the parameter come from?

Sorry for the delay. Somehow i missed this issue.

**Comment by Phu2** [comment]
SVGs don't have a size. Requesting SVGs using `width` parameter make Wikimedia deliver PNGs.

**Comment by dr0i** [comment]
Parameter comes from `depiction.thumbnail` in https://lobid.org/gnd/4647881-4.json .
Looking at the data, it seems that if we would use `depiction.id` we would get the URL ending with the file extension. If that's always the case we could use just switch to use this field (images would be a of greater size, but then the internet is fast enough and images are only served when using the web UI (few hits resulting from human interactions) and not the web API (possible millions of hits resulting from machine interactions). WDYT @Phu2 ?

**Comment by Phu2** [comment]
Otherwise, it just needs this minor adjustment https://github.com/hbz/lobid/commit/a5d0b23dce4dfb7955e2945cb471143fb8ec37bc in order to get the correct content type? But maybe i'm on the wrong track.

**Comment by dr0i** [comment]
@Phu2 I like your proposal also. Please merge and deploy :+1:

**Comment by dr0i** [comment]
+1

**Comment by Phu2** [comment]
Deployed to production.
Now this also works: https://lobid.org/imagesproxy?url=https://commons.wikimedia.org/wiki/Special:FilePath/ZHB%20Luzern%20Logo%20farbig.svg?width=270

Fixed by https://github.com/hbz/lobid/commit/e1083c95a5c0583f29ae9d4deddb7fe79dd84360 (sorry, used wrong reference in commit messgae)

**Comment by LibrErli** [comment]
one question: for months (maybe it has something to do with your work on imagesproxy for svg-files) all the icons in the "same As" section are "broken". e.g. https://lobid.org/imagesproxy?url=https://en.wikipedia.org/static/favicon/wikipedia.ico

**Comment by Phu2** [comment]
Thanks for reporting, @LibrErli I will look into it.
