### ISSUE TITLE
Improve /reconcile page

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#394]
As discussed today with DNB colleagues:

- [x] use official GND Logo -> https://gnd.network/Webs/gnd/DE/UeberGND/Infothek/Logos/logos_node.html
-  [x] Remove lobid header and apply gnd-network look
-  [x] add introduction text

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd/reconcile
