### ISSUE TITLE
Improve searching and ranking at the example of Mark Twain

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid-gnd#40]
1. [Searching for Mark Twain](https://lobid.org/gnd/search?q=Mark+Twain). The resource https://lobid.org/gnd/118624822 should appear as first entry.
- because perfect match with preferredNameEntityForThePerson
- because  118624822 is of type DifferentiatedPerson (DifferentiatedPerson should be preferred over not differentiated datatypes)
2. [Searching for 118624822](https://lobid.org/gnd/search?q=118624822). The resource https://lobid.org/gnd/118624822 should appear as first (and only ?!) entry.
- because perfect match to gndIdentifier

**Comment by fsteeg** [comment]
Deployed to test:

https://test.lobid.org/gnd/search?q=Mark+Twain
https://test.lobid.org/gnd/search?q=118624822

**Comment by acka47** [comment]
Just noticed that ID search also works for hyphenated GND IDs, e.g. https://test.lobid.org/gnd/search?q=4122597-1. Very good.

**Comment by ChristophEwertowski** [comment]
+1 But you should open a pull request, too.
