### ISSUE TITLE
Images won't load via Wikimedia images proxy

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#405]
We had this before (#291) but as this seems to be different, I am opening another issue.

Images won't load and the page seems to be in a perpetual loading state because of failing to load the image. Firefox dev tools do not really give back an error message or even the request. Example: https://lobid.org/gnd/119560275

**Comment by Phu2** [comment]
From `/var/log/php7.4-fpm.log`:

`[22-Aug-2024 15:17:39] WARNING: [pool www] server reached pm.max_children setting (37), consider raising it`

Raising the limit to `50` in `/etc/php/7.4/fpm/pool.d/www.conf` fixes the script for now. Need to investigate these pool settings further.

**Comment by Phu2** [comment]
With 

- **8GB** RAM available in total and 
- 50 max child process x approx. 18 MB each child process = approx. **900 MB**

this limit seems to be save. We could even set a higher limit if needed.
Closing.
