### ISSUE TITLE
Improve (sub-)type filtering

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#42]
Currently, we only allow filtering by first-level types `Person`, `CorporateBody`, `ConferenceOrEvent`, `Work`, `PlaceOrGeographicName`, `SubjectHeading`, `Family`.

One adjustment should be that the filter section adjusts when clicking on a type: Either the not-clicked first-level types shoud disappear (and the sub-types should be shown, see below) or the not-clicked types should be greyed out.

We should also enable filtering by the subtypes in these two ways:

1. Add a "+" sign to first-level types with sub-typing so that people can klick on it and the sub-types are shown. (E.g. for "Place or Geographic Name" "Building or Memorial", "Administrative Unit", "Fictive Place" etc.)
2. Filtering by a first-level type should yield filtered search results with sub-facets opening up

**Comment by fsteeg** [comment]
Deployed drill down in type facet to test: http://test.lobid.org/gnd/search

**Comment by fsteeg** [comment]
Updated with improved visual structure as discussed offline: http://test.lobid.org/gnd/search

**Comment by acka47** [comment]
Looks better but there isn't any order in the subtype list. Ordering by number of occurences would make most sense I guess.

**Comment by acka47** [comment]
We also have to think about another representation of the filters chosen when you have clicked on a "sub type". As there are different things adding up, maybe we should take a step back and think about a good usage concept of filtering by type and subtypes...

**Comment by fsteeg** [comment]
Updated with improved order of facet entries: http://test.lobid.org/gnd/search

**Comment by acka47** [comment]
We decided to not only show top levels in the facets from the beginning but also sub-classes indented below their super class.

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/gnd/search

**Comment by ChristophEwertowski** [comment]
+1 for the showing of subclasses. But the link of the last entry `gnd:Expression` fails.

**Comment by fsteeg** [comment]
Redeployed with fixed `Expression`: http://stage.lobid.org/gnd/search

**Comment by acka47** [comment]
Looks good but it looks really cluttered now so that we need to collapse this as default as I wrote in the original comment:

> Add a "+" sign to first-level types with sub-typing so that people can klick on it and the sub-types are shown.

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/gnd/search

**Comment by fsteeg** [comment]
Ping @acka47 @ChristophEwertowski

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1
