### ISSUE TITLE
Use information from EntityFacts

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#44]
Documentation: http://www.dnb.de/DE/Service/DigitaleDienste/EntityFacts/entityfacts_node.html

Example of `sameAs` links for [London](http://hub.culturegraph.org/entityfacts/4074335-4):

```json
{
  "sameAs":[
    {
      "@id":"http://d-nb.info/gnd/4074335-4/about",
      "collection":{
        "abbr":"DNB",
        "name":"Gemeinsame Normdatei (GND) im Katalog der Deutschen Nationalbibliothek",
        "publisher":"Deutsche Nationalbibliothek",
        "icon":"http://www.dnb.de/SiteGlobals/StyleBundles/Bilder/favicon.png?__blob=normal&v=1"
      }
    },
    {
      "@id":"http://viaf.org/viaf/236493943",
      "collection":{
        "abbr":"VIAF",
        "name":"Virtual International Authority File (VIAF)",
        "publisher":"OCLC",
        "icon":"http://viaf.org/viaf/images/viaf.ico"
      }
    },
    {
      "@id":"http://www.wikidata.org/entity/Q6669738",
      "collection":{
        "abbr":"WIKIDATA",
        "name":"Wikidata",
        "publisher":"Wikimedia Foundation Inc.",
        "icon":"https://www.wikidata.org/static/favicon/wikidata.ico"
      }
    },
    {
      "@id":"https://de.wikisource.org/wiki/London",
      "collection":{
        "abbr":"WIKISOURCE",
        "name":"Wikisource",
        "publisher":"Wikimedia Foundation Inc.",
        "icon":"https://wikisource.org/static/favicon/wikisource.ico"
      }
    },
    {
      "@id":"https://en.wikipedia.org/wiki/London%2C_Wisconsin",
      "collection":{
        "abbr":"enwiki",
        "name":"Wikipedia (English)",
        "publisher":"Wikimedia Foundation Inc.",
        "icon":"https://en.wikipedia.org/static/favicon/wikipedia.ico"
      }
    }
  ]
}
```

First step: Use EntityFacts to show links (using the icons linke din the JSON) to other resources in the HTML interface.

Possible further step: Enrich JSON-LD with links from EntityFacts. There might be a dump in the future we could build a map from, see https://twitter.com/junicatalo/status/971793109796433926.

**Comment by acka47** [comment]
Also of interest: links to depictions of an entity, see e.g. http://hub.culturegraph.org/entityfacts/11850391X:

```json
{
  "depiction":{
    "@id":"https://commons.wikimedia.org/wiki/Special:FilePath/Hannah_arendt-150x150.jpg",
    "thumbnail":{
      "@id":"https://commons.wikimedia.org/wiki/Special:FilePath/Hannah_arendt-150x150.jpg?width=270"
    },
    "url":"https://commons.wikimedia.org/wiki/File:Hannah_arendt-150x150.jpg?uselang=de"
  }
}
```

**Comment by acka47** [comment]
An EntityFacts dump (as a test, no updates promised for now) dump is now available, see https://data.dnb.de/opendata/ (file name 20180312-EFDump-de-DE.json.gz).

**Comment by acka47** [comment]
1st step: Set up an EntityFacts index in the cluster. Assigning @dr0i .

**Comment by acka47** [comment]
With this approach the long URLs to Wikipedia, DBpedia, Filmdienst, Viaf etc. should be replaced by a list of icons linking to the respective source. (Also, the DNB link should be part of this list.)

**Comment by dr0i** [comment]
Around 5.7M documents where send in 1 hour to ES. It took around 5h to index that into the index called `entityfacts`. The amount of the input data matches with that of the docs of the index, so all is fine here. Note, no index-config was used, so everything is mapped dynamically. Although the index is small (~8GB) it would be nice to define which fields doesn't need to be indexed, etc. ,to shrink the space needed and fasten the indexing time.

**Comment by fsteeg** [comment]
> it would be nice to define which fields doesn't need to be indexed

@dr0i: I've set up basic data access (see https://github.com/hbz/lobid-gnd/commit/e280185eca0e0f28c73ff5a2536c08bdb459b128) and all I need for queries is the `@id` field. With the GND ID as internal ES ID we could do without queries, just ES GET API, if that would make sense.

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/gnd/2047974-8
http://stage.lobid.org/gnd/138457913
http://stage.lobid.org/gnd/4031483-2

**Comment by acka47** [comment]
Add "Quelle" infromation with links to DNB à la https://d-nb.info/gnd/4031483-2/about/lds.rdf and to EntityFacts (if used).

**Comment by fsteeg** [comment]
Deployed to test, see:

http://test.lobid.org/gnd/4179170-8
http://test.lobid.org/gnd/4791358-7

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
There is still a rpoblem with the Cornell logo being shown on different entries, e.g. http://stage.lobid.org/gnd/365265-8. I grepped the EntityFacts dump and there the image only is associated with Cornell.

**Comment by fsteeg** [comment]
Looks like something went wrong during indexing then, see:

http://10.9.0.14:9200/entityfacts/_search?q=@id:%2238325-9%22
http://hub.culturegraph.org/entityfacts/38325-9

@dr0i Or could they have fixed the dump in the meantime? Could you check the dump you used?

**Comment by fsteeg** [comment]
Discussed offline with @dr0i: it seems like documents were partially updated during indexing.

New index should be available tomorrow, assigning @acka47 for review.

**Comment by fsteeg** [comment]
Fixed on test: https://test.lobid.org/gnd/365265-8

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
> With the GND ID as internal ES ID we could do without queries, just ES GET API, if that would make sense.

Makes sense - that's even _mandatory_ to build an updatable index. So I'm going to implement it.

**Comment by fsteeg** [comment]
I think we should continue work on this in https://github.com/hbz/lobid-gnd/issues/69 and leave this closed.

**Comment by dr0i** [comment]
As discussed offline: the branch of the index-building is not even opened, and thus not merged. I will continue to bring this branch to a happy end here.
