### ISSUE TITLE
Hide variant names in detail view

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#47]
When there are lots of variant names it doesn't look very good, e.g. https://test.lobid.org/gnd/1083009273

If we show the field at all we should hide it by default like so:

<details>
Gelin-xiongdi; Grimmů, Bratří; Grim, Broliai; Grimm, Frers; Grimm, Brüder; Grimm, Irmãos; Grimm, Bröderna; Grimm, Brothers; Grimm, Fratelli; Grimm, Bratraj; Grimai; Grîm, hā-Āḥîm; Grimmovci; Gkrim, Adelphōn; Grimm, Gebroeders; Grimm, Bratří; Grimm, Braci; Grim, Ve͏̈llez͏̈rit; Grimm, Bracia; Kardešler Grimm; Breudeur Grimm; Grimm, Frères; Grimm, Brdr.; Grimm, Braty; Grimm, Hermanos; Grimm, Frars; Gurimu; Gebrüder Grimm; Grimm, Brat'ja; Grimm, Brieder; Grim, Braḱata; Grimm, Germans; Adelphōn Gkrim; Grimmové; Gha-rim; Grīm, Barādarān-i; Grimm, G.; Grin; Ki-lwen; Braḱata Grim; Grimm, Bratʹev; Kŭrim, Hyŏngje; Grimmu, Brāļu; Kŭrīm, hyŏngje; Grimm, Braća; Grim, Bratja; Braci Grimm; Grim, Brider; Grimm, Gebrüder; Grimm, Frații; Grimm, Brata; Gkrimm, Adelphoi; Ghi-rim; Grimm, Brødrene; Grimm, Kardešler; Gurimu, Kyōdai; Grim Bandhu; Ge lin xiong di; Grimmin, Veljekset; Gimrm, Jcoab; Grimm, Bratray
</details>

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd/1083009273

**Comment by acka47** [comment]
I am not that happy with this solution. I don't think that we should link to the JSON other than we already do  in the top right corner. I'd rather leave out the field completely in the HTML or collapse the labels as written in the first comment.

**Comment by fsteeg** [comment]
Collapsing is a bit more involved, would require some restructuring of the implementation (the whole table is just a flat list internally, so I'd have to introduce some way to distinguish the separate field groups). I'd expect users to be confused if they find an entity via its variant name but don't see any variant names in the details.

How about adding the remaining variant names to a popup on the `...` icon istead of linking to the JSON?

**Comment by ChristophEwertowski** [comment]
I would be fine with a popup but then there should be more space between the points of the icon. My eyes first saw little "-".

**Comment by fsteeg** [comment]
Updated on test: https://test.lobid.org/gnd/1083009273

**Comment by ChristophEwertowski** [comment]
Intuitively I clicked on the plus but probably that's just my brain. Hovering works fine. +1

**Comment by acka47** [comment]
It's not just your brain. "+" commonly means expand so we should use another icon (or another approach).

**Comment by fsteeg** [comment]
Updated with another ellipsis icon: https://test.lobid.org/gnd/1083009273

**Comment by acka47** [comment]
+1
