### ISSUE TITLE
Use German labels from GND ontology for entity types & properties

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#48]
I will provide a label per type in a later comment to this issue.

**Comment by acka47** [comment]
Pick labels from the GND ontology: https://d-nb.info/standards/elementset/gnd

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/gnd/search
http://stage.lobid.org/gnd/2047974-8

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
+1
