### ISSUE TITLE
Person/DifferentiatedPerson missing for subclasses

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#55]
E.g. God & spirit, example http://test.lobid.org/gnd/1024589951

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/gnd/1024589951

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
So we are not adding "DifferentiatedPerson" for subtypes of it. (I think we already loosely discussed it offline). Seems ok to me from the user-perspective. +1

**Comment by fsteeg** [comment]
Deployed to production, closing. See http://lobid.org/gnd/1024589951
