### ISSUE TITLE
Provide more filter options

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#59]
We discussed which filter options we could add. I identified for additional filters that could be useful, two of them only covering persons:

- GND-Sachgruppen: ~11% of all entities have a Sachgruppe associated with them, see http://stage.lobid.org/gnd/search?q=_exists_%3AgndSubjectCategory
- Geographic area code: ~37% of all resources have a geographic area code, see http://stage.lobid.org/gnd/search?q=_exists_%3AgeographicAreaCode

For differentiated persons which account for ~31% of the entries, there are two more:
- dateOfBirth: (~52% of differentiated persons, see http://lobid.org/gnd/search?q=_exists_%3AdateOfBirth&filter=%2B%28type%3ADifferentiatedPerson%29)
- professionOrOccupation (~52% of differentiated persons, see http://lobid.org/gnd/search?q=_exists_%3AprofessionOrOccupation&filter=%2B%28type%3ADifferentiatedPerson%29)

**Comment by fsteeg** [comment]
Adopting the bar chart for `dateOfBirth` will take some time, so I suggest we create a separate issue for the  `dateOfBirth` facet (which only makes sense as a bar chart, not as a regular facet, right?) to avoid holding up the other facets.

Deployed to stage: http://stage.lobid.org/gnd/search

**Comment by ChristophEwertowski** [comment]
+1 Please don't forget to open the ticket for `dateOfBirth`.

**Comment by acka47** [comment]
Nice. +1

**Comment by fsteeg** [comment]
Opened https://github.com/hbz/lobid-gnd/issues/62

**Comment by isgrim** [comment]
Very nice feature.
A colleague has been a the KIM Workshop in Mannheim and saw the lightning talk and he told me about it.
