### ISSUE TITLE
Add autocomplete support

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#6]
_Copied from https://github.com/lobid/lodmill/issues/468, originally opened by @nichtich. We should consider this for the new implementation of GND lookup. (I think, @jschnasse also mentioned this.)_

> For simple lookup it would be nice to add `format=suggest` in OpenSearch Suggestions format. Format `short` returns a plain array of strings, e.g. http://api.lobid.org/person?name=Marx&format=short

```
[
    "Marx, Antônio Augusto (1919-)",
    "Marx, J. A.",
    "Marxsen, Peter Christian (1806-1869)",
    ...
]
```

> OpenSearch Suggestions would be:

 ```
[
    "Marx",
    [
        "Marx, Antônio Augusto",
        "Marx, J. A.",
        "Marxsen, Peter Christian",
        ...
    ],
    [
        "Architekt und Künstler (1919-)"
        "Organist und Musiker in Yselstein",
        "Subrektor (1806-1869)",
        ...
    ],
    [
        "http://d-nb.info/gnd/1030092001",
        "http://d-nb.info/gnd/1012540626",
        "http://d-nb.info/gnd/1016221088",
        ...
    ],    
]
```

**Comment by fsteeg** [comment]
In [resources](http://lobid.org/resources/api#auto-complete) and [organisations](http://lobid.org/organisations/api/de#auto-complete) we have a customizable suggestions format that works well with the jQuery autocomplete widget. For consistency, I think we should use the same format in authorities too.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
In https://github.com/lobid/lodmill/issues/801#issuecomment-327780679, @jschnasse wrties how he uses the 1.x API for auto suggestion.

**Comment by fsteeg** [comment]
> See http://ws.gbv.de/suggest/gnd/ for another GND autocomplete API. We should better agree on a common API (request and response format).

@nichtich So the idea here would be that API users could use both APIs without code changes or specific code? Like setting up the other API as a fallback if the main API is down?

**Comment by fsteeg** [comment]
@acka47 Deployed to test.

API sample: https://test.lobid.org/gnd/search?q=Twain&format=json:preferredName,dateOfBirth,dateOfDeath,professionOrOccupation

Enabled for search UI:  https://test.lobid.org/gnd/search

API documentation: https://test.lobid.org/gnd/api#auto-complete

**Comment by acka47** [comment]
I tried it out.

1. We need to make this an ngram search on `preferredName` and `variantName` so that I get feedback with every key I hit
2. We will probably have to improve the ranking.
3. The behaviour when chosing an entry from the drop down list has to be improved as well. Currently, the search box is filled with a `id` query but it isn't send. The best thing would be to directly go to the entry page skipping the result list with one entry.

**Comment by fsteeg** [comment]
Deployed to test, with some changes to https://github.com/hbz/lobid-gnd/issues/6#issuecomment-389775128, some of which we discussed offline:

API sample: https://test.lobid.org/gnd/search?q=Twain&format=json:suggest

Enabled for search UI: https://test.lobid.org/gnd

API documentation: https://test.lobid.org/gnd/api#auto-complete

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd/search?q=Twain&format=json:suggest

> I think it would be good to also show the birth date like "1889-1951"

Implemented like in the result list, with `1889-` if we only have the birth date.

> I think we should only show the most general or the most specific type.

Using sub types only, keeping top level types only if we have no sub types.

**Comment by acka47** [comment]
+1 This is really very nice now! And the ranking has already improved a lot due to the recent adjustments so that I think we don't have to change that much. The suggestions could come quicker, though, but this will hopefully be the case when we finally get the SSDs...

**Comment by jschnasse** [comment]
wow - I'm only mentioning it because my firefox insists to use "western" as encoding which results in an "umlaut problem".

**Comment by fsteeg** [comment]
> my firefox insists to use "western" as encoding which results in an "umlaut problem".

Yes I also noticed broken umlauts yesterday when looking at the JSON in mobile Safari. In Firefox (60.0) it works fine for me. Maybe it's an issue with some JSON plugin you're using? So obviously there are clients that don't handle the UTF-8 default for JSON correctly, but I also think it's OK to leave it like this.

**Comment by acka47** [comment]
@nichtich, we now have deployed this for lobid-gnd similarly to how we did it with the other lobid services. Re. additionally offering a standard way for auto-suggest, we can continue the discussion in #106.
