### ISSUE TITLE
Make numbers easier to read

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#60]
For the result and facet counts, e.g. instead of "4577743" "4.577.743". Keep in mind that we will implement this differently for the – to be added – English version of the service.

**Comment by acka47** [comment]
I think it is ok but looks a bit weird for numbers in the millions. Did you also try out a space instead of a period?

**Comment by acka47** [comment]
Forget my comment. +1

**Comment by ChristophEwertowski** [comment]
+1
