### ISSUE TITLE
Set up OpenRefine reconciliation endpoint

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#65]
https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API

See also https://github.com/hbz/lobid-organisations/issues/55 & https://github.com/hbz/lobid-organisations/issues/385.

**Comment by fsteeg** [comment]
Deployed to test:

http://test.lobid.org/gnd/reconcile

http://test.lobid.org/gnd/api#openrefine

`curl --data 'queries={"q1":{"query":"Twain, Mark"}}' http://test.lobid.org/gnd/reconcile`

**Comment by acka47** [comment]
Shouldn't it say `AuthorityResource` (or an array with all the entity types listedf) in the `defaultTypes` field? E.g. like this:

```json
{
  "defaultTypes":[
    {
      "id":"AuthorityResource",
      "name":"authority resource"
    }
  ]
}
```

**Comment by fsteeg** [comment]
> Shouldn't it say AuthorityResource in the defaultTypes field?

Right, if we actually support multiple types that would make sense. The types allow restricting the reconciliation in the OpenRefine UI. So with a single default type the name makes no difference (in lobid-organisations it's 'lobid-organisation', thus 'lobid-gnd' here). Restricting by top-level type would probably be a useful feature, both here and in lobid-organisations.

I suggest we add the funtionality in lobid-gnd in this issue, and open a new issue in lobid-organisations.

**Comment by acka47** [comment]
As it seems to be very simple, we should also add a [suggest API](https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API#suggest-apis).

**Comment by acka47** [comment]
Re. preview API, it might make sense to just deliver the default suggestion string plus a small image if available, similar to wikidata, see e.g. https://tools.wmflabs.org/openrefine-wikidata/en/preview?id=Q42. Providing this as small HTML snippet makes this a bit more complicated, so we might skip this for now.

**Comment by acka47** [comment]
> We have the phenomenon again that OpenRefine not automatically picks a match which is quite comfortable for Open Refine users.

Strange, testing this again with the following data yielded four automatic matches:

```tsv
id	label
01	Ford Taurus
02	Adrian Pohl
03	Niederrhein-Gebiet
04	Puerto Rico. Water Resources Authority
05	Twain, Mark
```

**Comment by fsteeg** [comment]
Deployed restriction by type, see: http://test.lobid.org/gnd/reconcile

About the preview API: it should be quite straightforward to implement, but we're not sure if or where it is used in the OpenRefine UI (I tested with OpenRefine 2.7 and both Wikidata and a local preview implementation for lobid-gnd, @acka47 tested with OpenRefine 3.0 beta and Wikidata reconciliation).

**Comment by acka47** [comment]
+1
