### ISSUE TITLE
Set up Kibana

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#66]
For visualization of different queries. https://www.elastic.co/products/kibana

See the oer world map example: https://oerworldmap.org/assets/html/dashboard.html.

**Comment by dr0i** [comment]
Done. Available under domain of known pattern, only secured by IP-Filtering.

**Comment by dr0i** [comment]
Several ES-index configs have to be adjusted to have nice stats. Will reference this ticket. Closing.

**Comment by dr0i** [comment]
@acka47 removed x-pack (see https://github.com/hbz/lobid/issues/382) and thus kibana is up again.
