### ISSUE TITLE
Show link to work list in person profiles

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#68]
E.g. [Ludwig Wittgenstein's entry](http://lobid.org/gnd/118634313.html) should link to http://stage.lobid.org/gnd/search?q=firstAuthor%3A%22http%3A%2F%2Fd-nb.info%2Fgnd%2F118634313%22&format=html.

We might also try to show a work list below the profile with five entries listed and the possibility to expand the list.

**Comment by acka47** [comment]
We should check `firstAuthor` and `firstComposer` for creating the field.

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd/118512676

**Comment by acka47** [comment]
+1 but please use "Werke" as label.
