### ISSUE TITLE
Include sameAs and depiction information from EntityFacts in lobid-gnd index

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#69]
I wrote in #44:

> Possible further step: Enrich JSON-LD with links from EntityFacts. There might be a dump in the future we could build a map from.

The dump is there now (see https://data.dnb.de/opendata/) and we already set up an ES index with the data. 

Reasons for including the information in the data:
- For some use cases (get all entries with a depiction, give me the GND entry with a specific ISNI etc.) we will need to query the data.
- Also, it is confusing when some things are shown in the HTML that aren't in the JSON.

**Comment by acka47** [comment]
Another challenge is the linking to wikipedia. From GND we get the following:

```json
{
  "id":"http://d-nb.info/gnd/118634313",
  "wikipedia":[
    "https://de.wikipedia.org/wiki/Ludwig_Wittgenstein"
  ]
}
```

In EntityFacts we get links to the German and English wikipedia as part of the `sameAs` array:

```json
{
  "@id":"http://d-nb.info/gnd/118634313",
  "sameAs":[
    {
      "@id":"https://de.wikipedia.org/wiki/Ludwig_Wittgenstein",
      "collection":{
        "abbr":"dewiki",
        "name":"Wikipedia (Deutsch)",
        "publisher":"Wikimedia Foundation Inc.",
        "icon":"https://de.wikipedia.org/static/favicon/wikipedia.ico"
      }
    },
    {
      "@id":"https://en.wikipedia.org/wiki/Ludwig_Wittgenstein",
      "collection":{
        "abbr":"enwiki",
        "name":"Wikipedia (English)",
        "publisher":"Wikimedia Foundation Inc.",
        "icon":"https://en.wikipedia.org/static/favicon/wikipedia.ico"
      }
    }
  ]
}
```
One solution would be to ignore the wikipedia links from GND and only use those from EntityFacts. This would mean that we would lose the links for all resources that are not part of EntityFacts. I think this is ok as on ~170 resources have a wikipedia link that are not also in EntitFacts, see [this query for resources with wikipedia link that are neither of type person, nor corporate body nor PlaceOrGeographicName](http://lobid.org/gnd/search?q=_exists_%3Awikipedia+AND+NOT+type%3APerson+AND+NOT+type%3ACorporateBody+AND+NOT+type%3APlaceOrGeographicName&size=100&format=html).

**Comment by acka47** [comment]
As discussed offline, I am also ok with keeping the – then mostly redundant – wikipedia links in `wikipedia`.

**Comment by fsteeg** [comment]
Currently processing EntityFacts data integrated in our JSON data. When we last discussed this, we said we'd like to stay close to the source data, as we do for the core GND data.

For the `depiction`, I only replaced `@id` with `id` (note it's not an array):

```
"depiction": {
  "id": "https://commons.wikimedia.org/wiki/Special:FilePath/MarkTwain.LOC.jpg",
  "thumbnail": {
    "id": "https://commons.wikimedia.org/wiki/Special:FilePath/MarkTwain.LOC.jpg?width=270"
  },
  "url": "https://commons.wikimedia.org/wiki/File:MarkTwain.LOC.jpg?uselang=en"
}
```

For `sameAs`, I replaced `@id` with `id` and added `collection.name` as `sameAs.label`:

```
"sameAs": [ {
  "id": "https://www.deutsche-digitale-bibliothek.de/entity/118624822",
  "label": "Deutsche Digitale Bibliothek",
  "collection": {
    "abbr": "DDB",
    "name": "Deutsche Digitale Bibliothek",
    "publisher": "Deutsche Digitale Bibliothek",
    "icon": "https://www.deutsche-digitale-bibliothek.de/appStatic/images/favicon.ico"
  }
} ]
```

Added the `label` to be consistent with the normal, non-EntityFacts `sameAs` structure with `id` and `label` (although we don't have actual labels in the GND `sameAs` data yet). The same consistency with other fields would be nice for `depiction` too (but not that urgent, as we don't have `depiction` fields with the `id` and `label` structure, so maybe a separate format for depiction is OK).

I think the whole `collection` thing is not ideal. It has no `id`, making it a bit pointless to introduce a separate entity (it's a blank node when converted to triples). The `icon` is the useful part, and that's similar to the depiction, also an image.

Maybe a `id`/`label`/`image` structure could work both for `depiction`:

```
"depiction": [ {
  "id": "https://commons.wikimedia.org/wiki/File:MarkTwain.LOC.jpg?uselang=en",
  "label": "Mark Twain",
  "image": "https://commons.wikimedia.org/wiki/Special:FilePath/MarkTwain.LOC.jpg"
} ]
```

And for `sameAs`:

```
"sameAs": [ {
  "id": "https://www.deutsche-digitale-bibliothek.de/entity/118624822",
  "label": "Deutsche Digitale Bibliothek",
  "image": "https://www.deutsche-digitale-bibliothek.de/appStatic/images/favicon.ico"
} ]
```

Current implementation uses the EntityFacts JSON and inserts the data into the framed, compacted GND JSON. We will have to look into the context and add some things there to keep our JSON consumable as RDF (`depiction` and `image` if we go with the unified approach, a few more if we stay closer to the EntityFacts format).

**Comment by fsteeg** [comment]
To summarize our offline discussion.

Reorder fields for `depiction`:

```
"depiction": [ {
  "id":"https://commons.wikimedia.org/wiki/Special:FilePath/MarkTwain.LOC.jpg",
  "url":"https://commons.wikimedia.org/wiki/File:MarkTwain.LOC.jpg?uselang=en",
  "thumbnail":"https://commons.wikimedia.org/wiki/Special:FilePath/MarkTwain.LOC.jpg?width=270"
} ]
```

Add `id` to `collection` for `sameAs` from EntityFacts:

```
"sameAs": [ {
  "id":"https://www.deutsche-digitale-bibliothek.de/entity/118624822",
  "collection":{
    "id":"http://d-nb.info/gnd/1070828033",
    "abbr":"DDB",
    "name":"Deutsche Digitale Bibliothek",
    "publisher":"Deutsche Digitale Bibliothek",
    "icon":"https://www.deutsche-digitale-bibliothek.de/appStatic/images/favicon.ico"
  }
} ]
```

Add  `collection` to `sameAs` from GND instead of `label`:

```
"sameAs": [ {
  "id": "http://viaf.org/viaf/9537769",
  "collection": {
    "id": "https://viaf.org",
    "abbr": "VIAF",
    "name": "Virtual International Authority File (VIAF)",
    "publisher": "OCLC",
    "icon": "http://viaf.org/viaf/images/viaf.ico"
  }
} ]
```

**Comment by acka47** [comment]
Here are the URIs for the different collections in EntityFacts. For consistency's sake I only took URIs from Wikidata. There are three URIs missing where we have to create a wikidata entry first.

- VIAF: http://www.wikidata.org/entity/Q54919
- DDB: http://www.wikidata.org/entity/Q621630
- Deutschsprachige Wikipedia: http://www.wikidata.org/entity/Q48183
- Englischsprachige Wikipedia: http://www.wikidata.org/entity/Q328
- Wikisource: http://www.wikidata.org/entity/Q263
- Wikidata: http://www.wikidata.org/entity/Q2013
- Portraitindex: http://www.wikidata.org/entity/Q2105262
- Hessische Biografie: :question: 
- ISNI: http://www.wikidata.org/entity/Q423048
- Historisches Lexikon der Schweiz: http://www.wikidata.org/entity/Q642074
- Filmportal: http://www.wikidata.org/entity/Q15706812
- NACO authority file: http://www.wikidata.org/entity/Q13219454
- BNF: http://www.wikidata.org/entity/Q19938912
- GND: http://www.wikidata.org/entity/Q36578
- Ostdeutsche Biographie: :question: 
- Kalliope Verbundkatalog: :question: 
- Neue Deutsche Biographie: http://www.wikidata.org/entity/Q222784
- Allgemeine Deutsche Biographie: http://www.wikidata.org/entity/Q590208
- Frankfurter Personenlexikon: http://www.wikidata.org/entity/Q39845173

**Comment by fsteeg** [comment]
Wikidata based `collection.id` values now also deployed to test:

http://test.lobid.org/gnd/118512676.json (sameAs with EntityFacts)
http://test.lobid.org/gnd/1006691-3.json (sameAs without EntityFacts)

**Comment by jentschk** [comment]
Absolutely with you. Will try to last minute squeeze this in for correction in Release 2018.03 (https://wiki.dnb.de/x/wgcbBQ)! Many thanks for alerting.

**Comment by acka47** [comment]
@jentschk Nice, thanks.

**Comment by fsteeg** [comment]
@acka47 Deployed to test: http://test.lobid.org/gnd/context.jsonld

**Comment by acka47** [comment]
@jentschk provided me with a list of all collections used in EntityFacts. Looks like I have missed some in https://github.com/hbz/lobid-gnd/issues/69#issuecomment-386567346:

- Volltexte im Sophie Project -> :question: 
- Biographie und Bibliographie bei 50 Klassiker der Soziologie -> :question: 
- Catalogus Professorum Rostochiensium (CPR) -> http://www.wikidata.org/entity/Q1050232
- Bayerisches Musiker-Lexikon Online -> http://www.wikidata.org/entity/Q47191
- Epigraphische Datenbank -> http://www.wikidata.org/entity/Q1347027 :question: 
- Klassiker der Geschichtswissenschaft -> :question: 
- Österreichisches Biographisches Lexikon -> http://www.wikidata.org/entity/Q25666 :question: 
- Vorarlberg Chronik -> :question:

**Comment by fsteeg** [comment]
> Looks like I have missed some [...]

Current fallback is to use the domain of the linked resource as the collection ID, see https://test.lobid.org/gnd/125217145.json so I think it's fine to deploy what we have here. I'll move the missing collections to a new issue and assign the pull request for this issue for review.
