### ISSUE TITLE
Add profession to auto-suggest labels

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#7]
_Copied from https://github.com/lobid/lodmill/issues/75._

> To improve disambiguation during auto-suggest selection we should add the profession to auto-suggest labels on the `/person` endpoint. The information is available through the GND links, but we have to resolve the labels

**Comment by acka47** [comment]
Probably has #24 as pre-requisite. 

This could be solved within #6 by allowing the selection of different fields for auto-suggestion à la:

https://lobid.org/authorities/search?q=preferredName:Goethe+AND+variantName:Goethe&format=json:preferredName,dateOfBirth,dateOfDeath,professionOrOccupation.preferredName

However, this would mean adding the preferred name for `professionOrOccupationto the data, see #

**Comment by fsteeg** [comment]
Depends partially on #24

**Comment by fsteeg** [comment]
> This could be solved within #6 by allowing the selection of different fields for auto-suggestion

Moved to https://github.com/hbz/lobid-gnd/issues/6#issuecomment-324634740, closing.
