### ISSUE TITLE
Move type from heading to list in detail view

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#70]
Only show the most specific type and make it clickable.

**Comment by fsteeg** [comment]
Deployed to test:

http://test.lobid.org/gnd/4031483-2
http://test.lobid.org/gnd/1081042850

**Comment by fsteeg** [comment]
> We should also use this as part of the html title like "Köln – lobid-gnd".

I think "lobid-gnd – Köln" would be better, otherwise for long titles the service name is not visible.

**Comment by acka47** [comment]
I was thinking that the entry name gives me more information than the service (i.e. when I have a smal tab "Köln" is more informative than "lobid-gnd" but it probably depends on the use case...

**Comment by fsteeg** [comment]
> "Köln" is more informative than "lobid-gnd" but it probably depends on the use case

Right, I was thinking of multiple tabs from different lobid services.

Redeployed to test as I suggested:

http://test.lobid.org/gnd/4031483-2
http://test.lobid.org/gnd/1081042850

**Comment by acka47** [comment]
We maybe should take the same approach for all three lobid-services.

- lobid-organisations currently does not have the organisation name in the title at all, see e.g. http://lobid.org/organisations/DE-605
- lobid-resources only has the resource name and not the service in the title,e.g. http://lobid.org/resources/HT006157459

**Comment by fsteeg** [comment]
Discussed offline: use only preferredName as title.

Redeployed to test:

http://test.lobid.org/gnd/4031483-2
http://test.lobid.org/gnd/1081042850

**Comment by ChristophEwertowski** [comment]
+1 for the changes in lobid-gnd.

**Comment by acka47** [comment]
+1
