### ISSUE TITLE
Verbesserungsvorschläge für Labels in gndo, Sachgruppen & Ländercodes

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#71]
In diesem Ticket werden Korrekturen und Verbesserungsvorschläge für die Labels in den folgenden Vokabularen gesammelt:

### [GND Ontology](http://d-nb.info/standards/elementset/gnd)

- [ ] Deutsches Label für [`gndo:professionalRelationship`](https://d-nb.info/standards/elementset/gnd#professionalRelationship) ist derzeit "Beruflich Beziehung" (sollte: "Berufliche Beziehung")
- [ ] Deutsches Label für [`gndo:opusNumericDesignationOfMusicalWork`](http://d-nb.info/standards/elementset/gnd#opusNumericDesignationOfMusicalWork) ist derzeit "Opus-Zahlung des Musikwerks" (sollte: "Opus-Zählung des Musikwerks")
- [ ] Für [`gndo:Manuscript`](https://d-nb.info/standards/elementset/gnd#Manuscript) wird das deutschsprachige Label "Schriftdenkmal" benutzt, was nicht wirklich gängig und für normale Menschen verwirrend sein dürfte. Warum nicht einfach "Manuskript" nehmen?

### [GND-Ländercodes](http://d-nb.info/standards/vocab/gnd/geographic-area-code)

- [ ] [XB-MM](http://d-nb.info/standards/vocab/gnd/geographic-area-code#XB-MM): Wäre nicht "Myanmar" korrekt?
- [ ] [XA-YUCS](http://d-nb.info/standards/vocab/gnd/geographic-area-code#XA-YUCS): Derzeitiges Label ist `Jugoslawien , Jugoslawien`.

### [GND-Sachgruppen](http://d-nb.info/standards/vocab/gnd/gnd-sc)

Sieht bisher alles gut aus.

**Comment by ChristophEwertowski** [comment]
## Berufe oder Beschäftigung
Stammen aus einer GND-Sachgruppe "Einzelne Berufe, Tätigkeiten, Funktionen; Religionszugehörigkeit, Weltanschauung". Filtert man diese nach "Schlagwort" (da es z.B. auch Personen gibt, die dieser Sachgruppe zugeordnet werden), werden einige Merkwürdigkeiten angezeigt.
- Es gibt "Argaringenieur", "Argraringenieurin" und "Diplom-Agraringenieur". Führen Diplom-Agraringenieure (und Diplom-Argraringenieurinnen!) andere Tätigkeiten aus als "gewöhnliche" Argraringenieure?

**Comment by acka47** [comment]
Siehe auch https://gist.github.com/acka47/e98d3503fe9ab6183ada4214e52e0fa1 für eine Liste der Labels aller Schlagwörter aus der Sachgruppe.

**Comment by ChristophEwertowski** [comment]
The issues will be dealt with in the [DNB JIRA](http://jira.dnb.de/secure/Dashboard.jspa). Closing this issue.
