### ISSUE TITLE
Variant names are gone

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#75]
I became aware of this by a feedback email from a user:

> 5.)Werden in lobid zukünftig die Synonyme mit angezeigt?
> 
> Die DNB bietet ja auch eine Web-basierte Suche in der GND an 
> http://d-nb.info/gnd/4129315-0 . Aktualierung minutengerecht für 
> Änderungen und neue Ts3-Sätze. Hier werden zu jeder Ansetzung die 
> Synomnyme mit angezeigt. Das finde ich sehr hilfreich! In lobid habe ich 
> keine Anzeige der Synonyme gesehen.

**Comment by fsteeg** [comment]
Will look into an implementation to expand details as you suggested in https://github.com/hbz/lobid-gnd/issues/47

**Comment by fsteeg** [comment]
Deployed to test:

http://test.lobid.org/gnd/4129315-0
http://test.lobid.org/gnd/118624822

**Comment by ChristophEwertowski** [comment]
+1

**Comment by fsteeg** [comment]
Discussed offline with @acka47: change cutoff to 10 values.

Deployed to test:

http://test.lobid.org/gnd/118624822
http://test.lobid.org/gnd/118540238

**Comment by acka47** [comment]
+1
