### ISSUE TITLE
Visualize intra-GND relations in detail views

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#77]
Requested via email by GND user.

> 1.)Ist eine graphische Visualisierung des Suchergebnisses mit z.B. Topic 
> Maps, zusätzlich zu der aktuellen textuellen Darstellung geplant?
> 
> -Für die Arbeit mit und in der GND wäre das enorm hilfreich!

This could be implemented as a tab that shows the relations of a specific entry with other GND resources as a browsable graph, e.g. inter-personal relations (`hasAuntUncle`, `hasSibling`, `hasFriend`, `professionalRelationship`, `hasChild`, `acquaintanceshipOrFriendship`, `hasParent`...), profession (`professionOrOccupation`) or related, broader, narrower and instantiated terms etc.(`relatedTerm`, `broaderTermGeneral`, `broaderTermInstantial`, `broaderTermPartitive`). Opening the tab, the describe dnode is in the center Clicking on other nodes, their relations to further nodes is shown.

**Comment by fsteeg** [comment]
Deployed to test:

http://test.lobid.org/gnd/4770075-0
http://test.lobid.org/gnd/7855044-0
http://test.lobid.org/gnd/118624822

**Comment by fsteeg** [comment]
Experimenting with an alternative, more visual, less field-oriented details layout:

http://test.lobid.org/gnd/118624822.visual
http://test.lobid.org/gnd/1045328480.visual
http://test.lobid.org/gnd/7855044-0.visual

**Comment by fsteeg** [comment]
Discussed offline:

- Keep header from .visual experiment (types as label, subtitle)
- Move current field-oriented view into a fields tab
- Move larger visual view into a relations tab
- Clicking nodes in the visual tab takes us to the entity's visual tab

**Comment by fsteeg** [comment]
Deployed to stage:

https://test.lobid.org/gnd/4172302-8
http://test.lobid.org/gnd/118634313
http://test.lobid.org/gnd/4024729-6

**Comment by fsteeg** [comment]
Discussed offline:

- Show fields tab as default, except when clicking on node in graph
- Never show fields on the right side, always left

**Comment by fsteeg** [comment]
Deployed to stage:

https://test.lobid.org/gnd/4172302-8
http://test.lobid.org/gnd/118634313
http://test.lobid.org/gnd/4024729-6

**Comment by acka47** [comment]
I think this looks good now and can be deployed to production as is. 

Last quibbles:
- There are quite a few cases where labels can't be read because they are overlapping, e.g. http://test.lobid.org/gnd/118512676 (property label "Sterbeort") & http://test.lobid.org/gnd/118514652 (two person names overlapping). Maybe we can make it all readable or at least a node or label should  be readable when I hover over it.
- For some graphs the window still is too small, see e.g. http://test.lobid.org/gnd/118529579, http://test.lobid.org/gnd/118711083 or http://test.lobid.org/gnd/118571575.html. I guess we will just leave it as is for now.

**Comment by fsteeg** [comment]
Tweaked the graph physics for improved layout, see:

http://test.lobid.org/gnd/118512676#rels
http://test.lobid.org/gnd/118514652#rels
http://test.lobid.org/gnd/118711083#rels

Also added field search on edge clicks, and popups.

**Comment by acka47** [comment]
Looks really nice now. +1
