### ISSUE TITLE
Improve documentation of search operators

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#83]
We received some feedback via email (using the feedback function in the upper right). Feedback for URL http://lobid.org/gnd/search?q=Muka%2Barno%C5%A1t:

> Kann man die Suche so einschraenken, dass nach dem gleichzeitigen 
> Auftreten des Vor- und Nachnamens gesucht wird. So wie in der alten API 
> oder dem GNDPortal?

We have this already covered with boolean AND but the search operators aren't shown to customers very prominently but only in a tooltip over the search. We need to somehow point the operators out more prominently.

**Comment by acka47** [comment]
As discussed offline, we will put the information as placeholder in light grey into the search field instead of the tool tip.

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd

**Comment by acka47** [comment]
+1 with the changes we just discussed offline.
