### ISSUE TITLE
Put all IRIs in JSON objects

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#85]
To have the data homogeneous and to prepare for adding labels (#24) and EntityFacts data (#69) we will use objects/an object array for (nearly) all fields that contain IRIs as value.

To find out, which are these fields you can do `$ curl http://lobid.org/gnd/context.jsonld | grep -B 2 -A 1 '"@type":"@id"'`. See the result (tweaked a bit so that it is valid JSON) at https://gist.github.com/acka47/133f1397ef704e7b38a65c2c46be1dbc.

Most of these properties aren't actually used in lobid-gnd, e.g. [`annotator`](http://lobid.org/gnd/search?q=_exists_%3Aannotator) or [`celebratedFamily`](http://lobid.org/gnd/search?q=_exists_%3AcelebratedFamily), so the actual list is much smaller.

**Comment by acka47** [comment]
With @fsteeg I talked about adding the label on the RDF level. We decided to use the same "side car" approach as in the other lobid services with `label` mapped to `rdfs:label` in the context. So we will add a statement à la `_:subject rdfs:label "Label" .` about every value that is an IRI making it an object in the resulting JSON-LD.

For labels from the GND and the associated controlled vocabularies (gender, geographic area code, GND subject category) we take the value of `gndo:preferredName` respectively of `skos:prefLabel` of the linked resource. For other properties with IRIs as values (`wikipedia`, `homepage`, `relatedDdcWithDegreeOfDeterminacy3` etc.) we have to set a general label.

Example (turtle):

```n3
@prefix gndo: <http://d-nb.info/standards/elementset/gnd#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.

<http://d-nb.info/gnd/142612960>
  gndo:professionOrOccupation <http://d-nb.info/gnd/4009836-9> ;
  gndo:affiliation <http://d-nb.info/gnd/2047974-8> ;
  gndo:geographicAreaCode <http://d-nb.info/standards/vocab/gnd/geographic-area-code#XA-DE> .

<http://d-nb.info/gnd/4009836-9> rdfs:label "Chemiker" .
<http://d-nb.info/gnd/2047974-8> rdfs:label "Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen" .
<http://d-nb.info/standards/vocab/gnd/geographic-area-code#XA-DE> rdfs:label "Deutschland"@de .
```

As one can see, some of the labels are available in German _and_ English. So we have to think about whether we want to provide both in the JSON-LD (which would mean using `"@container": "@language"`).

**Comment by acka47** [comment]
> As one can see, some of the labels are available in German _and_ English. So we have to think about whether we want to provide both in the JSON-LD (which would mean using `"@container": "@language"`).

Talking to @fsteeg we decided to use the simple approach as most times we only have a German (respectively a not specified) label.

**Comment by fsteeg** [comment]
> Talking to @fsteeg we decided to use the simple approach as most times we only have a German (respectively a not specified) label.

What about the non-IRI fields where we currently have language tags, like `definition` and `biographicalOrHistoricalInformation`?

**Comment by acka47** [comment]
Good question. It doesn't look like any of them have strings that are not in German, see http://lobid.org/gnd/search?q=_exists_%3Adefinition.en and http://lobid.org/gnd/search?q=_exists_%3AbiographicalOrHistoricalInformation.en. Thus, it probably makes sense to remove/ignore the language tagging. Even better, we could add the language to the context like so:

```json
{
  "@context":{
    "definition":{
      "@id":"gnd:definition",
      "@language":"de"
    },
    "biographicalOrHistoricalInformation":{
      "@id":"gnd:definition",
      "@language":"de"
    }
  }
}
```

Like this, we keep the language tagging but without language indexing and thus have more homogeneous data.

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/gnd/118548018.json

**Comment by acka47** [comment]
Looks good but one label seems broken:

```json
{
  "id": "http://d-nb.info/standards/vocab/gnd/gnd-sc#12.2p",
  "label": "Personen zu Literaturgeschichte\n            (Schriftsteller)"
}
```

**Comment by acka47** [comment]
Also, in search result lists occupations etc. are not shown on test at the moment.

(What seems to be a good thing is that there is no label for deprecated URIs.)

**Comment by fsteeg** [comment]
> Looks good but one label seems broken

Fixed with test in https://github.com/hbz/lobid-gnd/commit/e933598d2fbe15c31e1e21b19190d20da8f2083d, will be part of the next nightly conversion.

> Also, in search result lists occupations etc. are not shown on test at the moment

Fixed on test: https://test.lobid.org/gnd/search?q=haynrix

**Comment by acka47** [comment]
+1
