### ISSUE TITLE
Add provenance information to JSON-LD

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#89]
I suggest the following approach:

```json
{
  "id":"http://d-nb.info/gnd/142612960",
  "describedBy":{
    "id":"http://lobid.org/gnd/142612960",
    "label":"lobid-gnd description of 'Peter Reimer'",
    "provider":{
      "id":"http://lobid.org/organisations/DE-605#!",
      "label":"hbz – Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen"
    },
    "isBasedOn":[
      "http://hub.culturegraph.org/entityfacts/142612960",
      "https://d-nb.info/gnd/142612960/about/lds.rdf"
    ]
  }
}
```

This basically adds the information we recently added into the HTML to the JSON-LD. And we could also use this object to add  creation and modification dates (see #37).

**Comment by acka47** [comment]
With the October release there will also be a modification date in the data. From http://www.dnb.de/SharedDocs/Downloads/DE/DNB/service/rundschreiben20180709AenderungRdf20183.pdf?__blob=publicationFile:

>  Es werden jetzt auch Meta-Angaben über die Beschreibung der Entitäten
angegeben. Zunächst handelt es sind um die beiden Angaben "Änderungsdatum"
und "Lizenz". Konkret: wann ist die Beschreibung der Entität zuletzt geändert
worden und unter welchen Bedingungen darf die Beschreibung weiterverwendet
werden. Zu beachten ist, dass das Änderungsdatum (Property „dcterms:modified“)
aus technischen Gründen vorerst der letzten Änderung des zugrundeliegenden
Datensatzes im Bibliothekssystem der DNB entspricht. Unberücksichtigt bleiben
dabei im Fall von GND-Entitäten also zunächst Änderungen in den angereicherten
Links (Properties foaf:page und viele der owl:sameAs-Aussagen).
Dies bedeutet, dass das Datum keinen Hinweis darauf gibt, ob seit dem Zeitpunkt
zum Beispiel ein owl:sameAs-Link auf VIAF oder ein foaf:page-Link auf Wikipedia
zugefügt oder entfernt wurde. Wir bitten, diese Ungenauigkeit bei der Nachnutzung
zu berücksichtigen

**Comment by acka47** [comment]
The data is now added, but we have to add the new properties to the context as it currently looks like this:

```
{
   "http://www.w3.org/2007/05/powder-s#describedby":{
      "id":"http://d-nb.info/gnd/11850391X/about",
      "http://purl.org/dc/terms/license":{
         "id":"http://creativecommons.org/publicdomain/zero/1.0/",
         "label":"http://creativecommons.org/publicdomain/zero/1.0/"
      },
      "http://purl.org/dc/terms/modified":{
         "type":"http://www.w3.org/2001/XMLSchema#dateTime",
         "@value":"2018-10-24T10:57:57.000"
      },
      "label":"11850391X/about"
   }
}
```

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/gnd/1068849886.json

There are 63 items without `describedBy`, I suspect this is an issue with the current index, where older updates may have replaced newer baseline items (I reused an older backup of updates). Will create a fresh index for production deployment.

**Comment by acka47** [comment]
The `describedBy` information for the 63 items is also missing at the DNB GND. Will open an issue over there.
