### ISSUE TITLE
Offer content type JSON Lines and format gzip

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#91]
As in lobid-resources, see http://lobid.org/resources/api#content_types

**Comment by acka47** [comment]
And also support format gzip via content header.

**Comment by fsteeg** [comment]
Deployed to stage, see:

http://stage.lobid.org/gnd/search?q=ehrenfeld&format=bulk

Tested uncompressed request for all corporate bodies:

`curl "http://stage.lobid.org/gnd/search?q=type:CorporateBody&format=bulk" > bulk.jsonl`

This yields a 1.7 GB file. Took about:

- 1:30 minutes on the same machine
- 2:30 minutes on our local network
- 6:45 minutes on our Eduroam WLAN

Tested same request, but compressed (handled by the Apache proxy):

`curl --header "Accept-Encoding: gzip" "http://stage.lobid.org/gnd/search?q=type:CorporateBody&format=bulk" > bulk.gz`

This yields a 174 MB file. Took about:

- 1:30 minutes on the same machine
- 1:30 minutes on our local network
- 1:30 minutes on our Eduroam WLAN

See also documentation: http://stage.lobid.org/gnd/api#content_types

**Comment by acka47** [comment]
You should also be able to get jsonlines and gzip for a filter query. I tried `curl --header "Accept: application/x-jsonlines" "http://stage.lobid.org/gnd/search?filter=%2B%28type%3APlaceOrGeographicName%29" > geographika.jsonl` and am currently pulling the whole GND.

Furthermore, as we discussed online we will use `jsonl` instead of `bulk` (and adjust this in lobid-resources at a later point as well).

**Comment by acka47** [comment]
Downloading the whole GND as gzip (1,5 GB, unzipped 14 GB) took just 13 minutes. So, this definitely works like a charm.

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/gnd/search?filter=ehrenfeld&format=jsonl
http://stage.lobid.org/gnd/api#content_types

**Comment by fsteeg** [comment]
Deployed to stage.

Unsupported:

http://stage.lobid.org/gnd/4074335-4.jsonl
http://stage.lobid.org/gnd/4074335-4.jsonfoo
http://stage.lobid.org/gnd/4074335-4.json:suggest
http://stage.lobid.org/gnd/search?format=jsonfoo

Supported:

http://stage.lobid.org/gnd/search?format=json:suggest
http://stage.lobid.org/gnd/search?format=jsonl

**Comment by acka47** [comment]
+1
