### ISSUE TITLE
Several fields are not shown in HTML

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#93]
For example `formOfWorkAndExpression`, see http://lobid.org/gnd/1064607985 or `addressee`, see http://lobid.org/gnd/1078453608 and probably many more.

We should somehow automatically find out which are missing. @fsteeg, maybe it make sense to take this into account while doing the work you described in https://github.com/hbz/lobid-gnd/issues/24#issuecomment-385370171?

**Comment by fsteeg** [comment]
Automatically showing all fields would require major changes to the code. The current implementation binds the JSON to objects with specified fields (see https://github.com/hbz/lobid-gnd/blob/master/app/models/AuthorityResource.java#L28).

Even if we would implement a way to show all, I'm sure there will be cases that we don't want to display or display in a specific format, so I don't think this would be time well invested. Instead, I think we should collect the fields that are missing and add them. I'll start a list here, also moving https://github.com/hbz/lobid-gnd/issues/87 here.

- `affiliation` http://lobid.org/gnd/142612960
- `formOfWorkAndExpression` http://lobid.org/gnd/1064607985
- `addressee` http://lobid.org/gnd/1078453608

**Comment by fsteeg** [comment]
Deployed to test, see:

- `affiliation` http://test.lobid.org/gnd/142612960
- `formOfWorkAndExpression` http://test.lobid.org/gnd/1064607985
- `addressee` http://test.lobid.org/gnd/1078453608

**Comment by acka47** [comment]
Fields that are still not shown:

- [ ] `accordingWork`, e.g. http://test.lobid.org/gnd/4315345-8
- [ ] `accreditedArtist`, e.g. http://test.lobid.org/gnd/7680374-0
- [ ] `accreditedAuthor`, e.g. http://test.lobid.org/gnd/7560862-5
- [ ] `accreditedComposer`, e.g. http://test.lobid.org/gnd/107003844X
- [ ] `acquaintanceshipOrFriendship`, e.g. http://test.lobid.org/gnd/118634313
- [ ] `architect`, e.g. http://test.lobid.org/gnd/4255982-0
- [ ] `arranger`, e.g. http://test.lobid.org/gnd/1080969756
- [ ] `firstArtist` and `artist`, e.g. http://test.lobid.org/gnd/4252985-2
- [ ] `author`, e.g. http://test.lobid.org/gnd/7764818-3
- [ ] `benefactor`, e.g. http://test.lobid.org/gnd/2072947-9
- [ ] `bookdesigner`, e.g. http://test.lobid.org/gnd/1047507773
- [ ] `buildingOwner`, e.g. http://test.lobid.org/gnd/1050804384
- [ ] `cartographer`, e.g. http://test.lobid.org/gnd/1079856463
- [ ] `celebratedCorporateBody`, e.g. http://test.lobid.org/gnd/7783668-6
- [ ] `celebratedPerson`, e.g. http://test.lobid.org/gnd/1046441663
- [ ] `celebratedTopic`, e.g. http://test.lobid.org/gnd/1050813138
- [ ] `characteristicPlace`, e.g. http://test.lobid.org/gnd/1028094760
- [ ] `choreographer`, e.g. http://test.lobid.org/gnd/300616805
- [ ] `citedArtist`, e.g. http://test.lobid.org/gnd/300198345
- [ ] `citedAuthor`, e.g. http://test.lobid.org/gnd/1093439246
- [ ] `citedComposer`, e.g. http://test.lobid.org/gnd/300947747
- [ ] `collector`, e.g. http://test.lobid.org/gnd/1025028600
- [ ] `compiler`, e.g. http://test.lobid.org/gnd/1124266593
- [ ] `complexSeeReferenceSubject`, e.g. http://test.lobid.org/gnd/7511450-1
- [ ] `composer`, e.g. http://test.lobid.org/gnd/7617789-0
- [ ] `conferrer`, e.g. http://test.lobid.org/gnd/1136438688
- [ ] `contributingCorporateBody`, e.g. http://test.lobid.org/gnd/2106525-1
- [ ] `contributingPerson`, e.g. http://test.lobid.org/gnd/4207126-4
- [ ] `contributingPlaceOrGeographicName`, e.g. http://test.lobid.org/gnd/4143215-0
- [ ] `copist`, e.g. http://test.lobid.org/gnd/1053952899
- [ ] `corporateBodyIsMember`, e.g. http://test.lobid.org/gnd/2008246-0
- [ ] `correspondent`, e.g. http://test.lobid.org/gnd/1024181553
- [ ] `creator`, e.g. http://test.lobid.org/gnd/4070485-3
- [ ] `curator`, e.g. http://test.lobid.org/gnd/1036480879

**Comment by acka47** [comment]
As one can see, the list is already very long although I only went through 25% of https://gist.github.com/acka47/133f1397ef704e7b38a65c2c46be1dbc. For now, we will merge and deploy this as is and work on a solution to generally show all fields with an additional config file to define the order of the fields.
