### ISSUE TITLE
Self references in GND entries

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#94]
Indexing issues made me aware of some self references in GND entries. These don't seem right.

Here are the details:

https://d-nb.info/gnd/4100125-4 `broaderTermInstantial`
https://d-nb.info/gnd/4128319-3 `relatedTerm`
https://d-nb.info/gnd/4134736-5 `relatedTerm`
https://d-nb.info/gnd/4200101-8 `broaderTermInstantial`
https://d-nb.info/gnd/4200437-8 `broaderTermInstantial`
https://d-nb.info/gnd/114744068 `sameAs`
https://d-nb.info/gnd/120116766 `sameAs`
https://d-nb.info/gnd/2136169-1 `sameAs`
https://d-nb.info/gnd/4463462-6 `broaderTermInstantial`
https://d-nb.info/gnd/4619668-7 `broaderTermInstantial`
https://d-nb.info/gnd/4770075-0 `precedingCorporateBody`
https://d-nb.info/gnd/1010346326 `sameAs`
https://d-nb.info/gnd/1022370421 `sameAs`
https://d-nb.info/gnd/1060152614 `sameAs`

**Comment by ChristophEwertowski** [comment]
After I looked up which MARC fields are converted to RDF I sent a list with the GND-URIs, the RDF properties and MARC numbers to cataloging expert Mrs. B.

**Comment by ChristophEwertowski** [comment]
Mrs. Bl. told me that the cases will be dealt with. Exception to this are the cases with MARC field 024 / `sameAs`:
https://d-nb.info/gnd/114744068
https://d-nb.info/gnd/120116766
https://d-nb.info/gnd/2136169-1
https://d-nb.info/gnd/1010346326
https://d-nb.info/gnd/1022370421
https://d-nb.info/gnd/1060152614

They have the order to not change the standard identifier field. @acka47 : What's up with our Jira account / direct channel for listing GND improvements/errors?

**Comment by ChristophEwertowski** [comment]
This issue will be dealt with in a [DNB JIRA issue](http://jira.dnb.de/browse/GND-53). As these GND self references don't break anything for us at the moment, I'm closing this issue.
