### ISSUE TITLE
New subclasses for type CorporateBody

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-gnd#97]
From the 15th of May on new subclasses of `CorporateBody` are used. From a [DNB newsletter](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/service/rundschreiben20180216AenderungenFormatRDF.pdf?__blob=publicationFile):

> Neuerung: Vier weitere Unterarten von Körperschaften („gndo:CorporateBody“) werden explizit mit rdf:type als solche ausgezeichnet. Es handelt sich um die Klassen „gndo:Company“, „gndo:MusicalCorporateBody“, „gndo:ReligiousCorporateBody“ und „gndo:ReligiousAdministrativeUnit“. Sie sind jeweils Unterklassen (rdfs:subClassOf) von „gndo:CorporateBody“, vgl. 3. Abschnitt zur GND-Ontologie. Wie in dem Fall üblich, wird auf eine weitere explizite Zuordnung zur Oberklasse „gndo:CorporateBody“ verzichtet.

> Neuerung: Unselbständige Teile von Musiktonträgern („schema:MusicRelease“) werden jetzt deutlich gekennzeichnet mit „rdf:type schema:MusicRecording“. [...] Unselbständige Teile werden nicht mehr aktiv erfasst, in den Altdaten sind ca. 180.000 solcher Entitäten vorhanden. 

> Neuerung: Unselbständige Teile von Musikalien („vivo:Score“) werden jetzt deutlich gekennzeichnet mit „rdf:type bibo:DocumentPart“. [...] Unselbständige Teile werden nicht mehr aktiv erfasst, in den Altdaten sind ca. 47.000 solcher Entitäten vorhanden.

For the example please look at the newsletter after the data is published.

**Comment by acka47** [comment]
Duplicate of #41 which is already resolved. Closing.
