### ISSUE TITLE
Show all content from JSON documents in details view

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#98]
Originated in https://github.com/hbz/lobid-gnd/issues/93

We should show all content from the JSON documents by default.

Add config for specific fields to exclude, and for sorting the fields.

**Comment by fsteeg** [comment]
Deployed to stage, see http://test.lobid.org/gnd/107003844X and other samples listed in https://github.com/hbz/lobid-gnd/issues/93#issuecomment-386232275.

**Comment by acka47** [comment]
Nice. +1
